package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDSpecie;
import it.aizoon.ersaf.dto.generati.CarDSpecieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDSpecieMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDSpecie, CarDSpecieExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDSpecieExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDSpecieExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idSpecie);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDSpecie record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDSpecie record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDSpecie> selectByExample(CarDSpecieExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDSpecie selectByPrimaryKey(Long idSpecie);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDSpecie record, @Param("example") CarDSpecieExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDSpecie record, @Param("example") CarDSpecieExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDSpecie record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_specie
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDSpecie record);
}