package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDCostante;
import it.aizoon.ersaf.dto.generati.CarDCostanteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDCostanteMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDCostante, CarDCostanteExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	long countByExample(CarDCostanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int deleteByExample(CarDCostanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int deleteByPrimaryKey(Long idCostante);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int insert(CarDCostante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int insertSelective(CarDCostante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	List<CarDCostante> selectByExampleWithBLOBs(CarDCostanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	List<CarDCostante> selectByExample(CarDCostanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	CarDCostante selectByPrimaryKey(Long idCostante);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") CarDCostante record, @Param("example") CarDCostanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int updateByExampleWithBLOBs(@Param("record") CarDCostante record, @Param("example") CarDCostanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int updateByExample(@Param("record") CarDCostante record, @Param("example") CarDCostanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int updateByPrimaryKeySelective(CarDCostante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int updateByPrimaryKeyWithBLOBs(CarDCostante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_costante
	 * @mbg.generated  Mon Sep 19 15:32:11 CEST 2022
	 */
	int updateByPrimaryKey(CarDCostante record);
}