package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDMezzoPagamento;
import it.aizoon.ersaf.dto.generati.CarDMezzoPagamentoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDMezzoPagamentoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDMezzoPagamento, CarDMezzoPagamentoExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDMezzoPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDMezzoPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idMezzoPagamento);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDMezzoPagamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDMezzoPagamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDMezzoPagamento> selectByExample(CarDMezzoPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDMezzoPagamento selectByPrimaryKey(Long idMezzoPagamento);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDMezzoPagamento record,
      @Param("example") CarDMezzoPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDMezzoPagamento record, @Param("example") CarDMezzoPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDMezzoPagamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_mezzo_pagamento
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDMezzoPagamento record);
}