package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDGenere;
import it.aizoon.ersaf.dto.generati.CarDGenereExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDGenereMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDGenere, CarDGenereExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDGenereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDGenereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idGenere);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDGenere record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDGenere record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDGenere> selectByExample(CarDGenereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDGenere selectByPrimaryKey(Long idGenere);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDGenere record, @Param("example") CarDGenereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDGenere record, @Param("example") CarDGenereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDGenere record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_genere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDGenere record);
}