package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoOrgNocivo;
import it.aizoon.ersaf.dto.generati.CarDTipoOrgNocivoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoOrgNocivoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoOrgNocivo, CarDTipoOrgNocivoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	long countByExample(CarDTipoOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	int deleteByExample(CarDTipoOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	int deleteByPrimaryKey(Long idTipoOrgNocivo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	int insert(CarDTipoOrgNocivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	int insertSelective(CarDTipoOrgNocivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	List<CarDTipoOrgNocivo> selectByExample(CarDTipoOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	CarDTipoOrgNocivo selectByPrimaryKey(Long idTipoOrgNocivo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	int updateByExampleSelective(@Param("record") CarDTipoOrgNocivo record,
			@Param("example") CarDTipoOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	int updateByExample(@Param("record") CarDTipoOrgNocivo record, @Param("example") CarDTipoOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	int updateByPrimaryKeySelective(CarDTipoOrgNocivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_org_nocivo
	 * @mbg.generated  Mon Sep 06 16:39:49 CEST 2021
	 */
	int updateByPrimaryKey(CarDTipoOrgNocivo record);
}