package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoComunicazione;
import it.aizoon.ersaf.dto.generati.CarDTipoComunicazioneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoComunicazioneMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoComunicazione, CarDTipoComunicazioneExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	long countByExample(CarDTipoComunicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	int deleteByExample(CarDTipoComunicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	int deleteByPrimaryKey(Long idTipoComunicazione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	int insert(CarDTipoComunicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	int insertSelective(CarDTipoComunicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	List<CarDTipoComunicazione> selectByExample(CarDTipoComunicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	CarDTipoComunicazione selectByPrimaryKey(Long idTipoComunicazione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	int updateByExampleSelective(@Param("record") CarDTipoComunicazione record,
			@Param("example") CarDTipoComunicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	int updateByExample(@Param("record") CarDTipoComunicazione record,
			@Param("example") CarDTipoComunicazioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	int updateByPrimaryKeySelective(CarDTipoComunicazione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_comunicazione
	 * @mbg.generated  Mon May 03 11:52:53 CEST 2021
	 */
	int updateByPrimaryKey(CarDTipoComunicazione record);
}