package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDAssociazioneSezione;
import it.aizoon.ersaf.dto.generati.CarDAssociazioneSezioneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDAssociazioneSezioneMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDAssociazioneSezione, CarDAssociazioneSezioneExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDAssociazioneSezioneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDAssociazioneSezioneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idAssociazioneSezione);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDAssociazioneSezione record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDAssociazioneSezione record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDAssociazioneSezione> selectByExample(CarDAssociazioneSezioneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDAssociazioneSezione selectByPrimaryKey(Long idAssociazioneSezione);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDAssociazioneSezione record,
      @Param("example") CarDAssociazioneSezioneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDAssociazioneSezione record,
      @Param("example") CarDAssociazioneSezioneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDAssociazioneSezione record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDAssociazioneSezione record);
}