package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDNaturaCollo;
import it.aizoon.ersaf.dto.generati.CarDNaturaColloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDNaturaColloMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDNaturaCollo, CarDNaturaColloExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDNaturaColloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDNaturaColloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idNaturaCollo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDNaturaCollo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDNaturaCollo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDNaturaCollo> selectByExample(CarDNaturaColloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDNaturaCollo selectByPrimaryKey(Long idNaturaCollo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDNaturaCollo record,
      @Param("example") CarDNaturaColloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDNaturaCollo record, @Param("example") CarDNaturaColloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDNaturaCollo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_natura_collo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDNaturaCollo record);
}