package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDGruppo;
import it.aizoon.ersaf.dto.generati.CarDGruppoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDGruppoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDGruppo, CarDGruppoExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDGruppoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDGruppoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idGruppo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDGruppo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDGruppo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDGruppo> selectByExample(CarDGruppoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDGruppo selectByPrimaryKey(Long idGruppo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDGruppo record, @Param("example") CarDGruppoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDGruppo record, @Param("example") CarDGruppoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDGruppo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDGruppo record);
}