package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoFlusso;
import it.aizoon.ersaf.dto.generati.CarDTipoFlussoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoFlussoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoFlusso, CarDTipoFlussoExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    long countByExample(CarDTipoFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int deleteByExample(CarDTipoFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int deleteByPrimaryKey(Long idTipoFlusso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int insert(CarDTipoFlusso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int insertSelective(CarDTipoFlusso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    List<CarDTipoFlusso> selectByExample(CarDTipoFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    CarDTipoFlusso selectByPrimaryKey(Long idTipoFlusso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarDTipoFlusso record, @Param("example") CarDTipoFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByExample(@Param("record") CarDTipoFlusso record, @Param("example") CarDTipoFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByPrimaryKeySelective(CarDTipoFlusso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByPrimaryKey(CarDTipoFlusso record);
}