package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDStrutturaAttrezzatura;
import it.aizoon.ersaf.dto.generati.CarDStrutturaAttrezzaturaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDStrutturaAttrezzaturaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDStrutturaAttrezzatura, CarDStrutturaAttrezzaturaExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    long countByExample(CarDStrutturaAttrezzaturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    int deleteByExample(CarDStrutturaAttrezzaturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    int deleteByPrimaryKey(Long idStrutturaAttrezzatura);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    int insert(CarDStrutturaAttrezzatura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    int insertSelective(CarDStrutturaAttrezzatura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    List<CarDStrutturaAttrezzatura> selectByExample(CarDStrutturaAttrezzaturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    CarDStrutturaAttrezzatura selectByPrimaryKey(Long idStrutturaAttrezzatura);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    int updateByExampleSelective(@Param("record") CarDStrutturaAttrezzatura record, @Param("example") CarDStrutturaAttrezzaturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    int updateByExample(@Param("record") CarDStrutturaAttrezzatura record, @Param("example") CarDStrutturaAttrezzaturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    int updateByPrimaryKeySelective(CarDStrutturaAttrezzatura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_struttura_attrezzatura
     *
     * @mbg.generated Wed Dec 23 15:06:54 CET 2020
     */
    int updateByPrimaryKey(CarDStrutturaAttrezzatura record);
}