package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoModello;
import it.aizoon.ersaf.dto.generati.CarDTipoModelloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoModelloMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoModello, CarDTipoModelloExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    long countByExample(CarDTipoModelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int deleteByExample(CarDTipoModelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int deleteByPrimaryKey(Long idTipoModello);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int insert(CarDTipoModello record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int insertSelective(CarDTipoModello record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    List<CarDTipoModello> selectByExample(CarDTipoModelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    CarDTipoModello selectByPrimaryKey(Long idTipoModello);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarDTipoModello record, @Param("example") CarDTipoModelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int updateByExample(@Param("record") CarDTipoModello record, @Param("example") CarDTipoModelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int updateByPrimaryKeySelective(CarDTipoModello record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_modello
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int updateByPrimaryKey(CarDTipoModello record);
}