package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDProdotto;
import it.aizoon.ersaf.dto.generati.CarDProdottoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDProdottoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDProdotto, CarDProdottoExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDProdottoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDProdottoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idProdotto);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDProdotto record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDProdotto record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDProdotto> selectByExample(CarDProdottoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDProdotto selectByPrimaryKey(Long idProdotto);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDProdotto record, @Param("example") CarDProdottoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDProdotto record, @Param("example") CarDProdottoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDProdotto record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDProdotto record);
}