package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDClasse;
import it.aizoon.ersaf.dto.generati.CarDClasseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDClasseMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDClasse, CarDClasseExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDClasseExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDClasseExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idClasse);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDClasse record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDClasse record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDClasse> selectByExample(CarDClasseExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDClasse selectByPrimaryKey(Long idClasse);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDClasse record, @Param("example") CarDClasseExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDClasse record, @Param("example") CarDClasseExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDClasse record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_classe
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDClasse record);
}