package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDRuolo;
import it.aizoon.ersaf.dto.generati.CarDRuoloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDRuoloMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDRuolo, CarDRuoloExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDRuoloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDRuoloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idRuolo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDRuolo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDRuolo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDRuolo> selectByExample(CarDRuoloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDRuolo selectByPrimaryKey(Long idRuolo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDRuolo record, @Param("example") CarDRuoloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDRuolo record, @Param("example") CarDRuoloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDRuolo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_ruolo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDRuolo record);
}