package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDUnitaMisura;
import it.aizoon.ersaf.dto.generati.CarDUnitaMisuraExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDUnitaMisuraMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDUnitaMisura, CarDUnitaMisuraExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDUnitaMisuraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDUnitaMisuraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idUnitaMisura);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDUnitaMisura record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDUnitaMisura record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDUnitaMisura> selectByExample(CarDUnitaMisuraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDUnitaMisura selectByPrimaryKey(Long idUnitaMisura);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDUnitaMisura record,
      @Param("example") CarDUnitaMisuraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDUnitaMisura record, @Param("example") CarDUnitaMisuraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDUnitaMisura record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDUnitaMisura record);
}