package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoControllo;
import it.aizoon.ersaf.dto.generati.CarDTipoControlloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoControlloMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoControllo, CarDTipoControlloExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDTipoControlloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDTipoControlloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idTipoControllo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDTipoControllo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDTipoControllo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDTipoControllo> selectByExample(CarDTipoControlloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDTipoControllo selectByPrimaryKey(Long idTipoControllo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDTipoControllo record,
      @Param("example") CarDTipoControlloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDTipoControllo record, @Param("example") CarDTipoControlloExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDTipoControllo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_controllo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDTipoControllo record);
}