package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipologiaControllo;
import it.aizoon.ersaf.dto.generati.CarDTipologiaControlloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipologiaControlloMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipologiaControllo, CarDTipologiaControlloExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	long countByExample(CarDTipologiaControlloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int deleteByExample(CarDTipologiaControlloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int deleteByPrimaryKey(Long idTipologiaControllo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int insert(CarDTipologiaControllo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int insertSelective(CarDTipologiaControllo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	List<CarDTipologiaControllo> selectByExample(CarDTipologiaControlloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	CarDTipologiaControllo selectByPrimaryKey(Long idTipologiaControllo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int updateByExampleSelective(@Param("record") CarDTipologiaControllo record,
			@Param("example") CarDTipologiaControlloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int updateByExample(@Param("record") CarDTipologiaControllo record,
			@Param("example") CarDTipologiaControlloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int updateByPrimaryKeySelective(CarDTipologiaControllo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_controllo
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int updateByPrimaryKey(CarDTipologiaControllo record);
}