package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDRangeTariffa;
import it.aizoon.ersaf.dto.generati.CarDRangeTariffaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDRangeTariffaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDRangeTariffa, CarDRangeTariffaExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDRangeTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDRangeTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idRangeTariffa);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDRangeTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDRangeTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDRangeTariffa> selectByExample(CarDRangeTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDRangeTariffa selectByPrimaryKey(Long idRangeTariffa);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDRangeTariffa record,
      @Param("example") CarDRangeTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDRangeTariffa record, @Param("example") CarDRangeTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDRangeTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_range_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDRangeTariffa record);
}