package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDGruppoZonaProtetta;
import it.aizoon.ersaf.dto.generati.CarDGruppoZonaProtettaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDGruppoZonaProtettaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDGruppoZonaProtetta, CarDGruppoZonaProtettaExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	long countByExample(CarDGruppoZonaProtettaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int deleteByExample(CarDGruppoZonaProtettaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int deleteByPrimaryKey(Long idGruppoZonaProtetta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int insert(CarDGruppoZonaProtetta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int insertSelective(CarDGruppoZonaProtetta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	List<CarDGruppoZonaProtetta> selectByExample(CarDGruppoZonaProtettaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	CarDGruppoZonaProtetta selectByPrimaryKey(Long idGruppoZonaProtetta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") CarDGruppoZonaProtetta record,
			@Param("example") CarDGruppoZonaProtettaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int updateByExample(@Param("record") CarDGruppoZonaProtetta record,
			@Param("example") CarDGruppoZonaProtettaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int updateByPrimaryKeySelective(CarDGruppoZonaProtetta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_gruppo_zona_protetta
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int updateByPrimaryKey(CarDGruppoZonaProtetta record);
}