package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDNormaVerbale;
import it.aizoon.ersaf.dto.generati.CarDNormaVerbaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDNormaVerbaleMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDNormaVerbale, CarDNormaVerbaleExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	long countByExample(CarDNormaVerbaleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int deleteByExample(CarDNormaVerbaleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int deleteByPrimaryKey(Long idNormaVerbale);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int insert(CarDNormaVerbale record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int insertSelective(CarDNormaVerbale record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	List<CarDNormaVerbale> selectByExample(CarDNormaVerbaleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	CarDNormaVerbale selectByPrimaryKey(Long idNormaVerbale);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int updateByExampleSelective(@Param("record") CarDNormaVerbale record,
			@Param("example") CarDNormaVerbaleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int updateByExample(@Param("record") CarDNormaVerbale record, @Param("example") CarDNormaVerbaleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int updateByPrimaryKeySelective(CarDNormaVerbale record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	int updateByPrimaryKey(CarDNormaVerbale record);
}