package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDOrgNocivo;
import it.aizoon.ersaf.dto.generati.CarDOrgNocivoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDOrgNocivoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDOrgNocivo, CarDOrgNocivoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	long countByExample(CarDOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int deleteByExample(CarDOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int deleteByPrimaryKey(Long idOrgNocivo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int insert(CarDOrgNocivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int insertSelective(CarDOrgNocivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	List<CarDOrgNocivo> selectByExample(CarDOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	CarDOrgNocivo selectByPrimaryKey(Long idOrgNocivo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") CarDOrgNocivo record, @Param("example") CarDOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int updateByExample(@Param("record") CarDOrgNocivo record, @Param("example") CarDOrgNocivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int updateByPrimaryKeySelective(CarDOrgNocivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_org_nocivo
	 * @mbg.generated  Wed Aug 19 14:33:24 CEST 2020
	 */
	int updateByPrimaryKey(CarDOrgNocivo record);
}