package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoStampa;
import it.aizoon.ersaf.dto.generati.CarDTipoStampaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoStampaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoStampa, CarDTipoStampaExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    long countByExample(CarDTipoStampaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int deleteByExample(CarDTipoStampaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int deleteByPrimaryKey(Long idTipoStampa);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int insert(CarDTipoStampa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int insertSelective(CarDTipoStampa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    List<CarDTipoStampa> selectByExampleWithBLOBs(CarDTipoStampaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    List<CarDTipoStampa> selectByExample(CarDTipoStampaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    CarDTipoStampa selectByPrimaryKey(Long idTipoStampa);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarDTipoStampa record, @Param("example") CarDTipoStampaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") CarDTipoStampa record, @Param("example") CarDTipoStampaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int updateByExample(@Param("record") CarDTipoStampa record, @Param("example") CarDTipoStampaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int updateByPrimaryKeySelective(CarDTipoStampa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CarDTipoStampa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_tipo_stampa
     *
     * @mbg.generated Mon Sep 07 08:43:52 CEST 2020
     */
    int updateByPrimaryKey(CarDTipoStampa record);
}