package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoSpedizioniere;
import it.aizoon.ersaf.dto.generati.CarDTipoSpedizioniereExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoSpedizioniereMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoSpedizioniere, CarDTipoSpedizioniereExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDTipoSpedizioniereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDTipoSpedizioniereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idTipoSpedizioniere);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDTipoSpedizioniere record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDTipoSpedizioniere record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDTipoSpedizioniere> selectByExample(CarDTipoSpedizioniereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDTipoSpedizioniere selectByPrimaryKey(Long idTipoSpedizioniere);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDTipoSpedizioniere record,
      @Param("example") CarDTipoSpedizioniereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDTipoSpedizioniere record,
      @Param("example") CarDTipoSpedizioniereExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDTipoSpedizioniere record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_spedizioniere
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDTipoSpedizioniere record);
}