package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDVersioneControllo;
import it.aizoon.ersaf.dto.generati.CarDVersioneControlloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDVersioneControlloMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDVersioneControllo, CarDVersioneControlloExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    long countByExample(CarDVersioneControlloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    int deleteByExample(CarDVersioneControlloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    int deleteByPrimaryKey(Long idVersioneControllo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    int insert(CarDVersioneControllo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    int insertSelective(CarDVersioneControllo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    List<CarDVersioneControllo> selectByExample(CarDVersioneControlloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    CarDVersioneControllo selectByPrimaryKey(Long idVersioneControllo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    int updateByExampleSelective(@Param("record") CarDVersioneControllo record, @Param("example") CarDVersioneControlloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    int updateByExample(@Param("record") CarDVersioneControllo record, @Param("example") CarDVersioneControlloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    int updateByPrimaryKeySelective(CarDVersioneControllo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_versione_controllo
     *
     * @mbg.generated Mon Apr 12 09:32:57 CEST 2021
     */
    int updateByPrimaryKey(CarDVersioneControllo record);
}