package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoModulo;
import it.aizoon.ersaf.dto.generati.CarDTipoModuloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoModuloMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoModulo, CarDTipoModuloExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	long countByExample(CarDTipoModuloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int deleteByExample(CarDTipoModuloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int deleteByPrimaryKey(Long idTipoModulo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int insert(CarDTipoModulo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int insertSelective(CarDTipoModulo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	List<CarDTipoModulo> selectByExampleWithBLOBs(CarDTipoModuloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	List<CarDTipoModulo> selectByExample(CarDTipoModuloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	CarDTipoModulo selectByPrimaryKey(Long idTipoModulo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int updateByExampleSelective(@Param("record") CarDTipoModulo record,
			@Param("example") CarDTipoModuloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") CarDTipoModulo record,
			@Param("example") CarDTipoModuloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int updateByExample(@Param("record") CarDTipoModulo record, @Param("example") CarDTipoModuloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int updateByPrimaryKeySelective(CarDTipoModulo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int updateByPrimaryKeyWithBLOBs(CarDTipoModulo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_modulo
	 * @mbg.generated  Fri Dec 04 11:24:59 CET 2020
	 */
	int updateByPrimaryKey(CarDTipoModulo record);
}