package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDRequisitoProfessionale;
import it.aizoon.ersaf.dto.generati.CarDRequisitoProfessionaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDRequisitoProfessionaleMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDRequisitoProfessionale, CarDRequisitoProfessionaleExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    long countByExample(CarDRequisitoProfessionaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int deleteByExample(CarDRequisitoProfessionaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int deleteByPrimaryKey(Long idRequisitoProfessionale);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int insert(CarDRequisitoProfessionale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int insertSelective(CarDRequisitoProfessionale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    List<CarDRequisitoProfessionale> selectByExample(CarDRequisitoProfessionaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    CarDRequisitoProfessionale selectByPrimaryKey(Long idRequisitoProfessionale);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByExampleSelective(@Param("record") CarDRequisitoProfessionale record, @Param("example") CarDRequisitoProfessionaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByExample(@Param("record") CarDRequisitoProfessionale record, @Param("example") CarDRequisitoProfessionaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByPrimaryKeySelective(CarDRequisitoProfessionale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_d_requisito_professionale
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByPrimaryKey(CarDRequisitoProfessionale record);
}