package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoAllegato;
import it.aizoon.ersaf.dto.generati.CarDTipoAllegatoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoAllegatoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoAllegato, CarDTipoAllegatoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	long countByExample(CarDTipoAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	int deleteByExample(CarDTipoAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	int deleteByPrimaryKey(Long idTipoAllegato);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	int insert(CarDTipoAllegato record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	int insertSelective(CarDTipoAllegato record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	List<CarDTipoAllegato> selectByExample(CarDTipoAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	CarDTipoAllegato selectByPrimaryKey(Long idTipoAllegato);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") CarDTipoAllegato record,
			@Param("example") CarDTipoAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	int updateByExample(@Param("record") CarDTipoAllegato record, @Param("example") CarDTipoAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	int updateByPrimaryKeySelective(CarDTipoAllegato record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_allegato
	 * @mbg.generated  Thu Jul 30 08:41:41 CEST 2020
	 */
	int updateByPrimaryKey(CarDTipoAllegato record);
}