package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipologiaCampione;
import it.aizoon.ersaf.dto.generati.CarDTipologiaCampioneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipologiaCampioneMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipologiaCampione, CarDTipologiaCampioneExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	long countByExample(CarDTipologiaCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	int deleteByExample(CarDTipologiaCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	int deleteByPrimaryKey(Long idTipologiaCampione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	int insert(CarDTipologiaCampione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	int insertSelective(CarDTipologiaCampione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	List<CarDTipologiaCampione> selectByExample(CarDTipologiaCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	CarDTipologiaCampione selectByPrimaryKey(Long idTipologiaCampione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	int updateByExampleSelective(@Param("record") CarDTipologiaCampione record,
			@Param("example") CarDTipologiaCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	int updateByExample(@Param("record") CarDTipologiaCampione record,
			@Param("example") CarDTipologiaCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	int updateByPrimaryKeySelective(CarDTipologiaCampione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipologia_campione
	 * @mbg.generated  Tue Dec 29 12:15:01 CET 2020
	 */
	int updateByPrimaryKey(CarDTipologiaCampione record);
}