package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDTipoCertificato;
import it.aizoon.ersaf.dto.generati.CarDTipoCertificatoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDTipoCertificatoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDTipoCertificato, CarDTipoCertificatoExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDTipoCertificatoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDTipoCertificatoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idTipoCertificato);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDTipoCertificato record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDTipoCertificato record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDTipoCertificato> selectByExample(CarDTipoCertificatoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDTipoCertificato selectByPrimaryKey(Long idTipoCertificato);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDTipoCertificato record,
      @Param("example") CarDTipoCertificatoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDTipoCertificato record,
      @Param("example") CarDTipoCertificatoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDTipoCertificato record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tipo_certificato
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDTipoCertificato record);
}