package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarDComune;
import it.aizoon.ersaf.dto.generati.CarDComuneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarDComuneMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarDComune, CarDComuneExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  long countByExample(CarDComuneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByExample(CarDComuneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int deleteByPrimaryKey(Long idComune);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insert(CarDComune record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int insertSelective(CarDComune record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  List<CarDComune> selectByExample(CarDComuneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  CarDComune selectByPrimaryKey(Long idComune);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExampleSelective(@Param("record") CarDComune record, @Param("example") CarDComuneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByExample(@Param("record") CarDComune record, @Param("example") CarDComuneExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKeySelective(CarDComune record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_comune
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  int updateByPrimaryKey(CarDComune record);
}