package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRMisuraIspettore;
import it.aizoon.ersaf.dto.generati.CarRMisuraIspettoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRMisuraIspettoreMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRMisuraIspettore, CarRMisuraIspettoreExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_ispettore
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    long countByExample(CarRMisuraIspettoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_ispettore
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    int deleteByExample(CarRMisuraIspettoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_ispettore
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    int insert(CarRMisuraIspettore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_ispettore
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    int insertSelective(CarRMisuraIspettore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_ispettore
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    List<CarRMisuraIspettore> selectByExample(CarRMisuraIspettoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_ispettore
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    int updateByExampleSelective(@Param("record") CarRMisuraIspettore record, @Param("example") CarRMisuraIspettoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_ispettore
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    int updateByExample(@Param("record") CarRMisuraIspettore record, @Param("example") CarRMisuraIspettoreExample example);
}