package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRMerceTariffa;
import it.aizoon.ersaf.dto.generati.CarRMerceTariffaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRMerceTariffaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRMerceTariffa, CarRMerceTariffaExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  long countByExample(CarRMerceTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int deleteByExample(CarRMerceTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int deleteByPrimaryKey(@Param("idMerceRichiesta") Long idMerceRichiesta, @Param("idTariffa") Long idTariffa);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int insert(CarRMerceTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int insertSelective(CarRMerceTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  List<CarRMerceTariffa> selectByExample(CarRMerceTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  CarRMerceTariffa selectByPrimaryKey(@Param("idMerceRichiesta") Long idMerceRichiesta,
      @Param("idTariffa") Long idTariffa);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByExampleSelective(@Param("record") CarRMerceTariffa record,
      @Param("example") CarRMerceTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByExample(@Param("record") CarRMerceTariffa record, @Param("example") CarRMerceTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByPrimaryKeySelective(CarRMerceTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_merce_tariffa
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByPrimaryKey(CarRMerceTariffa record);
}