package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRCampioneOrgNoc;
import it.aizoon.ersaf.dto.generati.CarRCampioneOrgNocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRCampioneOrgNocMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRCampioneOrgNoc, CarRCampioneOrgNocExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_campione_org_noc
	 * @mbg.generated  Wed Dec 23 09:18:17 CET 2020
	 */
	long countByExample(CarRCampioneOrgNocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_campione_org_noc
	 * @mbg.generated  Wed Dec 23 09:18:17 CET 2020
	 */
	int deleteByExample(CarRCampioneOrgNocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_campione_org_noc
	 * @mbg.generated  Wed Dec 23 09:18:17 CET 2020
	 */
	int insert(CarRCampioneOrgNoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_campione_org_noc
	 * @mbg.generated  Wed Dec 23 09:18:17 CET 2020
	 */
	int insertSelective(CarRCampioneOrgNoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_campione_org_noc
	 * @mbg.generated  Wed Dec 23 09:18:17 CET 2020
	 */
	List<CarRCampioneOrgNoc> selectByExample(CarRCampioneOrgNocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_campione_org_noc
	 * @mbg.generated  Wed Dec 23 09:18:17 CET 2020
	 */
	int updateByExampleSelective(@Param("record") CarRCampioneOrgNoc record,
			@Param("example") CarRCampioneOrgNocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_campione_org_noc
	 * @mbg.generated  Wed Dec 23 09:18:17 CET 2020
	 */
	int updateByExample(@Param("record") CarRCampioneOrgNoc record,
			@Param("example") CarRCampioneOrgNocExample example);
}