package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRControlloTipoSemente;
import it.aizoon.ersaf.dto.generati.CarRControlloTipoSementeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRControlloTipoSementeMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRControlloTipoSemente, CarRControlloTipoSementeExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	long countByExample(CarRControlloTipoSementeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int deleteByExample(CarRControlloTipoSementeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int deleteByPrimaryKey(@Param("idControllo") Long idControllo,
			@Param("idTipologiaSemente") Long idTipologiaSemente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int insert(CarRControlloTipoSemente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int insertSelective(CarRControlloTipoSemente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	List<CarRControlloTipoSemente> selectByExample(CarRControlloTipoSementeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	CarRControlloTipoSemente selectByPrimaryKey(@Param("idControllo") Long idControllo,
			@Param("idTipologiaSemente") Long idTipologiaSemente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int updateByExampleSelective(@Param("record") CarRControlloTipoSemente record,
			@Param("example") CarRControlloTipoSementeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int updateByExample(@Param("record") CarRControlloTipoSemente record,
			@Param("example") CarRControlloTipoSementeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int updateByPrimaryKeySelective(CarRControlloTipoSemente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipo_semente
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int updateByPrimaryKey(CarRControlloTipoSemente record);
}