package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRControlloTipologia;
import it.aizoon.ersaf.dto.generati.CarRControlloTipologiaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRControlloTipologiaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRControlloTipologia, CarRControlloTipologiaExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	long countByExample(CarRControlloTipologiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	int deleteByExample(CarRControlloTipologiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	int deleteByPrimaryKey(@Param("idControllo") Long idControllo,
			@Param("idTipologiaControllo") Long idTipologiaControllo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	int insert(CarRControlloTipologia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	int insertSelective(CarRControlloTipologia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	List<CarRControlloTipologia> selectByExample(CarRControlloTipologiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	CarRControlloTipologia selectByPrimaryKey(@Param("idControllo") Long idControllo,
			@Param("idTipologiaControllo") Long idTipologiaControllo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	int updateByExampleSelective(@Param("record") CarRControlloTipologia record,
			@Param("example") CarRControlloTipologiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	int updateByExample(@Param("record") CarRControlloTipologia record,
			@Param("example") CarRControlloTipologiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	int updateByPrimaryKeySelective(CarRControlloTipologia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_tipologia
	 * @mbg.generated  Wed Mar 10 17:56:15 CET 2021
	 */
	int updateByPrimaryKey(CarRControlloTipologia record);
}