package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRControlloFisicoIrriga;
import it.aizoon.ersaf.dto.generati.CarRControlloFisicoIrrigaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRControlloFisicoIrrigaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRControlloFisicoIrriga, CarRControlloFisicoIrrigaExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    long countByExample(CarRControlloFisicoIrrigaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int deleteByExample(CarRControlloFisicoIrrigaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int deleteByPrimaryKey(@Param("idControlloFisico") Long idControlloFisico, @Param("idTipoIrrigazione") Long idTipoIrrigazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int insert(CarRControlloFisicoIrriga record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int insertSelective(CarRControlloFisicoIrriga record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    List<CarRControlloFisicoIrriga> selectByExample(CarRControlloFisicoIrrigaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    CarRControlloFisicoIrriga selectByPrimaryKey(@Param("idControlloFisico") Long idControlloFisico, @Param("idTipoIrrigazione") Long idTipoIrrigazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByExampleSelective(@Param("record") CarRControlloFisicoIrriga record, @Param("example") CarRControlloFisicoIrrigaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByExample(@Param("record") CarRControlloFisicoIrriga record, @Param("example") CarRControlloFisicoIrrigaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByPrimaryKeySelective(CarRControlloFisicoIrriga record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_irriga
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByPrimaryKey(CarRControlloFisicoIrriga record);
}