package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRControlloFisicoOrgNoc;
import it.aizoon.ersaf.dto.generati.CarRControlloFisicoOrgNocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRControlloFisicoOrgNocMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRControlloFisicoOrgNoc, CarRControlloFisicoOrgNocExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_org_noc
     *
     * @mbg.generated Mon Apr 12 16:58:28 CEST 2021
     */
    long countByExample(CarRControlloFisicoOrgNocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_org_noc
     *
     * @mbg.generated Mon Apr 12 16:58:28 CEST 2021
     */
    int deleteByExample(CarRControlloFisicoOrgNocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_org_noc
     *
     * @mbg.generated Mon Apr 12 16:58:28 CEST 2021
     */
    int insert(CarRControlloFisicoOrgNoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_org_noc
     *
     * @mbg.generated Mon Apr 12 16:58:28 CEST 2021
     */
    int insertSelective(CarRControlloFisicoOrgNoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_org_noc
     *
     * @mbg.generated Mon Apr 12 16:58:28 CEST 2021
     */
    List<CarRControlloFisicoOrgNoc> selectByExample(CarRControlloFisicoOrgNocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_org_noc
     *
     * @mbg.generated Mon Apr 12 16:58:28 CEST 2021
     */
    int updateByExampleSelective(@Param("record") CarRControlloFisicoOrgNoc record, @Param("example") CarRControlloFisicoOrgNocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_org_noc
     *
     * @mbg.generated Mon Apr 12 16:58:28 CEST 2021
     */
    int updateByExample(@Param("record") CarRControlloFisicoOrgNoc record, @Param("example") CarRControlloFisicoOrgNocExample example);
}