package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRRichiestaTariffa;
import it.aizoon.ersaf.dto.generati.CarRRichiestaTariffaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRRichiestaTariffaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRRichiestaTariffa, CarRRichiestaTariffaExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  long countByExample(CarRRichiestaTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int deleteByExample(CarRRichiestaTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int deleteByPrimaryKey(@Param("idRichiesta") Long idRichiesta, @Param("idTariffa") Long idTariffa);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int insert(CarRRichiestaTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int insertSelective(CarRRichiestaTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  List<CarRRichiestaTariffa> selectByExample(CarRRichiestaTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  CarRRichiestaTariffa selectByPrimaryKey(@Param("idRichiesta") Long idRichiesta, @Param("idTariffa") Long idTariffa);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByExampleSelective(@Param("record") CarRRichiestaTariffa record,
      @Param("example") CarRRichiestaTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByExample(@Param("record") CarRRichiestaTariffa record,
      @Param("example") CarRRichiestaTariffaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByPrimaryKeySelective(CarRRichiestaTariffa record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_richiesta_tariffa
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByPrimaryKey(CarRRichiestaTariffa record);
}