package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRTipoDomAllegato;
import it.aizoon.ersaf.dto.generati.CarRTipoDomAllegatoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRTipoDomAllegatoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRTipoDomAllegato, CarRTipoDomAllegatoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_tipo_dom_allegato
	 * @mbg.generated  Fri Sep 25 14:44:55 CEST 2020
	 */
	long countByExample(CarRTipoDomAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_tipo_dom_allegato
	 * @mbg.generated  Fri Sep 25 14:44:55 CEST 2020
	 */
	int deleteByExample(CarRTipoDomAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_tipo_dom_allegato
	 * @mbg.generated  Fri Sep 25 14:44:55 CEST 2020
	 */
	int insert(CarRTipoDomAllegato record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_tipo_dom_allegato
	 * @mbg.generated  Fri Sep 25 14:44:55 CEST 2020
	 */
	int insertSelective(CarRTipoDomAllegato record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_tipo_dom_allegato
	 * @mbg.generated  Fri Sep 25 14:44:55 CEST 2020
	 */
	List<CarRTipoDomAllegato> selectByExample(CarRTipoDomAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_tipo_dom_allegato
	 * @mbg.generated  Fri Sep 25 14:44:55 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") CarRTipoDomAllegato record,
			@Param("example") CarRTipoDomAllegatoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_tipo_dom_allegato
	 * @mbg.generated  Fri Sep 25 14:44:55 CEST 2020
	 */
	int updateByExample(@Param("record") CarRTipoDomAllegato record,
			@Param("example") CarRTipoDomAllegatoExample example);
}