package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRControlloFisicoConProf;
import it.aizoon.ersaf.dto.generati.CarRControlloFisicoConProfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRControlloFisicoConProfMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRControlloFisicoConProf, CarRControlloFisicoConProfExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    long countByExample(CarRControlloFisicoConProfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int deleteByExample(CarRControlloFisicoConProfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int deleteByPrimaryKey(@Param("idControlloFisico") Long idControlloFisico, @Param("idConoscenzaProfessionale") Long idConoscenzaProfessionale);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int insert(CarRControlloFisicoConProf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int insertSelective(CarRControlloFisicoConProf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    List<CarRControlloFisicoConProf> selectByExample(CarRControlloFisicoConProfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    CarRControlloFisicoConProf selectByPrimaryKey(@Param("idControlloFisico") Long idControlloFisico, @Param("idConoscenzaProfessionale") Long idConoscenzaProfessionale);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByExampleSelective(@Param("record") CarRControlloFisicoConProf record, @Param("example") CarRControlloFisicoConProfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByExample(@Param("record") CarRControlloFisicoConProf record, @Param("example") CarRControlloFisicoConProfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByPrimaryKeySelective(CarRControlloFisicoConProf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_fisico_con_prof
     *
     * @mbg.generated Wed Dec 23 08:31:16 CET 2020
     */
    int updateByPrimaryKey(CarRControlloFisicoConProf record);
}