package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRGruppoStatoComSucc;
import it.aizoon.ersaf.dto.generati.CarRGruppoStatoComSuccExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRGruppoStatoComSuccMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRGruppoStatoComSucc, CarRGruppoStatoComSuccExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com_succ
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    long countByExample(CarRGruppoStatoComSuccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com_succ
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int deleteByExample(CarRGruppoStatoComSuccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com_succ
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int deleteByPrimaryKey(@Param("idGruppo") Long idGruppo, @Param("idStatoComunicazione") Long idStatoComunicazione, @Param("idStatoComSucc") Long idStatoComSucc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com_succ
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int insert(CarRGruppoStatoComSucc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com_succ
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int insertSelective(CarRGruppoStatoComSucc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com_succ
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    List<CarRGruppoStatoComSucc> selectByExample(CarRGruppoStatoComSuccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com_succ
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int updateByExampleSelective(@Param("record") CarRGruppoStatoComSucc record, @Param("example") CarRGruppoStatoComSuccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com_succ
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int updateByExample(@Param("record") CarRGruppoStatoComSucc record, @Param("example") CarRGruppoStatoComSuccExample example);
}