package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRControlloIdentitaSito;
import it.aizoon.ersaf.dto.generati.CarRControlloIdentitaSitoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRControlloIdentitaSitoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRControlloIdentitaSito, CarRControlloIdentitaSitoExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    long countByExample(CarRControlloIdentitaSitoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    int deleteByExample(CarRControlloIdentitaSitoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    int deleteByPrimaryKey(@Param("idControlloIdentita") Long idControlloIdentita, @Param("idSitoProduzione") Long idSitoProduzione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    int insert(CarRControlloIdentitaSito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    int insertSelective(CarRControlloIdentitaSito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    List<CarRControlloIdentitaSito> selectByExample(CarRControlloIdentitaSitoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    CarRControlloIdentitaSito selectByPrimaryKey(@Param("idControlloIdentita") Long idControlloIdentita, @Param("idSitoProduzione") Long idSitoProduzione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    int updateByExampleSelective(@Param("record") CarRControlloIdentitaSito record, @Param("example") CarRControlloIdentitaSitoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    int updateByExample(@Param("record") CarRControlloIdentitaSito record, @Param("example") CarRControlloIdentitaSitoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    int updateByPrimaryKeySelective(CarRControlloIdentitaSito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_controllo_identita_sito
     *
     * @mbg.generated Wed Dec 23 18:05:14 CET 2020
     */
    int updateByPrimaryKey(CarRControlloIdentitaSito record);
}