package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRControlloIspettore;
import it.aizoon.ersaf.dto.generati.CarRControlloIspettoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRControlloIspettoreMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRControlloIspettore, CarRControlloIspettoreExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	long countByExample(CarRControlloIspettoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int deleteByExample(CarRControlloIspettoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int deleteByPrimaryKey(@Param("idControllo") Long idControllo, @Param("idIspettore") Long idIspettore);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int insert(CarRControlloIspettore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int insertSelective(CarRControlloIspettore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	List<CarRControlloIspettore> selectByExample(CarRControlloIspettoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	CarRControlloIspettore selectByPrimaryKey(@Param("idControllo") Long idControllo,
			@Param("idIspettore") Long idIspettore);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int updateByExampleSelective(@Param("record") CarRControlloIspettore record,
			@Param("example") CarRControlloIspettoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int updateByExample(@Param("record") CarRControlloIspettore record,
			@Param("example") CarRControlloIspettoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int updateByPrimaryKeySelective(CarRControlloIspettore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_controllo_ispettore
	 * @mbg.generated  Tue Dec 22 10:13:41 CET 2020
	 */
	int updateByPrimaryKey(CarRControlloIspettore record);
}