package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRDomandaTipologia;
import it.aizoon.ersaf.dto.generati.CarRDomandaTipologiaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRDomandaTipologiaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRDomandaTipologia, CarRDomandaTipologiaExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    long countByExample(CarRDomandaTipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int deleteByExample(CarRDomandaTipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int deleteByPrimaryKey(@Param("idDomanda") Long idDomanda, @Param("idTipologia") Long idTipologia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int insert(CarRDomandaTipologia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int insertSelective(CarRDomandaTipologia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    List<CarRDomandaTipologia> selectByExample(CarRDomandaTipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    CarRDomandaTipologia selectByPrimaryKey(@Param("idDomanda") Long idDomanda, @Param("idTipologia") Long idTipologia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarRDomandaTipologia record, @Param("example") CarRDomandaTipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int updateByExample(@Param("record") CarRDomandaTipologia record, @Param("example") CarRDomandaTipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int updateByPrimaryKeySelective(CarRDomandaTipologia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_domanda_tipologia
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int updateByPrimaryKey(CarRDomandaTipologia record);
}