package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRTipoComSezione;
import it.aizoon.ersaf.dto.generati.CarRTipoComSezioneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRTipoComSezioneMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRTipoComSezione, CarRTipoComSezioneExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    long countByExample(CarRTipoComSezioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    int deleteByExample(CarRTipoComSezioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    int deleteByPrimaryKey(@Param("idTipoComunicazione") Long idTipoComunicazione, @Param("idAssociazioneSezione") Long idAssociazioneSezione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    int insert(CarRTipoComSezione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    int insertSelective(CarRTipoComSezione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    List<CarRTipoComSezione> selectByExample(CarRTipoComSezioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    CarRTipoComSezione selectByPrimaryKey(@Param("idTipoComunicazione") Long idTipoComunicazione, @Param("idAssociazioneSezione") Long idAssociazioneSezione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarRTipoComSezione record, @Param("example") CarRTipoComSezioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    int updateByExample(@Param("record") CarRTipoComSezione record, @Param("example") CarRTipoComSezioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    int updateByPrimaryKeySelective(CarRTipoComSezione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_com_sezione
     *
     * @mbg.generated Fri May 08 17:20:59 CEST 2020
     */
    int updateByPrimaryKey(CarRTipoComSezione record);
}