package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRTipoFlussoCom;
import it.aizoon.ersaf.dto.generati.CarRTipoFlussoComExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRTipoFlussoComMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRTipoFlussoCom, CarRTipoFlussoComExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    long countByExample(CarRTipoFlussoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int deleteByExample(CarRTipoFlussoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int deleteByPrimaryKey(@Param("idTipoFlusso") Long idTipoFlusso, @Param("idTipoComunicazione") Long idTipoComunicazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int insert(CarRTipoFlussoCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int insertSelective(CarRTipoFlussoCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    List<CarRTipoFlussoCom> selectByExample(CarRTipoFlussoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    CarRTipoFlussoCom selectByPrimaryKey(@Param("idTipoFlusso") Long idTipoFlusso, @Param("idTipoComunicazione") Long idTipoComunicazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarRTipoFlussoCom record, @Param("example") CarRTipoFlussoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByExample(@Param("record") CarRTipoFlussoCom record, @Param("example") CarRTipoFlussoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByPrimaryKeySelective(CarRTipoFlussoCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipo_flusso_com
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByPrimaryKey(CarRTipoFlussoCom record);
}