package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRTrattamentoRichiesta;
import it.aizoon.ersaf.dto.generati.CarRTrattamentoRichiestaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRTrattamentoRichiestaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRTrattamentoRichiesta, CarRTrattamentoRichiestaExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  long countByExample(CarRTrattamentoRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int deleteByExample(CarRTrattamentoRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int deleteByPrimaryKey(Long idTrattamentoRichiesta);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int insert(CarRTrattamentoRichiesta record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int insertSelective(CarRTrattamentoRichiesta record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  List<CarRTrattamentoRichiesta> selectByExample(CarRTrattamentoRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  CarRTrattamentoRichiesta selectByPrimaryKey(Long idTrattamentoRichiesta);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByExampleSelective(@Param("record") CarRTrattamentoRichiesta record,
      @Param("example") CarRTrattamentoRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByExample(@Param("record") CarRTrattamentoRichiesta record,
      @Param("example") CarRTrattamentoRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByPrimaryKeySelective(CarRTrattamentoRichiesta record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_trattamento_richiesta
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByPrimaryKey(CarRTrattamentoRichiesta record);
}