package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRLinguaGenere;
import it.aizoon.ersaf.dto.generati.CarRLinguaGenereExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRLinguaGenereMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRLinguaGenere, CarRLinguaGenereExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	long countByExample(CarRLinguaGenereExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	int deleteByExample(CarRLinguaGenereExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	int deleteByPrimaryKey(@Param("idGenere") Long idGenere, @Param("idLingua") Long idLingua);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	int insert(CarRLinguaGenere record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	int insertSelective(CarRLinguaGenere record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	List<CarRLinguaGenere> selectByExample(CarRLinguaGenereExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	CarRLinguaGenere selectByPrimaryKey(@Param("idGenere") Long idGenere, @Param("idLingua") Long idLingua);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") CarRLinguaGenere record,
			@Param("example") CarRLinguaGenereExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	int updateByExample(@Param("record") CarRLinguaGenere record, @Param("example") CarRLinguaGenereExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	int updateByPrimaryKeySelective(CarRLinguaGenere record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_lingua_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	int updateByPrimaryKey(CarRLinguaGenere record);
}