package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRTipologiaVoce;
import it.aizoon.ersaf.dto.generati.CarRTipologiaVoceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRTipologiaVoceMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRTipologiaVoce, CarRTipologiaVoceExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    long countByExample(CarRTipologiaVoceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int deleteByExample(CarRTipologiaVoceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int deleteByPrimaryKey(Long idTipolgiaVoce);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int insert(CarRTipologiaVoce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int insertSelective(CarRTipologiaVoce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    List<CarRTipologiaVoce> selectByExample(CarRTipologiaVoceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    CarRTipologiaVoce selectByPrimaryKey(Long idTipolgiaVoce);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarRTipologiaVoce record, @Param("example") CarRTipologiaVoceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int updateByExample(@Param("record") CarRTipologiaVoce record, @Param("example") CarRTipologiaVoceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int updateByPrimaryKeySelective(CarRTipologiaVoce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_tipologia_voce
     *
     * @mbg.generated Thu Jul 09 13:34:39 CEST 2020
     */
    int updateByPrimaryKey(CarRTipologiaVoce record);
}