package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRGruppoStatoCom;
import it.aizoon.ersaf.dto.generati.CarRGruppoStatoComExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRGruppoStatoComMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRGruppoStatoCom, CarRGruppoStatoComExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    long countByExample(CarRGruppoStatoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int deleteByExample(CarRGruppoStatoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int deleteByPrimaryKey(@Param("idGruppo") Long idGruppo, @Param("idStatoComunicazione") Long idStatoComunicazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int insert(CarRGruppoStatoCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int insertSelective(CarRGruppoStatoCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    List<CarRGruppoStatoCom> selectByExample(CarRGruppoStatoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    CarRGruppoStatoCom selectByPrimaryKey(@Param("idGruppo") Long idGruppo, @Param("idStatoComunicazione") Long idStatoComunicazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int updateByExampleSelective(@Param("record") CarRGruppoStatoCom record, @Param("example") CarRGruppoStatoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int updateByExample(@Param("record") CarRGruppoStatoCom record, @Param("example") CarRGruppoStatoComExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int updateByPrimaryKeySelective(CarRGruppoStatoCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_gruppo_stato_com
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    int updateByPrimaryKey(CarRGruppoStatoCom record);
}