package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarRUtenteGruppo;
import it.aizoon.ersaf.dto.generati.CarRUtenteGruppoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarRUtenteGruppoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarRUtenteGruppo, CarRUtenteGruppoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_utente_gruppo
	 * @mbg.generated  Fri Dec 23 15:23:51 CET 2022
	 */
	long countByExample(CarRUtenteGruppoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_utente_gruppo
	 * @mbg.generated  Fri Dec 23 15:23:51 CET 2022
	 */
	int deleteByExample(CarRUtenteGruppoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_utente_gruppo
	 * @mbg.generated  Fri Dec 23 15:23:51 CET 2022
	 */
	int deleteByPrimaryKey(@Param("idUtente") Long idUtente, @Param("idGruppo") Long idGruppo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_utente_gruppo
	 * @mbg.generated  Fri Dec 23 15:23:51 CET 2022
	 */
	int insert(CarRUtenteGruppo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_utente_gruppo
	 * @mbg.generated  Fri Dec 23 15:23:51 CET 2022
	 */
	int insertSelective(CarRUtenteGruppo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_utente_gruppo
	 * @mbg.generated  Fri Dec 23 15:23:51 CET 2022
	 */
	List<CarRUtenteGruppo> selectByExample(CarRUtenteGruppoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_utente_gruppo
	 * @mbg.generated  Fri Dec 23 15:23:51 CET 2022
	 */
	int updateByExampleSelective(@Param("record") CarRUtenteGruppo record,
			@Param("example") CarRUtenteGruppoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_utente_gruppo
	 * @mbg.generated  Fri Dec 23 15:23:51 CET 2022
	 */
	int updateByExample(@Param("record") CarRUtenteGruppo record, @Param("example") CarRUtenteGruppoExample example);
}