package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTZonaProtettaUtente;
import it.aizoon.ersaf.dto.generati.CarTZonaProtettaUtenteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTZonaProtettaUtenteMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTZonaProtettaUtente, CarTZonaProtettaUtenteExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	long countByExample(CarTZonaProtettaUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	int deleteByExample(CarTZonaProtettaUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	int deleteByPrimaryKey(Long idZonaProtettaUtente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	int insert(CarTZonaProtettaUtente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	int insertSelective(CarTZonaProtettaUtente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	List<CarTZonaProtettaUtente> selectByExample(CarTZonaProtettaUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	CarTZonaProtettaUtente selectByPrimaryKey(Long idZonaProtettaUtente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") CarTZonaProtettaUtente record,
			@Param("example") CarTZonaProtettaUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	int updateByExample(@Param("record") CarTZonaProtettaUtente record,
			@Param("example") CarTZonaProtettaUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	int updateByPrimaryKeySelective(CarTZonaProtettaUtente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_zona_protetta_utente
	 * @mbg.generated  Thu Aug 20 11:49:39 CEST 2020
	 */
	int updateByPrimaryKey(CarTZonaProtettaUtente record);
}