package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTControlloFisico;
import it.aizoon.ersaf.dto.generati.CarTControlloFisicoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTControlloFisicoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTControlloFisico, CarTControlloFisicoExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    long countByExample(CarTControlloFisicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    int deleteByExample(CarTControlloFisicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    int deleteByPrimaryKey(Long idControlloFisico);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    int insert(CarTControlloFisico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    int insertSelective(CarTControlloFisico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    List<CarTControlloFisico> selectByExample(CarTControlloFisicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    CarTControlloFisico selectByPrimaryKey(Long idControlloFisico);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    int updateByExampleSelective(@Param("record") CarTControlloFisico record, @Param("example") CarTControlloFisicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    int updateByExample(@Param("record") CarTControlloFisico record, @Param("example") CarTControlloFisicoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    int updateByPrimaryKeySelective(CarTControlloFisico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    int updateByPrimaryKey(CarTControlloFisico record);
}