package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTIterTariffaSped;
import it.aizoon.ersaf.dto.generati.CarTIterTariffaSpedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTIterTariffaSpedMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTIterTariffaSped, CarTIterTariffaSpedExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    long countByExample(CarTIterTariffaSpedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int deleteByExample(CarTIterTariffaSpedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int deleteByPrimaryKey(Long idIterTariffaSped);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int insert(CarTIterTariffaSped record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int insertSelective(CarTIterTariffaSped record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    List<CarTIterTariffaSped> selectByExample(CarTIterTariffaSpedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    CarTIterTariffaSped selectByPrimaryKey(Long idIterTariffaSped);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int updateByExampleSelective(@Param("record") CarTIterTariffaSped record, @Param("example") CarTIterTariffaSpedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int updateByExample(@Param("record") CarTIterTariffaSped record, @Param("example") CarTIterTariffaSpedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int updateByPrimaryKeySelective(CarTIterTariffaSped record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tariffa_sped
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int updateByPrimaryKey(CarTIterTariffaSped record);
}