package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTEsito;
import it.aizoon.ersaf.dto.generati.CarTEsitoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTEsitoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTEsito, CarTEsitoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	long countByExample(CarTEsitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int deleteByExample(CarTEsitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int deleteByPrimaryKey(Long idEsito);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int insert(CarTEsito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int insertSelective(CarTEsito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	List<CarTEsito> selectByExampleWithBLOBs(CarTEsitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	List<CarTEsito> selectByExample(CarTEsitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	CarTEsito selectByPrimaryKey(Long idEsito);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int updateByExampleSelective(@Param("record") CarTEsito record, @Param("example") CarTEsitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int updateByExampleWithBLOBs(@Param("record") CarTEsito record, @Param("example") CarTEsitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int updateByExample(@Param("record") CarTEsito record, @Param("example") CarTEsitoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int updateByPrimaryKeySelective(CarTEsito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int updateByPrimaryKeyWithBLOBs(CarTEsito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	int updateByPrimaryKey(CarTEsito record);
}