package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTRichiesta;
import it.aizoon.ersaf.dto.generati.CarTRichiestaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTRichiestaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTRichiesta, CarTRichiestaExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  long countByExample(CarTRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int deleteByExample(CarTRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int deleteByPrimaryKey(Long idRichiesta);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int insert(CarTRichiesta record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int insertSelective(CarTRichiesta record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  List<CarTRichiesta> selectByExample(CarTRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  CarTRichiesta selectByPrimaryKey(Long idRichiesta);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByExampleSelective(@Param("record") CarTRichiesta record, @Param("example") CarTRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByExample(@Param("record") CarTRichiesta record, @Param("example") CarTRichiestaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByPrimaryKeySelective(CarTRichiesta record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_richiesta
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByPrimaryKey(CarTRichiesta record);
}