package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTResponsabilePassaporto;
import it.aizoon.ersaf.dto.generati.CarTResponsabilePassaportoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTResponsabilePassaportoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTResponsabilePassaporto, CarTResponsabilePassaportoExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    long countByExample(CarTResponsabilePassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int deleteByExample(CarTResponsabilePassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int deleteByPrimaryKey(Long idResponsabilePassaporto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int insert(CarTResponsabilePassaporto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int insertSelective(CarTResponsabilePassaporto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    List<CarTResponsabilePassaporto> selectByExample(CarTResponsabilePassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    CarTResponsabilePassaporto selectByPrimaryKey(Long idResponsabilePassaporto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarTResponsabilePassaporto record, @Param("example") CarTResponsabilePassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int updateByExample(@Param("record") CarTResponsabilePassaporto record, @Param("example") CarTResponsabilePassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int updateByPrimaryKeySelective(CarTResponsabilePassaporto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_responsabile_passaporto
     *
     * @mbg.generated Wed Jun 17 10:40:54 CEST 2020
     */
    int updateByPrimaryKey(CarTResponsabilePassaporto record);
}