package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTUtente;
import it.aizoon.ersaf.dto.generati.CarTUtenteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTUtenteMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTUtente, CarTUtenteExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	long countByExample(CarTUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	int deleteByExample(CarTUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	int deleteByPrimaryKey(Long idUtente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	int insert(CarTUtente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	int insertSelective(CarTUtente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	List<CarTUtente> selectByExample(CarTUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	CarTUtente selectByPrimaryKey(Long idUtente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	int updateByExampleSelective(@Param("record") CarTUtente record, @Param("example") CarTUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	int updateByExample(@Param("record") CarTUtente record, @Param("example") CarTUtenteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	int updateByPrimaryKeySelective(CarTUtente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_utente
	 * @mbg.generated  Wed Aug 04 14:10:57 CEST 2021
	 */
	int updateByPrimaryKey(CarTUtente record);
}