package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTPagamento;
import it.aizoon.ersaf.dto.generati.CarTPagamentoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTPagamentoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTPagamento, CarTPagamentoExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  long countByExample(CarTPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int deleteByExample(CarTPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int deleteByPrimaryKey(Long idPagamento);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int insert(CarTPagamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int insertSelective(CarTPagamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  List<CarTPagamento> selectByExampleWithBLOBs(CarTPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  List<CarTPagamento> selectByExample(CarTPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  CarTPagamento selectByPrimaryKey(Long idPagamento);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByExampleSelective(@Param("record") CarTPagamento record, @Param("example") CarTPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByExampleWithBLOBs(@Param("record") CarTPagamento record, @Param("example") CarTPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByExample(@Param("record") CarTPagamento record, @Param("example") CarTPagamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByPrimaryKeySelective(CarTPagamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByPrimaryKeyWithBLOBs(CarTPagamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  int updateByPrimaryKey(CarTPagamento record);
}