package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTNotifica;
import it.aizoon.ersaf.dto.generati.CarTNotificaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTNotificaMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTNotifica, CarTNotificaExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  long countByExample(CarTNotificaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int deleteByExample(CarTNotificaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int deleteByPrimaryKey(Long idNotifica);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int insert(CarTNotifica record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int insertSelective(CarTNotifica record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  List<CarTNotifica> selectByExample(CarTNotificaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  CarTNotifica selectByPrimaryKey(Long idNotifica);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByExampleSelective(@Param("record") CarTNotifica record, @Param("example") CarTNotificaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByExample(@Param("record") CarTNotifica record, @Param("example") CarTNotificaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByPrimaryKeySelective(CarTNotifica record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_notifica
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  int updateByPrimaryKey(CarTNotifica record);
}