package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTCampione;
import it.aizoon.ersaf.dto.generati.CarTCampioneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTCampioneMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTCampione, CarTCampioneExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	long countByExample(CarTCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	int deleteByExample(CarTCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	int deleteByPrimaryKey(Long idCampione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	int insert(CarTCampione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	int insertSelective(CarTCampione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	List<CarTCampione> selectByExample(CarTCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	CarTCampione selectByPrimaryKey(Long idCampione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	int updateByExampleSelective(@Param("record") CarTCampione record, @Param("example") CarTCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	int updateByExample(@Param("record") CarTCampione record, @Param("example") CarTCampioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	int updateByPrimaryKeySelective(CarTCampione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_campione
	 * @mbg.generated  Tue May 04 12:43:17 CEST 2021
	 */
	int updateByPrimaryKey(CarTCampione record);
}