package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTIterTipoPassaporto;
import it.aizoon.ersaf.dto.generati.CarTIterTipoPassaportoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTIterTipoPassaportoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTIterTipoPassaporto, CarTIterTipoPassaportoExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    long countByExample(CarTIterTipoPassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int deleteByExample(CarTIterTipoPassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int deleteByPrimaryKey(Long idIterTipoPassaporto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int insert(CarTIterTipoPassaporto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int insertSelective(CarTIterTipoPassaporto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    List<CarTIterTipoPassaporto> selectByExample(CarTIterTipoPassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    CarTIterTipoPassaporto selectByPrimaryKey(Long idIterTipoPassaporto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int updateByExampleSelective(@Param("record") CarTIterTipoPassaporto record, @Param("example") CarTIterTipoPassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int updateByExample(@Param("record") CarTIterTipoPassaporto record, @Param("example") CarTIterTipoPassaportoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int updateByPrimaryKeySelective(CarTIterTipoPassaporto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_iter_tipo_passaporto
     *
<<<<<<< HEAD
     * @mbg.generated Thu May 04 10:03:44 CEST 2023
=======
     * @mbg.generated Wed May 03 17:48:23 CEST 2023
>>>>>>> 338f5556e526f4af2a8601b1763ed97bf455325e
     */
    int updateByPrimaryKey(CarTIterTipoPassaporto record);
}