package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTFlusso;
import it.aizoon.ersaf.dto.generati.CarTFlussoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTFlussoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTFlusso, CarTFlussoExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    long countByExample(CarTFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int deleteByExample(CarTFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int deleteByPrimaryKey(Long idFlusso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int insert(CarTFlusso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int insertSelective(CarTFlusso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    List<CarTFlusso> selectByExample(CarTFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    CarTFlusso selectByPrimaryKey(Long idFlusso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByExampleSelective(@Param("record") CarTFlusso record, @Param("example") CarTFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByExample(@Param("record") CarTFlusso record, @Param("example") CarTFlussoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByPrimaryKeySelective(CarTFlusso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    int updateByPrimaryKey(CarTFlusso record);
}