package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.CarTTraceLogin;
import it.aizoon.ersaf.dto.generati.CarTTraceLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarTTraceLoginMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<CarTTraceLogin, CarTTraceLoginExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    long countByExample(CarTTraceLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    int deleteByExample(CarTTraceLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    int deleteByPrimaryKey(Long idTraceLogin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    int insert(CarTTraceLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    int insertSelective(CarTTraceLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    List<CarTTraceLogin> selectByExample(CarTTraceLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    CarTTraceLogin selectByPrimaryKey(Long idTraceLogin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    int updateByExampleSelective(@Param("record") CarTTraceLogin record, @Param("example") CarTTraceLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    int updateByExample(@Param("record") CarTTraceLogin record, @Param("example") CarTTraceLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    int updateByPrimaryKeySelective(CarTTraceLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_t_trace_login
     *
     * @mbg.generated Fri Apr 27 16:41:05 CEST 2018
     */
    int updateByPrimaryKey(CarTTraceLogin record);
}