package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.TestTokenLogin;
import it.aizoon.ersaf.dto.generati.TestTokenLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TestTokenLoginMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<TestTokenLogin, TestTokenLoginExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_token_login
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    long countByExample(TestTokenLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_token_login
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int deleteByExample(TestTokenLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_token_login
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int insert(TestTokenLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_token_login
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int insertSelective(TestTokenLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_token_login
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    List<TestTokenLogin> selectByExample(TestTokenLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_token_login
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByExampleSelective(@Param("record") TestTokenLogin record, @Param("example") TestTokenLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_token_login
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByExample(@Param("record") TestTokenLogin record, @Param("example") TestTokenLoginExample example);
}