package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.TestRGruppoAutorizzazione;
import it.aizoon.ersaf.dto.generati.TestRGruppoAutorizzazioneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TestRGruppoAutorizzazioneMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<TestRGruppoAutorizzazione, TestRGruppoAutorizzazioneExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_gruppo_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    long countByExample(TestRGruppoAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_gruppo_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int deleteByExample(TestRGruppoAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_gruppo_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int insert(TestRGruppoAutorizzazione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_gruppo_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int insertSelective(TestRGruppoAutorizzazione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_gruppo_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    List<TestRGruppoAutorizzazione> selectByExample(TestRGruppoAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_gruppo_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByExampleSelective(@Param("record") TestRGruppoAutorizzazione record, @Param("example") TestRGruppoAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_gruppo_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByExample(@Param("record") TestRGruppoAutorizzazione record, @Param("example") TestRGruppoAutorizzazioneExample example);
}