package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.TestRUtenteGruppo;
import it.aizoon.ersaf.dto.generati.TestRUtenteGruppoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TestRUtenteGruppoMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<TestRUtenteGruppo, TestRUtenteGruppoExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_utente_gruppo
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    long countByExample(TestRUtenteGruppoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_utente_gruppo
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int deleteByExample(TestRUtenteGruppoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_utente_gruppo
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int insert(TestRUtenteGruppo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_utente_gruppo
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int insertSelective(TestRUtenteGruppo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_utente_gruppo
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    List<TestRUtenteGruppo> selectByExample(TestRUtenteGruppoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_utente_gruppo
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByExampleSelective(@Param("record") TestRUtenteGruppo record, @Param("example") TestRUtenteGruppoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_r_utente_gruppo
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByExample(@Param("record") TestRUtenteGruppo record, @Param("example") TestRUtenteGruppoExample example);
}