package it.aizoon.ersaf.integration.mybatis.mapper.generati;

import it.aizoon.ersaf.dto.generati.TestAutorizzazione;
import it.aizoon.ersaf.dto.generati.TestAutorizzazioneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TestAutorizzazioneMapper extends it.aizoon.ersaf.integration.mybatis.mapper.IBaseDao<TestAutorizzazione, TestAutorizzazioneExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    long countByExample(TestAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int deleteByExample(TestAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int insert(TestAutorizzazione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int insertSelective(TestAutorizzazione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    List<TestAutorizzazione> selectByExample(TestAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    TestAutorizzazione selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByExampleSelective(@Param("record") TestAutorizzazione record, @Param("example") TestAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByExample(@Param("record") TestAutorizzazione record, @Param("example") TestAutorizzazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByPrimaryKeySelective(TestAutorizzazione record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.test_autorizzazione
     *
     * @mbg.generated Fri Nov 17 17:20:50 CET 2017
     */
    int updateByPrimaryKey(TestAutorizzazione record);
}