package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;
import java.util.Date;

public class CarDMateriale extends BaseDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_d_materiale.id_materiale
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    private Long idMateriale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_d_materiale.desc_breve
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    private String descBreve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_d_materiale.desc_estesa
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    private String descEstesa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_d_materiale.istruzioni
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    private String istruzioni;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_d_materiale.inizio_validita
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    private Date inizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_d_materiale.fine_validita
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    private Date fineValidita;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_d_materiale.id_materiale
     *
     * @return the value of caronte.car_d_materiale.id_materiale
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public Long getIdMateriale() {
        return idMateriale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_d_materiale.id_materiale
     *
     * @param idMateriale the value for caronte.car_d_materiale.id_materiale
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public void setIdMateriale(Long idMateriale) {
        this.idMateriale = idMateriale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_d_materiale.desc_breve
     *
     * @return the value of caronte.car_d_materiale.desc_breve
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public String getDescBreve() {
        return descBreve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_d_materiale.desc_breve
     *
     * @param descBreve the value for caronte.car_d_materiale.desc_breve
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve == null ? null : descBreve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_d_materiale.desc_estesa
     *
     * @return the value of caronte.car_d_materiale.desc_estesa
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public String getDescEstesa() {
        return descEstesa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_d_materiale.desc_estesa
     *
     * @param descEstesa the value for caronte.car_d_materiale.desc_estesa
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public void setDescEstesa(String descEstesa) {
        this.descEstesa = descEstesa == null ? null : descEstesa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_d_materiale.istruzioni
     *
     * @return the value of caronte.car_d_materiale.istruzioni
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public String getIstruzioni() {
        return istruzioni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_d_materiale.istruzioni
     *
     * @param istruzioni the value for caronte.car_d_materiale.istruzioni
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public void setIstruzioni(String istruzioni) {
        this.istruzioni = istruzioni == null ? null : istruzioni.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_d_materiale.inizio_validita
     *
     * @return the value of caronte.car_d_materiale.inizio_validita
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public Date getInizioValidita() {
        return inizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_d_materiale.inizio_validita
     *
     * @param inizioValidita the value for caronte.car_d_materiale.inizio_validita
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public void setInizioValidita(Date inizioValidita) {
        this.inizioValidita = inizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_d_materiale.fine_validita
     *
     * @return the value of caronte.car_d_materiale.fine_validita
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public Date getFineValidita() {
        return fineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_d_materiale.fine_validita
     *
     * @param fineValidita the value for caronte.car_d_materiale.fine_validita
     *
     * @mbg.generated Thu Jun 18 09:22:53 CEST 2020
     */
    public void setFineValidita(Date fineValidita) {
        this.fineValidita = fineValidita;
    }
}