package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;
import java.util.Date;

public class CarDNormaVerbale extends BaseDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_d_norma_verbale.id_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	private Long idNormaVerbale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_d_norma_verbale.desc_breve
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	private String descBreve;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_d_norma_verbale.desc_estesa
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	private String descEstesa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_d_norma_verbale.data_inizio_validita
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_d_norma_verbale.data_fine_validita
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	private Date dataFineValidita;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_d_norma_verbale.id_norma_verbale
	 * @return  the value of caronte.car_d_norma_verbale.id_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public Long getIdNormaVerbale() {
		return idNormaVerbale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_d_norma_verbale.id_norma_verbale
	 * @param idNormaVerbale  the value for caronte.car_d_norma_verbale.id_norma_verbale
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public void setIdNormaVerbale(Long idNormaVerbale) {
		this.idNormaVerbale = idNormaVerbale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_d_norma_verbale.desc_breve
	 * @return  the value of caronte.car_d_norma_verbale.desc_breve
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public String getDescBreve() {
		return descBreve;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_d_norma_verbale.desc_breve
	 * @param descBreve  the value for caronte.car_d_norma_verbale.desc_breve
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public void setDescBreve(String descBreve) {
		this.descBreve = descBreve == null ? null : descBreve.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_d_norma_verbale.desc_estesa
	 * @return  the value of caronte.car_d_norma_verbale.desc_estesa
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public String getDescEstesa() {
		return descEstesa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_d_norma_verbale.desc_estesa
	 * @param descEstesa  the value for caronte.car_d_norma_verbale.desc_estesa
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public void setDescEstesa(String descEstesa) {
		this.descEstesa = descEstesa == null ? null : descEstesa.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_d_norma_verbale.data_inizio_validita
	 * @return  the value of caronte.car_d_norma_verbale.data_inizio_validita
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_d_norma_verbale.data_inizio_validita
	 * @param dataInizioValidita  the value for caronte.car_d_norma_verbale.data_inizio_validita
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_d_norma_verbale.data_fine_validita
	 * @return  the value of caronte.car_d_norma_verbale.data_fine_validita
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_d_norma_verbale.data_fine_validita
	 * @param dataFineValidita  the value for caronte.car_d_norma_verbale.data_fine_validita
	 * @mbg.generated  Tue Dec 22 16:27:35 CET 2020
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}
}