package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.List;

public class CarDAssociazioneSezioneExample extends GenericExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public CarDAssociazioneSezioneExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdAssociazioneSezioneIsNull() {
      addCriterion("id_associazione_sezione is null");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneIsNotNull() {
      addCriterion("id_associazione_sezione is not null");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneEqualTo(Long value) {
      addCriterion("id_associazione_sezione =", value, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneNotEqualTo(Long value) {
      addCriterion("id_associazione_sezione <>", value, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneGreaterThan(Long value) {
      addCriterion("id_associazione_sezione >", value, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneGreaterThanOrEqualTo(Long value) {
      addCriterion("id_associazione_sezione >=", value, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneLessThan(Long value) {
      addCriterion("id_associazione_sezione <", value, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneLessThanOrEqualTo(Long value) {
      addCriterion("id_associazione_sezione <=", value, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneIn(List<Long> values) {
      addCriterion("id_associazione_sezione in", values, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneNotIn(List<Long> values) {
      addCriterion("id_associazione_sezione not in", values, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneBetween(Long value1, Long value2) {
      addCriterion("id_associazione_sezione between", value1, value2, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andIdAssociazioneSezioneNotBetween(Long value1, Long value2) {
      addCriterion("id_associazione_sezione not between", value1, value2, "idAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneIsNull() {
      addCriterion("desc_associazione_sezione is null");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneIsNotNull() {
      addCriterion("desc_associazione_sezione is not null");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneEqualTo(String value) {
      addCriterion("desc_associazione_sezione =", value, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneNotEqualTo(String value) {
      addCriterion("desc_associazione_sezione <>", value, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneGreaterThan(String value) {
      addCriterion("desc_associazione_sezione >", value, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneGreaterThanOrEqualTo(String value) {
      addCriterion("desc_associazione_sezione >=", value, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneLessThan(String value) {
      addCriterion("desc_associazione_sezione <", value, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneLessThanOrEqualTo(String value) {
      addCriterion("desc_associazione_sezione <=", value, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneLike(String value) {
      addCriterion("desc_associazione_sezione like", value, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneNotLike(String value) {
      addCriterion("desc_associazione_sezione not like", value, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneIn(List<String> values) {
      addCriterion("desc_associazione_sezione in", values, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneNotIn(List<String> values) {
      addCriterion("desc_associazione_sezione not in", values, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneBetween(String value1, String value2) {
      addCriterion("desc_associazione_sezione between", value1, value2, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneNotBetween(String value1, String value2) {
      addCriterion("desc_associazione_sezione not between", value1, value2, "descAssociazioneSezione");
      return (Criteria) this;
    }

    public Criteria andDescAssociazioneSezioneLikeInsensitive(String value) {
      addCriterion("upper(desc_associazione_sezione) like", value.toUpperCase(), "descAssociazioneSezione");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_d_associazione_sezione
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_d_associazione_sezione
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 14 19:16:19 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}