package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;

public class CarDTipoProdotto extends BaseDto {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_d_tipo_prodotto.id_tipo_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  private Long idTipoProdotto;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_d_tipo_prodotto.desc_tipo_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  private String descTipoProdotto;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_d_tipo_prodotto.id_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  private Long idUnitaMisura;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_d_tipo_prodotto.id_tipo_prodotto
   * @return  the value of caronte.car_d_tipo_prodotto.id_tipo_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Long getIdTipoProdotto() {
    return idTipoProdotto;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_d_tipo_prodotto.id_tipo_prodotto
   * @param idTipoProdotto  the value for caronte.car_d_tipo_prodotto.id_tipo_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setIdTipoProdotto(Long idTipoProdotto) {
    this.idTipoProdotto = idTipoProdotto;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_d_tipo_prodotto.desc_tipo_prodotto
   * @return  the value of caronte.car_d_tipo_prodotto.desc_tipo_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public String getDescTipoProdotto() {
    return descTipoProdotto;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_d_tipo_prodotto.desc_tipo_prodotto
   * @param descTipoProdotto  the value for caronte.car_d_tipo_prodotto.desc_tipo_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setDescTipoProdotto(String descTipoProdotto) {
    this.descTipoProdotto = descTipoProdotto == null ? null : descTipoProdotto.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_d_tipo_prodotto.id_unita_misura
   * @return  the value of caronte.car_d_tipo_prodotto.id_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Long getIdUnitaMisura() {
    return idUnitaMisura;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_d_tipo_prodotto.id_unita_misura
   * @param idUnitaMisura  the value for caronte.car_d_tipo_prodotto.id_unita_misura
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setIdUnitaMisura(Long idUnitaMisura) {
    this.idUnitaMisura = idUnitaMisura;
  }
}