package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.List;

public class CarDProdottoExample extends GenericExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public CarDProdottoExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdProdottoIsNull() {
      addCriterion("id_prodotto is null");
      return (Criteria) this;
    }

    public Criteria andIdProdottoIsNotNull() {
      addCriterion("id_prodotto is not null");
      return (Criteria) this;
    }

    public Criteria andIdProdottoEqualTo(Long value) {
      addCriterion("id_prodotto =", value, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoNotEqualTo(Long value) {
      addCriterion("id_prodotto <>", value, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoGreaterThan(Long value) {
      addCriterion("id_prodotto >", value, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoGreaterThanOrEqualTo(Long value) {
      addCriterion("id_prodotto >=", value, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoLessThan(Long value) {
      addCriterion("id_prodotto <", value, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoLessThanOrEqualTo(Long value) {
      addCriterion("id_prodotto <=", value, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoIn(List<Long> values) {
      addCriterion("id_prodotto in", values, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoNotIn(List<Long> values) {
      addCriterion("id_prodotto not in", values, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoBetween(Long value1, Long value2) {
      addCriterion("id_prodotto between", value1, value2, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andIdProdottoNotBetween(Long value1, Long value2) {
      addCriterion("id_prodotto not between", value1, value2, "idProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoIsNull() {
      addCriterion("cod_prodotto is null");
      return (Criteria) this;
    }

    public Criteria andCodProdottoIsNotNull() {
      addCriterion("cod_prodotto is not null");
      return (Criteria) this;
    }

    public Criteria andCodProdottoEqualTo(String value) {
      addCriterion("cod_prodotto =", value, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoNotEqualTo(String value) {
      addCriterion("cod_prodotto <>", value, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoGreaterThan(String value) {
      addCriterion("cod_prodotto >", value, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoGreaterThanOrEqualTo(String value) {
      addCriterion("cod_prodotto >=", value, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoLessThan(String value) {
      addCriterion("cod_prodotto <", value, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoLessThanOrEqualTo(String value) {
      addCriterion("cod_prodotto <=", value, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoLike(String value) {
      addCriterion("cod_prodotto like", value, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoNotLike(String value) {
      addCriterion("cod_prodotto not like", value, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoIn(List<String> values) {
      addCriterion("cod_prodotto in", values, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoNotIn(List<String> values) {
      addCriterion("cod_prodotto not in", values, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoBetween(String value1, String value2) {
      addCriterion("cod_prodotto between", value1, value2, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andCodProdottoNotBetween(String value1, String value2) {
      addCriterion("cod_prodotto not between", value1, value2, "codProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoIsNull() {
      addCriterion("denom_prodotto is null");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoIsNotNull() {
      addCriterion("denom_prodotto is not null");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoEqualTo(String value) {
      addCriterion("denom_prodotto =", value, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoNotEqualTo(String value) {
      addCriterion("denom_prodotto <>", value, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoGreaterThan(String value) {
      addCriterion("denom_prodotto >", value, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoGreaterThanOrEqualTo(String value) {
      addCriterion("denom_prodotto >=", value, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoLessThan(String value) {
      addCriterion("denom_prodotto <", value, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoLessThanOrEqualTo(String value) {
      addCriterion("denom_prodotto <=", value, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoLike(String value) {
      addCriterion("denom_prodotto like", value, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoNotLike(String value) {
      addCriterion("denom_prodotto not like", value, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoIn(List<String> values) {
      addCriterion("denom_prodotto in", values, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoNotIn(List<String> values) {
      addCriterion("denom_prodotto not in", values, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoBetween(String value1, String value2) {
      addCriterion("denom_prodotto between", value1, value2, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoNotBetween(String value1, String value2) {
      addCriterion("denom_prodotto not between", value1, value2, "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoIsNull() {
      addCriterion("denom_breve_prodotto is null");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoIsNotNull() {
      addCriterion("denom_breve_prodotto is not null");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoEqualTo(String value) {
      addCriterion("denom_breve_prodotto =", value, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoNotEqualTo(String value) {
      addCriterion("denom_breve_prodotto <>", value, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoGreaterThan(String value) {
      addCriterion("denom_breve_prodotto >", value, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoGreaterThanOrEqualTo(String value) {
      addCriterion("denom_breve_prodotto >=", value, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoLessThan(String value) {
      addCriterion("denom_breve_prodotto <", value, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoLessThanOrEqualTo(String value) {
      addCriterion("denom_breve_prodotto <=", value, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoLike(String value) {
      addCriterion("denom_breve_prodotto like", value, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoNotLike(String value) {
      addCriterion("denom_breve_prodotto not like", value, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoIn(List<String> values) {
      addCriterion("denom_breve_prodotto in", values, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoNotIn(List<String> values) {
      addCriterion("denom_breve_prodotto not in", values, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoBetween(String value1, String value2) {
      addCriterion("denom_breve_prodotto between", value1, value2, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoNotBetween(String value1, String value2) {
      addCriterion("denom_breve_prodotto not between", value1, value2, "denomBreveProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoIsNull() {
      addCriterion("id_tipo_prodotto is null");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoIsNotNull() {
      addCriterion("id_tipo_prodotto is not null");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoEqualTo(Long value) {
      addCriterion("id_tipo_prodotto =", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoNotEqualTo(Long value) {
      addCriterion("id_tipo_prodotto <>", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoGreaterThan(Long value) {
      addCriterion("id_tipo_prodotto >", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoGreaterThanOrEqualTo(Long value) {
      addCriterion("id_tipo_prodotto >=", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoLessThan(Long value) {
      addCriterion("id_tipo_prodotto <", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoLessThanOrEqualTo(Long value) {
      addCriterion("id_tipo_prodotto <=", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoIn(List<Long> values) {
      addCriterion("id_tipo_prodotto in", values, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoNotIn(List<Long> values) {
      addCriterion("id_tipo_prodotto not in", values, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoBetween(Long value1, Long value2) {
      addCriterion("id_tipo_prodotto between", value1, value2, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoNotBetween(Long value1, Long value2) {
      addCriterion("id_tipo_prodotto not between", value1, value2, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdClasseIsNull() {
      addCriterion("id_classe is null");
      return (Criteria) this;
    }

    public Criteria andIdClasseIsNotNull() {
      addCriterion("id_classe is not null");
      return (Criteria) this;
    }

    public Criteria andIdClasseEqualTo(Long value) {
      addCriterion("id_classe =", value, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseNotEqualTo(Long value) {
      addCriterion("id_classe <>", value, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseGreaterThan(Long value) {
      addCriterion("id_classe >", value, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseGreaterThanOrEqualTo(Long value) {
      addCriterion("id_classe >=", value, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseLessThan(Long value) {
      addCriterion("id_classe <", value, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseLessThanOrEqualTo(Long value) {
      addCriterion("id_classe <=", value, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseIn(List<Long> values) {
      addCriterion("id_classe in", values, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseNotIn(List<Long> values) {
      addCriterion("id_classe not in", values, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseBetween(Long value1, Long value2) {
      addCriterion("id_classe between", value1, value2, "idClasse");
      return (Criteria) this;
    }

    public Criteria andIdClasseNotBetween(Long value1, Long value2) {
      addCriterion("id_classe not between", value1, value2, "idClasse");
      return (Criteria) this;
    }

    public Criteria andCodProdottoLikeInsensitive(String value) {
      addCriterion("upper(cod_prodotto) like", value.toUpperCase(), "codProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomProdottoLikeInsensitive(String value) {
      addCriterion("upper(denom_prodotto) like", value.toUpperCase(), "denomProdotto");
      return (Criteria) this;
    }

    public Criteria andDenomBreveProdottoLikeInsensitive(String value) {
      addCriterion("upper(denom_breve_prodotto) like", value.toUpperCase(), "denomBreveProdotto");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_d_prodotto
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_d_prodotto
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 14 19:16:19 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}