package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CarDTariffaExample extends GenericExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public CarDTariffaExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    protected void addCriterionForJDBCDate(String condition, Date value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value.getTime()), property);
    }

    protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
      Iterator<Date> iter = values.iterator();
      while (iter.hasNext()) {
        dateList.add(new java.sql.Date(iter.next().getTime()));
      }
      addCriterion(condition, dateList, property);
    }

    protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
    }

    public Criteria andIdTariffaIsNull() {
      addCriterion("id_tariffa is null");
      return (Criteria) this;
    }

    public Criteria andIdTariffaIsNotNull() {
      addCriterion("id_tariffa is not null");
      return (Criteria) this;
    }

    public Criteria andIdTariffaEqualTo(Long value) {
      addCriterion("id_tariffa =", value, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaNotEqualTo(Long value) {
      addCriterion("id_tariffa <>", value, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaGreaterThan(Long value) {
      addCriterion("id_tariffa >", value, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaGreaterThanOrEqualTo(Long value) {
      addCriterion("id_tariffa >=", value, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaLessThan(Long value) {
      addCriterion("id_tariffa <", value, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaLessThanOrEqualTo(Long value) {
      addCriterion("id_tariffa <=", value, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaIn(List<Long> values) {
      addCriterion("id_tariffa in", values, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaNotIn(List<Long> values) {
      addCriterion("id_tariffa not in", values, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaBetween(Long value1, Long value2) {
      addCriterion("id_tariffa between", value1, value2, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTariffaNotBetween(Long value1, Long value2) {
      addCriterion("id_tariffa not between", value1, value2, "idTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaIsNull() {
      addCriterion("id_tipo_controllo_tariffa is null");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaIsNotNull() {
      addCriterion("id_tipo_controllo_tariffa is not null");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaEqualTo(Long value) {
      addCriterion("id_tipo_controllo_tariffa =", value, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaNotEqualTo(Long value) {
      addCriterion("id_tipo_controllo_tariffa <>", value, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaGreaterThan(Long value) {
      addCriterion("id_tipo_controllo_tariffa >", value, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaGreaterThanOrEqualTo(Long value) {
      addCriterion("id_tipo_controllo_tariffa >=", value, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaLessThan(Long value) {
      addCriterion("id_tipo_controllo_tariffa <", value, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaLessThanOrEqualTo(Long value) {
      addCriterion("id_tipo_controllo_tariffa <=", value, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaIn(List<Long> values) {
      addCriterion("id_tipo_controllo_tariffa in", values, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaNotIn(List<Long> values) {
      addCriterion("id_tipo_controllo_tariffa not in", values, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaBetween(Long value1, Long value2) {
      addCriterion("id_tipo_controllo_tariffa between", value1, value2, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoControlloTariffaNotBetween(Long value1, Long value2) {
      addCriterion("id_tipo_controllo_tariffa not between", value1, value2, "idTipoControlloTariffa");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoIsNull() {
      addCriterion("id_tipo_prodotto is null");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoIsNotNull() {
      addCriterion("id_tipo_prodotto is not null");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoEqualTo(Long value) {
      addCriterion("id_tipo_prodotto =", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoNotEqualTo(Long value) {
      addCriterion("id_tipo_prodotto <>", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoGreaterThan(Long value) {
      addCriterion("id_tipo_prodotto >", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoGreaterThanOrEqualTo(Long value) {
      addCriterion("id_tipo_prodotto >=", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoLessThan(Long value) {
      addCriterion("id_tipo_prodotto <", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoLessThanOrEqualTo(Long value) {
      addCriterion("id_tipo_prodotto <=", value, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoIn(List<Long> values) {
      addCriterion("id_tipo_prodotto in", values, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoNotIn(List<Long> values) {
      addCriterion("id_tipo_prodotto not in", values, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoBetween(Long value1, Long value2) {
      addCriterion("id_tipo_prodotto between", value1, value2, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIdTipoProdottoNotBetween(Long value1, Long value2) {
      addCriterion("id_tipo_prodotto not between", value1, value2, "idTipoProdotto");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaIsNull() {
      addCriterion("incremento_quantita is null");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaIsNotNull() {
      addCriterion("incremento_quantita is not null");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaEqualTo(Long value) {
      addCriterion("incremento_quantita =", value, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaNotEqualTo(Long value) {
      addCriterion("incremento_quantita <>", value, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaGreaterThan(Long value) {
      addCriterion("incremento_quantita >", value, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaGreaterThanOrEqualTo(Long value) {
      addCriterion("incremento_quantita >=", value, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaLessThan(Long value) {
      addCriterion("incremento_quantita <", value, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaLessThanOrEqualTo(Long value) {
      addCriterion("incremento_quantita <=", value, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaIn(List<Long> values) {
      addCriterion("incremento_quantita in", values, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaNotIn(List<Long> values) {
      addCriterion("incremento_quantita not in", values, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaBetween(Long value1, Long value2) {
      addCriterion("incremento_quantita between", value1, value2, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoQuantitaNotBetween(Long value1, Long value2) {
      addCriterion("incremento_quantita not between", value1, value2, "incrementoQuantita");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaIsNull() {
      addCriterion("incremento_tariffa is null");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaIsNotNull() {
      addCriterion("incremento_tariffa is not null");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaEqualTo(BigDecimal value) {
      addCriterion("incremento_tariffa =", value, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaNotEqualTo(BigDecimal value) {
      addCriterion("incremento_tariffa <>", value, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaGreaterThan(BigDecimal value) {
      addCriterion("incremento_tariffa >", value, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("incremento_tariffa >=", value, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaLessThan(BigDecimal value) {
      addCriterion("incremento_tariffa <", value, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("incremento_tariffa <=", value, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaIn(List<BigDecimal> values) {
      addCriterion("incremento_tariffa in", values, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaNotIn(List<BigDecimal> values) {
      addCriterion("incremento_tariffa not in", values, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("incremento_tariffa between", value1, value2, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andIncrementoTariffaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("incremento_tariffa not between", value1, value2, "incrementoTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaIsNull() {
      addCriterion("massimale_tariffa is null");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaIsNotNull() {
      addCriterion("massimale_tariffa is not null");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaEqualTo(BigDecimal value) {
      addCriterion("massimale_tariffa =", value, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaNotEqualTo(BigDecimal value) {
      addCriterion("massimale_tariffa <>", value, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaGreaterThan(BigDecimal value) {
      addCriterion("massimale_tariffa >", value, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("massimale_tariffa >=", value, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaLessThan(BigDecimal value) {
      addCriterion("massimale_tariffa <", value, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("massimale_tariffa <=", value, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaIn(List<BigDecimal> values) {
      addCriterion("massimale_tariffa in", values, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaNotIn(List<BigDecimal> values) {
      addCriterion("massimale_tariffa not in", values, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("massimale_tariffa between", value1, value2, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andMassimaleTariffaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("massimale_tariffa not between", value1, value2, "massimaleTariffa");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaIsNull() {
      addCriterion("inizio_validita is null");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaIsNotNull() {
      addCriterion("inizio_validita is not null");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaEqualTo(Date value) {
      addCriterionForJDBCDate("inizio_validita =", value, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaNotEqualTo(Date value) {
      addCriterionForJDBCDate("inizio_validita <>", value, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaGreaterThan(Date value) {
      addCriterionForJDBCDate("inizio_validita >", value, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("inizio_validita >=", value, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaLessThan(Date value) {
      addCriterionForJDBCDate("inizio_validita <", value, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("inizio_validita <=", value, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaIn(List<Date> values) {
      addCriterionForJDBCDate("inizio_validita in", values, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaNotIn(List<Date> values) {
      addCriterionForJDBCDate("inizio_validita not in", values, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("inizio_validita between", value1, value2, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andInizioValiditaNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("inizio_validita not between", value1, value2, "inizioValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaIsNull() {
      addCriterion("fine_validita is null");
      return (Criteria) this;
    }

    public Criteria andFineValiditaIsNotNull() {
      addCriterion("fine_validita is not null");
      return (Criteria) this;
    }

    public Criteria andFineValiditaEqualTo(Date value) {
      addCriterionForJDBCDate("fine_validita =", value, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaNotEqualTo(Date value) {
      addCriterionForJDBCDate("fine_validita <>", value, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaGreaterThan(Date value) {
      addCriterionForJDBCDate("fine_validita >", value, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("fine_validita >=", value, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaLessThan(Date value) {
      addCriterionForJDBCDate("fine_validita <", value, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("fine_validita <=", value, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaIn(List<Date> values) {
      addCriterionForJDBCDate("fine_validita in", values, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaNotIn(List<Date> values) {
      addCriterionForJDBCDate("fine_validita not in", values, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("fine_validita between", value1, value2, "fineValidita");
      return (Criteria) this;
    }

    public Criteria andFineValiditaNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("fine_validita not between", value1, value2, "fineValidita");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_d_tariffa
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_d_tariffa
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 14 19:16:19 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}