package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.List;

public class CarDAutoreEppoExample extends GenericExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public CarDAutoreEppoExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdAutoreEppoIsNull() {
      addCriterion("id_autore_eppo is null");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoIsNotNull() {
      addCriterion("id_autore_eppo is not null");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoEqualTo(Long value) {
      addCriterion("id_autore_eppo =", value, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoNotEqualTo(Long value) {
      addCriterion("id_autore_eppo <>", value, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoGreaterThan(Long value) {
      addCriterion("id_autore_eppo >", value, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoGreaterThanOrEqualTo(Long value) {
      addCriterion("id_autore_eppo >=", value, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoLessThan(Long value) {
      addCriterion("id_autore_eppo <", value, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoLessThanOrEqualTo(Long value) {
      addCriterion("id_autore_eppo <=", value, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoIn(List<Long> values) {
      addCriterion("id_autore_eppo in", values, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoNotIn(List<Long> values) {
      addCriterion("id_autore_eppo not in", values, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoBetween(Long value1, Long value2) {
      addCriterion("id_autore_eppo between", value1, value2, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andIdAutoreEppoNotBetween(Long value1, Long value2) {
      addCriterion("id_autore_eppo not between", value1, value2, "idAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoIsNull() {
      addCriterion("desc_autore_eppo is null");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoIsNotNull() {
      addCriterion("desc_autore_eppo is not null");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoEqualTo(String value) {
      addCriterion("desc_autore_eppo =", value, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoNotEqualTo(String value) {
      addCriterion("desc_autore_eppo <>", value, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoGreaterThan(String value) {
      addCriterion("desc_autore_eppo >", value, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoGreaterThanOrEqualTo(String value) {
      addCriterion("desc_autore_eppo >=", value, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoLessThan(String value) {
      addCriterion("desc_autore_eppo <", value, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoLessThanOrEqualTo(String value) {
      addCriterion("desc_autore_eppo <=", value, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoLike(String value) {
      addCriterion("desc_autore_eppo like", value, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoNotLike(String value) {
      addCriterion("desc_autore_eppo not like", value, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoIn(List<String> values) {
      addCriterion("desc_autore_eppo in", values, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoNotIn(List<String> values) {
      addCriterion("desc_autore_eppo not in", values, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoBetween(String value1, String value2) {
      addCriterion("desc_autore_eppo between", value1, value2, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoNotBetween(String value1, String value2) {
      addCriterion("desc_autore_eppo not between", value1, value2, "descAutoreEppo");
      return (Criteria) this;
    }

    public Criteria andDescAutoreEppoLikeInsensitive(String value) {
      addCriterion("upper(desc_autore_eppo) like", value.toUpperCase(), "descAutoreEppo");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_d_autore_eppo
   * @mbg.generated  Tue Mar 10 17:11:28 CET 2020
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_d_autore_eppo
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 14 19:16:19 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}