package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;
import java.util.Date;

public class CarRTipoFlussoCom extends BaseDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_tipo_flusso_com.id_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    private Long idTipoFlusso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_tipo_flusso_com.id_tipo_comunicazione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    private Long idTipoComunicazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_tipo_flusso_com.descrizione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    private String descrizione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_tipo_flusso_com.ordinamento
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    private Long ordinamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_tipo_flusso_com.id_stato_comunicazione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    private Long idStatoComunicazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_tipo_flusso_com.inizio_validita
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    private Date inizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_tipo_flusso_com.fine_validita
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    private Date fineValidita;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_tipo_flusso_com.id_tipo_flusso
     *
     * @return the value of caronte.car_r_tipo_flusso_com.id_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public Long getIdTipoFlusso() {
        return idTipoFlusso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_tipo_flusso_com.id_tipo_flusso
     *
     * @param idTipoFlusso the value for caronte.car_r_tipo_flusso_com.id_tipo_flusso
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public void setIdTipoFlusso(Long idTipoFlusso) {
        this.idTipoFlusso = idTipoFlusso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_tipo_flusso_com.id_tipo_comunicazione
     *
     * @return the value of caronte.car_r_tipo_flusso_com.id_tipo_comunicazione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public Long getIdTipoComunicazione() {
        return idTipoComunicazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_tipo_flusso_com.id_tipo_comunicazione
     *
     * @param idTipoComunicazione the value for caronte.car_r_tipo_flusso_com.id_tipo_comunicazione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public void setIdTipoComunicazione(Long idTipoComunicazione) {
        this.idTipoComunicazione = idTipoComunicazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_tipo_flusso_com.descrizione
     *
     * @return the value of caronte.car_r_tipo_flusso_com.descrizione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_tipo_flusso_com.descrizione
     *
     * @param descrizione the value for caronte.car_r_tipo_flusso_com.descrizione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione == null ? null : descrizione.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_tipo_flusso_com.ordinamento
     *
     * @return the value of caronte.car_r_tipo_flusso_com.ordinamento
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public Long getOrdinamento() {
        return ordinamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_tipo_flusso_com.ordinamento
     *
     * @param ordinamento the value for caronte.car_r_tipo_flusso_com.ordinamento
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public void setOrdinamento(Long ordinamento) {
        this.ordinamento = ordinamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_tipo_flusso_com.id_stato_comunicazione
     *
     * @return the value of caronte.car_r_tipo_flusso_com.id_stato_comunicazione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public Long getIdStatoComunicazione() {
        return idStatoComunicazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_tipo_flusso_com.id_stato_comunicazione
     *
     * @param idStatoComunicazione the value for caronte.car_r_tipo_flusso_com.id_stato_comunicazione
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public void setIdStatoComunicazione(Long idStatoComunicazione) {
        this.idStatoComunicazione = idStatoComunicazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_tipo_flusso_com.inizio_validita
     *
     * @return the value of caronte.car_r_tipo_flusso_com.inizio_validita
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public Date getInizioValidita() {
        return inizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_tipo_flusso_com.inizio_validita
     *
     * @param inizioValidita the value for caronte.car_r_tipo_flusso_com.inizio_validita
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public void setInizioValidita(Date inizioValidita) {
        this.inizioValidita = inizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_tipo_flusso_com.fine_validita
     *
     * @return the value of caronte.car_r_tipo_flusso_com.fine_validita
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public Date getFineValidita() {
        return fineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_tipo_flusso_com.fine_validita
     *
     * @param fineValidita the value for caronte.car_r_tipo_flusso_com.fine_validita
     *
     * @mbg.generated Thu Jun 18 09:18:38 CEST 2020
     */
    public void setFineValidita(Date fineValidita) {
        this.fineValidita = fineValidita;
    }
}