package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;

public class CarRGruppoStatoCom extends BaseDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_gruppo_stato_com.id_gruppo
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    private Long idGruppo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_gruppo_stato_com.id_stato_comunicazione
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    private Long idStatoComunicazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_gruppo_stato_com.richiesta_modificabile
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    private Boolean richiestaModificabile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_gruppo_stato_com.id_gruppo
     *
     * @return the value of caronte.car_r_gruppo_stato_com.id_gruppo
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    public Long getIdGruppo() {
        return idGruppo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_gruppo_stato_com.id_gruppo
     *
     * @param idGruppo the value for caronte.car_r_gruppo_stato_com.id_gruppo
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    public void setIdGruppo(Long idGruppo) {
        this.idGruppo = idGruppo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_gruppo_stato_com.id_stato_comunicazione
     *
     * @return the value of caronte.car_r_gruppo_stato_com.id_stato_comunicazione
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    public Long getIdStatoComunicazione() {
        return idStatoComunicazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_gruppo_stato_com.id_stato_comunicazione
     *
     * @param idStatoComunicazione the value for caronte.car_r_gruppo_stato_com.id_stato_comunicazione
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    public void setIdStatoComunicazione(Long idStatoComunicazione) {
        this.idStatoComunicazione = idStatoComunicazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_gruppo_stato_com.richiesta_modificabile
     *
     * @return the value of caronte.car_r_gruppo_stato_com.richiesta_modificabile
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    public Boolean getRichiestaModificabile() {
        return richiestaModificabile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_gruppo_stato_com.richiesta_modificabile
     *
     * @param richiestaModificabile the value for caronte.car_r_gruppo_stato_com.richiesta_modificabile
     *
     * @mbg.generated Tue Mar 10 17:11:28 CET 2020
     */
    public void setRichiestaModificabile(Boolean richiestaModificabile) {
        this.richiestaModificabile = richiestaModificabile;
    }
}