package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;

public class CarRSpedizAssocSezione extends BaseDto {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_r_spediz_assoc_sezione.id_spedizioniere
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  private Long idSpedizioniere;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_r_spediz_assoc_sezione.id_associazione_sezione
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  private Long idAssociazioneSezione;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_r_spediz_assoc_sezione.id_spedizioniere
   * @return  the value of caronte.car_r_spediz_assoc_sezione.id_spedizioniere
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  public Long getIdSpedizioniere() {
    return idSpedizioniere;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_r_spediz_assoc_sezione.id_spedizioniere
   * @param idSpedizioniere  the value for caronte.car_r_spediz_assoc_sezione.id_spedizioniere
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  public void setIdSpedizioniere(Long idSpedizioniere) {
    this.idSpedizioniere = idSpedizioniere;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_r_spediz_assoc_sezione.id_associazione_sezione
   * @return  the value of caronte.car_r_spediz_assoc_sezione.id_associazione_sezione
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  public Long getIdAssociazioneSezione() {
    return idAssociazioneSezione;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_r_spediz_assoc_sezione.id_associazione_sezione
   * @param idAssociazioneSezione  the value for caronte.car_r_spediz_assoc_sezione.id_associazione_sezione
   * @mbg.generated  Wed Oct 31 16:30:01 CET 2018
   */
  public void setIdAssociazioneSezione(Long idAssociazioneSezione) {
    this.idAssociazioneSezione = idAssociazioneSezione;
  }
}