package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;

public class CarRVoceUtenteSpecie extends BaseDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_r_voce_utente_specie.id_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	private Long idVoceUtenteSpecie;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_r_voce_utente_specie.id_voce_utente
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	private Long idVoceUtente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_r_voce_utente_specie.id_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	private Long idSpecie;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_r_voce_utente_specie.id_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	private Long idGenere;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_r_voce_utente_specie.id_voce_utente_specie
	 * @return  the value of caronte.car_r_voce_utente_specie.id_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public Long getIdVoceUtenteSpecie() {
		return idVoceUtenteSpecie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_r_voce_utente_specie.id_voce_utente_specie
	 * @param idVoceUtenteSpecie  the value for caronte.car_r_voce_utente_specie.id_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public void setIdVoceUtenteSpecie(Long idVoceUtenteSpecie) {
		this.idVoceUtenteSpecie = idVoceUtenteSpecie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_r_voce_utente_specie.id_voce_utente
	 * @return  the value of caronte.car_r_voce_utente_specie.id_voce_utente
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public Long getIdVoceUtente() {
		return idVoceUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_r_voce_utente_specie.id_voce_utente
	 * @param idVoceUtente  the value for caronte.car_r_voce_utente_specie.id_voce_utente
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public void setIdVoceUtente(Long idVoceUtente) {
		this.idVoceUtente = idVoceUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_r_voce_utente_specie.id_specie
	 * @return  the value of caronte.car_r_voce_utente_specie.id_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public Long getIdSpecie() {
		return idSpecie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_r_voce_utente_specie.id_specie
	 * @param idSpecie  the value for caronte.car_r_voce_utente_specie.id_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public void setIdSpecie(Long idSpecie) {
		this.idSpecie = idSpecie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_r_voce_utente_specie.id_genere
	 * @return  the value of caronte.car_r_voce_utente_specie.id_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public Long getIdGenere() {
		return idGenere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_r_voce_utente_specie.id_genere
	 * @param idGenere  the value for caronte.car_r_voce_utente_specie.id_genere
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public void setIdGenere(Long idGenere) {
		this.idGenere = idGenere;
	}
}