package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarRMisuraOrgNocExample extends GenericExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public CarRMisuraOrgNocExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdMisuraUfficialeIsNull() {
            addCriterion("id_misura_ufficiale is null");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeIsNotNull() {
            addCriterion("id_misura_ufficiale is not null");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeEqualTo(Long value) {
            addCriterion("id_misura_ufficiale =", value, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeNotEqualTo(Long value) {
            addCriterion("id_misura_ufficiale <>", value, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeGreaterThan(Long value) {
            addCriterion("id_misura_ufficiale >", value, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeGreaterThanOrEqualTo(Long value) {
            addCriterion("id_misura_ufficiale >=", value, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeLessThan(Long value) {
            addCriterion("id_misura_ufficiale <", value, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeLessThanOrEqualTo(Long value) {
            addCriterion("id_misura_ufficiale <=", value, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeIn(List<Long> values) {
            addCriterion("id_misura_ufficiale in", values, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeNotIn(List<Long> values) {
            addCriterion("id_misura_ufficiale not in", values, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeBetween(Long value1, Long value2) {
            addCriterion("id_misura_ufficiale between", value1, value2, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdMisuraUfficialeNotBetween(Long value1, Long value2) {
            addCriterion("id_misura_ufficiale not between", value1, value2, "idMisuraUfficiale");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoIsNull() {
            addCriterion("id_org_nocivo is null");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoIsNotNull() {
            addCriterion("id_org_nocivo is not null");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoEqualTo(Long value) {
            addCriterion("id_org_nocivo =", value, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoNotEqualTo(Long value) {
            addCriterion("id_org_nocivo <>", value, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoGreaterThan(Long value) {
            addCriterion("id_org_nocivo >", value, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_org_nocivo >=", value, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoLessThan(Long value) {
            addCriterion("id_org_nocivo <", value, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoLessThanOrEqualTo(Long value) {
            addCriterion("id_org_nocivo <=", value, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoIn(List<Long> values) {
            addCriterion("id_org_nocivo in", values, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoNotIn(List<Long> values) {
            addCriterion("id_org_nocivo not in", values, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoBetween(Long value1, Long value2) {
            addCriterion("id_org_nocivo between", value1, value2, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdOrgNocivoNotBetween(Long value1, Long value2) {
            addCriterion("id_org_nocivo not between", value1, value2, "idOrgNocivo");
            return (Criteria) this;
        }

        public Criteria andIdGenereIsNull() {
            addCriterion("id_genere is null");
            return (Criteria) this;
        }

        public Criteria andIdGenereIsNotNull() {
            addCriterion("id_genere is not null");
            return (Criteria) this;
        }

        public Criteria andIdGenereEqualTo(Long value) {
            addCriterion("id_genere =", value, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereNotEqualTo(Long value) {
            addCriterion("id_genere <>", value, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereGreaterThan(Long value) {
            addCriterion("id_genere >", value, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereGreaterThanOrEqualTo(Long value) {
            addCriterion("id_genere >=", value, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereLessThan(Long value) {
            addCriterion("id_genere <", value, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereLessThanOrEqualTo(Long value) {
            addCriterion("id_genere <=", value, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereIn(List<Long> values) {
            addCriterion("id_genere in", values, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereNotIn(List<Long> values) {
            addCriterion("id_genere not in", values, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereBetween(Long value1, Long value2) {
            addCriterion("id_genere between", value1, value2, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdGenereNotBetween(Long value1, Long value2) {
            addCriterion("id_genere not between", value1, value2, "idGenere");
            return (Criteria) this;
        }

        public Criteria andIdSpecieIsNull() {
            addCriterion("id_specie is null");
            return (Criteria) this;
        }

        public Criteria andIdSpecieIsNotNull() {
            addCriterion("id_specie is not null");
            return (Criteria) this;
        }

        public Criteria andIdSpecieEqualTo(Long value) {
            addCriterion("id_specie =", value, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieNotEqualTo(Long value) {
            addCriterion("id_specie <>", value, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieGreaterThan(Long value) {
            addCriterion("id_specie >", value, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieGreaterThanOrEqualTo(Long value) {
            addCriterion("id_specie >=", value, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieLessThan(Long value) {
            addCriterion("id_specie <", value, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieLessThanOrEqualTo(Long value) {
            addCriterion("id_specie <=", value, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieIn(List<Long> values) {
            addCriterion("id_specie in", values, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieNotIn(List<Long> values) {
            addCriterion("id_specie not in", values, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieBetween(Long value1, Long value2) {
            addCriterion("id_specie between", value1, value2, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andIdSpecieNotBetween(Long value1, Long value2) {
            addCriterion("id_specie not between", value1, value2, "idSpecie");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteIsNull() {
            addCriterion("numero_piante is null");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteIsNotNull() {
            addCriterion("numero_piante is not null");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteEqualTo(Long value) {
            addCriterion("numero_piante =", value, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteNotEqualTo(Long value) {
            addCriterion("numero_piante <>", value, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteGreaterThan(Long value) {
            addCriterion("numero_piante >", value, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteGreaterThanOrEqualTo(Long value) {
            addCriterion("numero_piante >=", value, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteLessThan(Long value) {
            addCriterion("numero_piante <", value, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteLessThanOrEqualTo(Long value) {
            addCriterion("numero_piante <=", value, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteIn(List<Long> values) {
            addCriterion("numero_piante in", values, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteNotIn(List<Long> values) {
            addCriterion("numero_piante not in", values, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteBetween(Long value1, Long value2) {
            addCriterion("numero_piante between", value1, value2, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNumeroPianteNotBetween(Long value1, Long value2) {
            addCriterion("numero_piante not between", value1, value2, "numeroPiante");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoIsNull() {
            addCriterion("id_utente_inserimento is null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoIsNotNull() {
            addCriterion("id_utente_inserimento is not null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoEqualTo(Long value) {
            addCriterion("id_utente_inserimento =", value, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoNotEqualTo(Long value) {
            addCriterion("id_utente_inserimento <>", value, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoGreaterThan(Long value) {
            addCriterion("id_utente_inserimento >", value, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_utente_inserimento >=", value, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoLessThan(Long value) {
            addCriterion("id_utente_inserimento <", value, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoLessThanOrEqualTo(Long value) {
            addCriterion("id_utente_inserimento <=", value, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoIn(List<Long> values) {
            addCriterion("id_utente_inserimento in", values, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoNotIn(List<Long> values) {
            addCriterion("id_utente_inserimento not in", values, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoBetween(Long value1, Long value2) {
            addCriterion("id_utente_inserimento between", value1, value2, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteInserimentoNotBetween(Long value1, Long value2) {
            addCriterion("id_utente_inserimento not between", value1, value2, "idUtenteInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoIsNull() {
            addCriterion("data_inserimento is null");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoIsNotNull() {
            addCriterion("data_inserimento is not null");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoEqualTo(Date value) {
            addCriterion("data_inserimento =", value, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoNotEqualTo(Date value) {
            addCriterion("data_inserimento <>", value, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoGreaterThan(Date value) {
            addCriterion("data_inserimento >", value, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoGreaterThanOrEqualTo(Date value) {
            addCriterion("data_inserimento >=", value, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoLessThan(Date value) {
            addCriterion("data_inserimento <", value, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoLessThanOrEqualTo(Date value) {
            addCriterion("data_inserimento <=", value, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoIn(List<Date> values) {
            addCriterion("data_inserimento in", values, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoNotIn(List<Date> values) {
            addCriterion("data_inserimento not in", values, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoBetween(Date value1, Date value2) {
            addCriterion("data_inserimento between", value1, value2, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andDataInserimentoNotBetween(Date value1, Date value2) {
            addCriterion("data_inserimento not between", value1, value2, "dataInserimento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIsNull() {
            addCriterion("id_utente_aggiornamento is null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIsNotNull() {
            addCriterion("id_utente_aggiornamento is not null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento =", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento <>", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoGreaterThan(Long value) {
            addCriterion("id_utente_aggiornamento >", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento >=", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoLessThan(Long value) {
            addCriterion("id_utente_aggiornamento <", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoLessThanOrEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento <=", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIn(List<Long> values) {
            addCriterion("id_utente_aggiornamento in", values, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotIn(List<Long> values) {
            addCriterion("id_utente_aggiornamento not in", values, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoBetween(Long value1, Long value2) {
            addCriterion("id_utente_aggiornamento between", value1, value2, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotBetween(Long value1, Long value2) {
            addCriterion("id_utente_aggiornamento not between", value1, value2, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIsNull() {
            addCriterion("data_aggiornamento is null");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIsNotNull() {
            addCriterion("data_aggiornamento is not null");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoEqualTo(Date value) {
            addCriterion("data_aggiornamento =", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotEqualTo(Date value) {
            addCriterion("data_aggiornamento <>", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoGreaterThan(Date value) {
            addCriterion("data_aggiornamento >", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoGreaterThanOrEqualTo(Date value) {
            addCriterion("data_aggiornamento >=", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoLessThan(Date value) {
            addCriterion("data_aggiornamento <", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoLessThanOrEqualTo(Date value) {
            addCriterion("data_aggiornamento <=", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIn(List<Date> values) {
            addCriterion("data_aggiornamento in", values, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotIn(List<Date> values) {
            addCriterion("data_aggiornamento not in", values, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoBetween(Date value1, Date value2) {
            addCriterion("data_aggiornamento between", value1, value2, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotBetween(Date value1, Date value2) {
            addCriterion("data_aggiornamento not between", value1, value2, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andNoteLikeInsensitive(String value) {
            addCriterion("upper(note) like", value.toUpperCase(), "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 01 18:18:59 CET 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_r_misura_org_noc
     *
     * @mbg.generated Mon Feb 01 18:18:59 CET 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}