package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;
import java.util.Date;

public class CarRControlloFisicoMetPro extends BaseDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_controllo_fisico_met_pro.id_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    private Long idControlloFisico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_controllo_fisico_met_pro.id_metodo_produzione
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    private Long idMetodoProduzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_controllo_fisico_met_pro.id_utente_inserimento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    private Long idUtenteInserimento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_controllo_fisico_met_pro.data_inserimento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    private Date dataInserimento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_controllo_fisico_met_pro.id_utente_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    private Long idUtenteAggiornamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_r_controllo_fisico_met_pro.data_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    private Date dataAggiornamento;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_controllo_fisico_met_pro.id_controllo_fisico
     *
     * @return the value of caronte.car_r_controllo_fisico_met_pro.id_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public Long getIdControlloFisico() {
        return idControlloFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_controllo_fisico_met_pro.id_controllo_fisico
     *
     * @param idControlloFisico the value for caronte.car_r_controllo_fisico_met_pro.id_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public void setIdControlloFisico(Long idControlloFisico) {
        this.idControlloFisico = idControlloFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_controllo_fisico_met_pro.id_metodo_produzione
     *
     * @return the value of caronte.car_r_controllo_fisico_met_pro.id_metodo_produzione
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public Long getIdMetodoProduzione() {
        return idMetodoProduzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_controllo_fisico_met_pro.id_metodo_produzione
     *
     * @param idMetodoProduzione the value for caronte.car_r_controllo_fisico_met_pro.id_metodo_produzione
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public void setIdMetodoProduzione(Long idMetodoProduzione) {
        this.idMetodoProduzione = idMetodoProduzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_controllo_fisico_met_pro.id_utente_inserimento
     *
     * @return the value of caronte.car_r_controllo_fisico_met_pro.id_utente_inserimento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public Long getIdUtenteInserimento() {
        return idUtenteInserimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_controllo_fisico_met_pro.id_utente_inserimento
     *
     * @param idUtenteInserimento the value for caronte.car_r_controllo_fisico_met_pro.id_utente_inserimento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public void setIdUtenteInserimento(Long idUtenteInserimento) {
        this.idUtenteInserimento = idUtenteInserimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_controllo_fisico_met_pro.data_inserimento
     *
     * @return the value of caronte.car_r_controllo_fisico_met_pro.data_inserimento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public Date getDataInserimento() {
        return dataInserimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_controllo_fisico_met_pro.data_inserimento
     *
     * @param dataInserimento the value for caronte.car_r_controllo_fisico_met_pro.data_inserimento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public void setDataInserimento(Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_controllo_fisico_met_pro.id_utente_aggiornamento
     *
     * @return the value of caronte.car_r_controllo_fisico_met_pro.id_utente_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public Long getIdUtenteAggiornamento() {
        return idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_controllo_fisico_met_pro.id_utente_aggiornamento
     *
     * @param idUtenteAggiornamento the value for caronte.car_r_controllo_fisico_met_pro.id_utente_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
        this.idUtenteAggiornamento = idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_r_controllo_fisico_met_pro.data_aggiornamento
     *
     * @return the value of caronte.car_r_controllo_fisico_met_pro.data_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public Date getDataAggiornamento() {
        return dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_r_controllo_fisico_met_pro.data_aggiornamento
     *
     * @param dataAggiornamento the value for caronte.car_r_controllo_fisico_met_pro.data_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:38:57 CET 2020
     */
    public void setDataAggiornamento(Date dataAggiornamento) {
        this.dataAggiornamento = dataAggiornamento;
    }
}