package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.List;

public class CarRVoceUtenteSpecieExample extends GenericExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public CarRVoceUtenteSpecieExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdVoceUtenteSpecieIsNull() {
			addCriterion("id_voce_utente_specie is null");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieIsNotNull() {
			addCriterion("id_voce_utente_specie is not null");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieEqualTo(Long value) {
			addCriterion("id_voce_utente_specie =", value, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieNotEqualTo(Long value) {
			addCriterion("id_voce_utente_specie <>", value, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieGreaterThan(Long value) {
			addCriterion("id_voce_utente_specie >", value, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieGreaterThanOrEqualTo(Long value) {
			addCriterion("id_voce_utente_specie >=", value, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieLessThan(Long value) {
			addCriterion("id_voce_utente_specie <", value, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieLessThanOrEqualTo(Long value) {
			addCriterion("id_voce_utente_specie <=", value, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieIn(List<Long> values) {
			addCriterion("id_voce_utente_specie in", values, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieNotIn(List<Long> values) {
			addCriterion("id_voce_utente_specie not in", values, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieBetween(Long value1, Long value2) {
			addCriterion("id_voce_utente_specie between", value1, value2, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteSpecieNotBetween(Long value1, Long value2) {
			addCriterion("id_voce_utente_specie not between", value1, value2, "idVoceUtenteSpecie");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteIsNull() {
			addCriterion("id_voce_utente is null");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteIsNotNull() {
			addCriterion("id_voce_utente is not null");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteEqualTo(Long value) {
			addCriterion("id_voce_utente =", value, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteNotEqualTo(Long value) {
			addCriterion("id_voce_utente <>", value, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteGreaterThan(Long value) {
			addCriterion("id_voce_utente >", value, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteGreaterThanOrEqualTo(Long value) {
			addCriterion("id_voce_utente >=", value, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteLessThan(Long value) {
			addCriterion("id_voce_utente <", value, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteLessThanOrEqualTo(Long value) {
			addCriterion("id_voce_utente <=", value, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteIn(List<Long> values) {
			addCriterion("id_voce_utente in", values, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteNotIn(List<Long> values) {
			addCriterion("id_voce_utente not in", values, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteBetween(Long value1, Long value2) {
			addCriterion("id_voce_utente between", value1, value2, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdVoceUtenteNotBetween(Long value1, Long value2) {
			addCriterion("id_voce_utente not between", value1, value2, "idVoceUtente");
			return (Criteria) this;
		}

		public Criteria andIdSpecieIsNull() {
			addCriterion("id_specie is null");
			return (Criteria) this;
		}

		public Criteria andIdSpecieIsNotNull() {
			addCriterion("id_specie is not null");
			return (Criteria) this;
		}

		public Criteria andIdSpecieEqualTo(Long value) {
			addCriterion("id_specie =", value, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieNotEqualTo(Long value) {
			addCriterion("id_specie <>", value, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieGreaterThan(Long value) {
			addCriterion("id_specie >", value, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieGreaterThanOrEqualTo(Long value) {
			addCriterion("id_specie >=", value, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieLessThan(Long value) {
			addCriterion("id_specie <", value, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieLessThanOrEqualTo(Long value) {
			addCriterion("id_specie <=", value, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieIn(List<Long> values) {
			addCriterion("id_specie in", values, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieNotIn(List<Long> values) {
			addCriterion("id_specie not in", values, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieBetween(Long value1, Long value2) {
			addCriterion("id_specie between", value1, value2, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdSpecieNotBetween(Long value1, Long value2) {
			addCriterion("id_specie not between", value1, value2, "idSpecie");
			return (Criteria) this;
		}

		public Criteria andIdGenereIsNull() {
			addCriterion("id_genere is null");
			return (Criteria) this;
		}

		public Criteria andIdGenereIsNotNull() {
			addCriterion("id_genere is not null");
			return (Criteria) this;
		}

		public Criteria andIdGenereEqualTo(Long value) {
			addCriterion("id_genere =", value, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereNotEqualTo(Long value) {
			addCriterion("id_genere <>", value, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereGreaterThan(Long value) {
			addCriterion("id_genere >", value, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereGreaterThanOrEqualTo(Long value) {
			addCriterion("id_genere >=", value, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereLessThan(Long value) {
			addCriterion("id_genere <", value, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereLessThanOrEqualTo(Long value) {
			addCriterion("id_genere <=", value, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereIn(List<Long> values) {
			addCriterion("id_genere in", values, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereNotIn(List<Long> values) {
			addCriterion("id_genere not in", values, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereBetween(Long value1, Long value2) {
			addCriterion("id_genere between", value1, value2, "idGenere");
			return (Criteria) this;
		}

		public Criteria andIdGenereNotBetween(Long value1, Long value2) {
			addCriterion("id_genere not between", value1, value2, "idGenere");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_r_voce_utente_specie
	 * @mbg.generated  Fri Oct 23 14:45:57 CEST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_r_voce_utente_specie
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 04 15:28:59 CEST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}