package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.time.LocalTime;

public class CarTCertificatoExample extends GenericExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public CarTCertificatoExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    protected void addCriterionForJDBCDate(String condition, Date value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value.getTime()), property);
    }

    protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
      Iterator<Date> iter = values.iterator();
      while (iter.hasNext()) {
        dateList.add(new java.sql.Date(iter.next().getTime()));
      }
      addCriterion(condition, dateList, property);
    }

    protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
    }

    public Criteria andIdCertificatoIsNull() {
      addCriterion("id_certificato is null");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoIsNotNull() {
      addCriterion("id_certificato is not null");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoEqualTo(Long value) {
      addCriterion("id_certificato =", value, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoNotEqualTo(Long value) {
      addCriterion("id_certificato <>", value, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoGreaterThan(Long value) {
      addCriterion("id_certificato >", value, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoGreaterThanOrEqualTo(Long value) {
      addCriterion("id_certificato >=", value, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoLessThan(Long value) {
      addCriterion("id_certificato <", value, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoLessThanOrEqualTo(Long value) {
      addCriterion("id_certificato <=", value, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoIn(List<Long> values) {
      addCriterion("id_certificato in", values, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoNotIn(List<Long> values) {
      addCriterion("id_certificato not in", values, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoBetween(Long value1, Long value2) {
      addCriterion("id_certificato between", value1, value2, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andIdCertificatoNotBetween(Long value1, Long value2) {
      addCriterion("id_certificato not between", value1, value2, "idCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoIsNull() {
      addCriterion("numero_certificato is null");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoIsNotNull() {
      addCriterion("numero_certificato is not null");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoEqualTo(String value) {
      addCriterion("numero_certificato =", value, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoNotEqualTo(String value) {
      addCriterion("numero_certificato <>", value, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoGreaterThan(String value) {
      addCriterion("numero_certificato >", value, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoGreaterThanOrEqualTo(String value) {
      addCriterion("numero_certificato >=", value, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoLessThan(String value) {
      addCriterion("numero_certificato <", value, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoLessThanOrEqualTo(String value) {
      addCriterion("numero_certificato <=", value, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoLike(String value) {
      addCriterion("numero_certificato like", value, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoNotLike(String value) {
      addCriterion("numero_certificato not like", value, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoIn(List<String> values) {
      addCriterion("numero_certificato in", values, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoNotIn(List<String> values) {
      addCriterion("numero_certificato not in", values, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoBetween(String value1, String value2) {
      addCriterion("numero_certificato between", value1, value2, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoNotBetween(String value1, String value2) {
      addCriterion("numero_certificato not between", value1, value2, "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeIsNull() {
      addCriterion("numero_certificato_manuale is null");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeIsNotNull() {
      addCriterion("numero_certificato_manuale is not null");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeEqualTo(String value) {
      addCriterion("numero_certificato_manuale =", value, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeNotEqualTo(String value) {
      addCriterion("numero_certificato_manuale <>", value, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeGreaterThan(String value) {
      addCriterion("numero_certificato_manuale >", value, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeGreaterThanOrEqualTo(String value) {
      addCriterion("numero_certificato_manuale >=", value, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeLessThan(String value) {
      addCriterion("numero_certificato_manuale <", value, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeLessThanOrEqualTo(String value) {
      addCriterion("numero_certificato_manuale <=", value, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeLike(String value) {
      addCriterion("numero_certificato_manuale like", value, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeNotLike(String value) {
      addCriterion("numero_certificato_manuale not like", value, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeIn(List<String> values) {
      addCriterion("numero_certificato_manuale in", values, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeNotIn(List<String> values) {
      addCriterion("numero_certificato_manuale not in", values, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeBetween(String value1, String value2) {
      addCriterion("numero_certificato_manuale between", value1, value2, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeNotBetween(String value1, String value2) {
      addCriterion("numero_certificato_manuale not between", value1, value2, "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneIsNull() {
      addCriterion("id_ufficio_doganale_esecuzione is null");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneIsNotNull() {
      addCriterion("id_ufficio_doganale_esecuzione is not null");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneEqualTo(Long value) {
      addCriterion("id_ufficio_doganale_esecuzione =", value, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneNotEqualTo(Long value) {
      addCriterion("id_ufficio_doganale_esecuzione <>", value, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneGreaterThan(Long value) {
      addCriterion("id_ufficio_doganale_esecuzione >", value, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneGreaterThanOrEqualTo(Long value) {
      addCriterion("id_ufficio_doganale_esecuzione >=", value, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneLessThan(Long value) {
      addCriterion("id_ufficio_doganale_esecuzione <", value, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneLessThanOrEqualTo(Long value) {
      addCriterion("id_ufficio_doganale_esecuzione <=", value, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneIn(List<Long> values) {
      addCriterion("id_ufficio_doganale_esecuzione in", values, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneNotIn(List<Long> values) {
      addCriterion("id_ufficio_doganale_esecuzione not in", values, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneBetween(Long value1, Long value2) {
      addCriterion("id_ufficio_doganale_esecuzione between", value1, value2, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdUfficioDoganaleEsecuzioneNotBetween(Long value1, Long value2) {
      addCriterion("id_ufficio_doganale_esecuzione not between", value1, value2, "idUfficioDoganaleEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneIsNull() {
      addCriterion("data_esecuzione is null");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneIsNotNull() {
      addCriterion("data_esecuzione is not null");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneEqualTo(Date value) {
      addCriterionForJDBCDate("data_esecuzione =", value, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneNotEqualTo(Date value) {
      addCriterionForJDBCDate("data_esecuzione <>", value, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneGreaterThan(Date value) {
      addCriterionForJDBCDate("data_esecuzione >", value, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("data_esecuzione >=", value, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneLessThan(Date value) {
      addCriterionForJDBCDate("data_esecuzione <", value, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("data_esecuzione <=", value, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneIn(List<Date> values) {
      addCriterionForJDBCDate("data_esecuzione in", values, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneNotIn(List<Date> values) {
      addCriterionForJDBCDate("data_esecuzione not in", values, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("data_esecuzione between", value1, value2, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDataEsecuzioneNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("data_esecuzione not between", value1, value2, "dataEsecuzione");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareIsNull() {
      addCriterion("dichiarazione_supplementare is null");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareIsNotNull() {
      addCriterion("dichiarazione_supplementare is not null");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareEqualTo(String value) {
      addCriterion("dichiarazione_supplementare =", value, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareNotEqualTo(String value) {
      addCriterion("dichiarazione_supplementare <>", value, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareGreaterThan(String value) {
      addCriterion("dichiarazione_supplementare >", value, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareGreaterThanOrEqualTo(String value) {
      addCriterion("dichiarazione_supplementare >=", value, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareLessThan(String value) {
      addCriterion("dichiarazione_supplementare <", value, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareLessThanOrEqualTo(String value) {
      addCriterion("dichiarazione_supplementare <=", value, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareLike(String value) {
      addCriterion("dichiarazione_supplementare like", value, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareNotLike(String value) {
      addCriterion("dichiarazione_supplementare not like", value, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareIn(List<String> values) {
      addCriterion("dichiarazione_supplementare in", values, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareNotIn(List<String> values) {
      addCriterion("dichiarazione_supplementare not in", values, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareBetween(String value1, String value2) {
      addCriterion("dichiarazione_supplementare between", value1, value2, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareNotBetween(String value1, String value2) {
      addCriterion("dichiarazione_supplementare not between", value1, value2, "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaIsNull() {
      addCriterion("id_richiesta is null");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaIsNotNull() {
      addCriterion("id_richiesta is not null");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaEqualTo(Long value) {
      addCriterion("id_richiesta =", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaNotEqualTo(Long value) {
      addCriterion("id_richiesta <>", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaGreaterThan(Long value) {
      addCriterion("id_richiesta >", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaGreaterThanOrEqualTo(Long value) {
      addCriterion("id_richiesta >=", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaLessThan(Long value) {
      addCriterion("id_richiesta <", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaLessThanOrEqualTo(Long value) {
      addCriterion("id_richiesta <=", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaIn(List<Long> values) {
      addCriterion("id_richiesta in", values, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaNotIn(List<Long> values) {
      addCriterion("id_richiesta not in", values, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaBetween(Long value1, Long value2) {
      addCriterion("id_richiesta between", value1, value2, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaNotBetween(Long value1, Long value2) {
      addCriterion("id_richiesta not between", value1, value2, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoIsNull() {
      addCriterion("id_tipo_certificato is null");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoIsNotNull() {
      addCriterion("id_tipo_certificato is not null");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoEqualTo(Long value) {
      addCriterion("id_tipo_certificato =", value, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoNotEqualTo(Long value) {
      addCriterion("id_tipo_certificato <>", value, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoGreaterThan(Long value) {
      addCriterion("id_tipo_certificato >", value, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoGreaterThanOrEqualTo(Long value) {
      addCriterion("id_tipo_certificato >=", value, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoLessThan(Long value) {
      addCriterion("id_tipo_certificato <", value, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoLessThanOrEqualTo(Long value) {
      addCriterion("id_tipo_certificato <=", value, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoIn(List<Long> values) {
      addCriterion("id_tipo_certificato in", values, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoNotIn(List<Long> values) {
      addCriterion("id_tipo_certificato not in", values, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoBetween(Long value1, Long value2) {
      addCriterion("id_tipo_certificato between", value1, value2, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdTipoCertificatoNotBetween(Long value1, Long value2) {
      addCriterion("id_tipo_certificato not between", value1, value2, "idTipoCertificato");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreIsNull() {
      addCriterion("id_ispettore is null");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreIsNotNull() {
      addCriterion("id_ispettore is not null");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreEqualTo(Long value) {
      addCriterion("id_ispettore =", value, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreNotEqualTo(Long value) {
      addCriterion("id_ispettore <>", value, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreGreaterThan(Long value) {
      addCriterion("id_ispettore >", value, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreGreaterThanOrEqualTo(Long value) {
      addCriterion("id_ispettore >=", value, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreLessThan(Long value) {
      addCriterion("id_ispettore <", value, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreLessThanOrEqualTo(Long value) {
      addCriterion("id_ispettore <=", value, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreIn(List<Long> values) {
      addCriterion("id_ispettore in", values, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreNotIn(List<Long> values) {
      addCriterion("id_ispettore not in", values, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreBetween(Long value1, Long value2) {
      addCriterion("id_ispettore between", value1, value2, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andIdIspettoreNotBetween(Long value1, Long value2) {
      addCriterion("id_ispettore not between", value1, value2, "idIspettore");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoIsNull() {
      addCriterion("nome_file_allegato is null");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoIsNotNull() {
      addCriterion("nome_file_allegato is not null");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoEqualTo(String value) {
      addCriterion("nome_file_allegato =", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoNotEqualTo(String value) {
      addCriterion("nome_file_allegato <>", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoGreaterThan(String value) {
      addCriterion("nome_file_allegato >", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoGreaterThanOrEqualTo(String value) {
      addCriterion("nome_file_allegato >=", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoLessThan(String value) {
      addCriterion("nome_file_allegato <", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoLessThanOrEqualTo(String value) {
      addCriterion("nome_file_allegato <=", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoLike(String value) {
      addCriterion("nome_file_allegato like", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoNotLike(String value) {
      addCriterion("nome_file_allegato not like", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoIn(List<String> values) {
      addCriterion("nome_file_allegato in", values, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoNotIn(List<String> values) {
      addCriterion("nome_file_allegato not in", values, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoBetween(String value1, String value2) {
      addCriterion("nome_file_allegato between", value1, value2, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoNotBetween(String value1, String value2) {
      addCriterion("nome_file_allegato not between", value1, value2, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNoteIsNull() {
      addCriterion("note is null");
      return (Criteria) this;
    }

    public Criteria andNoteIsNotNull() {
      addCriterion("note is not null");
      return (Criteria) this;
    }

    public Criteria andNoteEqualTo(String value) {
      addCriterion("note =", value, "note");
      return (Criteria) this;
    }

    public Criteria andNoteNotEqualTo(String value) {
      addCriterion("note <>", value, "note");
      return (Criteria) this;
    }

    public Criteria andNoteGreaterThan(String value) {
      addCriterion("note >", value, "note");
      return (Criteria) this;
    }

    public Criteria andNoteGreaterThanOrEqualTo(String value) {
      addCriterion("note >=", value, "note");
      return (Criteria) this;
    }

    public Criteria andNoteLessThan(String value) {
      addCriterion("note <", value, "note");
      return (Criteria) this;
    }

    public Criteria andNoteLessThanOrEqualTo(String value) {
      addCriterion("note <=", value, "note");
      return (Criteria) this;
    }

    public Criteria andNoteLike(String value) {
      addCriterion("note like", value, "note");
      return (Criteria) this;
    }

    public Criteria andNoteNotLike(String value) {
      addCriterion("note not like", value, "note");
      return (Criteria) this;
    }

    public Criteria andNoteIn(List<String> values) {
      addCriterion("note in", values, "note");
      return (Criteria) this;
    }

    public Criteria andNoteNotIn(List<String> values) {
      addCriterion("note not in", values, "note");
      return (Criteria) this;
    }

    public Criteria andNoteBetween(String value1, String value2) {
      addCriterion("note between", value1, value2, "note");
      return (Criteria) this;
    }

    public Criteria andNoteNotBetween(String value1, String value2) {
      addCriterion("note not between", value1, value2, "note");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertIsNull() {
      addCriterion("id_utente_insert is null");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertIsNotNull() {
      addCriterion("id_utente_insert is not null");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertEqualTo(Long value) {
      addCriterion("id_utente_insert =", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertNotEqualTo(Long value) {
      addCriterion("id_utente_insert <>", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertGreaterThan(Long value) {
      addCriterion("id_utente_insert >", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertGreaterThanOrEqualTo(Long value) {
      addCriterion("id_utente_insert >=", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertLessThan(Long value) {
      addCriterion("id_utente_insert <", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertLessThanOrEqualTo(Long value) {
      addCriterion("id_utente_insert <=", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertIn(List<Long> values) {
      addCriterion("id_utente_insert in", values, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertNotIn(List<Long> values) {
      addCriterion("id_utente_insert not in", values, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertBetween(Long value1, Long value2) {
      addCriterion("id_utente_insert between", value1, value2, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertNotBetween(Long value1, Long value2) {
      addCriterion("id_utente_insert not between", value1, value2, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertIsNull() {
      addCriterion("data_insert is null");
      return (Criteria) this;
    }

    public Criteria andDataInsertIsNotNull() {
      addCriterion("data_insert is not null");
      return (Criteria) this;
    }

    public Criteria andDataInsertEqualTo(Date value) {
      addCriterion("data_insert =", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertNotEqualTo(Date value) {
      addCriterion("data_insert <>", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertGreaterThan(Date value) {
      addCriterion("data_insert >", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertGreaterThanOrEqualTo(Date value) {
      addCriterion("data_insert >=", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertLessThan(Date value) {
      addCriterion("data_insert <", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertLessThanOrEqualTo(Date value) {
      addCriterion("data_insert <=", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertIn(List<Date> values) {
      addCriterion("data_insert in", values, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertNotIn(List<Date> values) {
      addCriterion("data_insert not in", values, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertBetween(Date value1, Date value2) {
      addCriterion("data_insert between", value1, value2, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertNotBetween(Date value1, Date value2) {
      addCriterion("data_insert not between", value1, value2, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateIsNull() {
      addCriterion("id_utente_update is null");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateIsNotNull() {
      addCriterion("id_utente_update is not null");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateEqualTo(Long value) {
      addCriterion("id_utente_update =", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateNotEqualTo(Long value) {
      addCriterion("id_utente_update <>", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateGreaterThan(Long value) {
      addCriterion("id_utente_update >", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateGreaterThanOrEqualTo(Long value) {
      addCriterion("id_utente_update >=", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateLessThan(Long value) {
      addCriterion("id_utente_update <", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateLessThanOrEqualTo(Long value) {
      addCriterion("id_utente_update <=", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateIn(List<Long> values) {
      addCriterion("id_utente_update in", values, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateNotIn(List<Long> values) {
      addCriterion("id_utente_update not in", values, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateBetween(Long value1, Long value2) {
      addCriterion("id_utente_update between", value1, value2, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateNotBetween(Long value1, Long value2) {
      addCriterion("id_utente_update not between", value1, value2, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateIsNull() {
      addCriterion("data_update is null");
      return (Criteria) this;
    }

    public Criteria andDataUpdateIsNotNull() {
      addCriterion("data_update is not null");
      return (Criteria) this;
    }

    public Criteria andDataUpdateEqualTo(Date value) {
      addCriterion("data_update =", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateNotEqualTo(Date value) {
      addCriterion("data_update <>", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateGreaterThan(Date value) {
      addCriterion("data_update >", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateGreaterThanOrEqualTo(Date value) {
      addCriterion("data_update >=", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateLessThan(Date value) {
      addCriterion("data_update <", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateLessThanOrEqualTo(Date value) {
      addCriterion("data_update <=", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateIn(List<Date> values) {
      addCriterion("data_update in", values, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateNotIn(List<Date> values) {
      addCriterion("data_update not in", values, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateBetween(Date value1, Date value2) {
      addCriterion("data_update between", value1, value2, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateNotBetween(Date value1, Date value2) {
      addCriterion("data_update not between", value1, value2, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneIsNull() {
      addCriterion("id_comune_esecuzione is null");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneIsNotNull() {
      addCriterion("id_comune_esecuzione is not null");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneEqualTo(Long value) {
      addCriterion("id_comune_esecuzione =", value, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneNotEqualTo(Long value) {
      addCriterion("id_comune_esecuzione <>", value, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneGreaterThan(Long value) {
      addCriterion("id_comune_esecuzione >", value, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneGreaterThanOrEqualTo(Long value) {
      addCriterion("id_comune_esecuzione >=", value, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneLessThan(Long value) {
      addCriterion("id_comune_esecuzione <", value, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneLessThanOrEqualTo(Long value) {
      addCriterion("id_comune_esecuzione <=", value, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneIn(List<Long> values) {
      addCriterion("id_comune_esecuzione in", values, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneNotIn(List<Long> values) {
      addCriterion("id_comune_esecuzione not in", values, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneBetween(Long value1, Long value2) {
      addCriterion("id_comune_esecuzione between", value1, value2, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdComuneEsecuzioneNotBetween(Long value1, Long value2) {
      addCriterion("id_comune_esecuzione not between", value1, value2, "idComuneEsecuzione");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioIsNull() {
      addCriterion("id_tipo_imballaggio is null");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioIsNotNull() {
      addCriterion("id_tipo_imballaggio is not null");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioEqualTo(Long value) {
      addCriterion("id_tipo_imballaggio =", value, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioNotEqualTo(Long value) {
      addCriterion("id_tipo_imballaggio <>", value, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioGreaterThan(Long value) {
      addCriterion("id_tipo_imballaggio >", value, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioGreaterThanOrEqualTo(Long value) {
      addCriterion("id_tipo_imballaggio >=", value, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioLessThan(Long value) {
      addCriterion("id_tipo_imballaggio <", value, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioLessThanOrEqualTo(Long value) {
      addCriterion("id_tipo_imballaggio <=", value, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioIn(List<Long> values) {
      addCriterion("id_tipo_imballaggio in", values, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioNotIn(List<Long> values) {
      addCriterion("id_tipo_imballaggio not in", values, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioBetween(Long value1, Long value2) {
      addCriterion("id_tipo_imballaggio between", value1, value2, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andIdTipoImballaggioNotBetween(Long value1, Long value2) {
      addCriterion("id_tipo_imballaggio not between", value1, value2, "idTipoImballaggio");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeIsNull() {
      addCriterion("copia_conforme is null");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeIsNotNull() {
      addCriterion("copia_conforme is not null");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeEqualTo(Boolean value) {
      addCriterion("copia_conforme =", value, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeNotEqualTo(Boolean value) {
      addCriterion("copia_conforme <>", value, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeGreaterThan(Boolean value) {
      addCriterion("copia_conforme >", value, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeGreaterThanOrEqualTo(Boolean value) {
      addCriterion("copia_conforme >=", value, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeLessThan(Boolean value) {
      addCriterion("copia_conforme <", value, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeLessThanOrEqualTo(Boolean value) {
      addCriterion("copia_conforme <=", value, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeIn(List<Boolean> values) {
      addCriterion("copia_conforme in", values, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeNotIn(List<Boolean> values) {
      addCriterion("copia_conforme not in", values, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeBetween(Boolean value1, Boolean value2) {
      addCriterion("copia_conforme between", value1, value2, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andCopiaConformeNotBetween(Boolean value1, Boolean value2) {
      addCriterion("copia_conforme not between", value1, value2, "copiaConforme");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigIsNull() {
      addCriterion("conforme_certif_orig is null");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigIsNotNull() {
      addCriterion("conforme_certif_orig is not null");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigEqualTo(Boolean value) {
      addCriterion("conforme_certif_orig =", value, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigNotEqualTo(Boolean value) {
      addCriterion("conforme_certif_orig <>", value, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigGreaterThan(Boolean value) {
      addCriterion("conforme_certif_orig >", value, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigGreaterThanOrEqualTo(Boolean value) {
      addCriterion("conforme_certif_orig >=", value, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigLessThan(Boolean value) {
      addCriterion("conforme_certif_orig <", value, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigLessThanOrEqualTo(Boolean value) {
      addCriterion("conforme_certif_orig <=", value, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigIn(List<Boolean> values) {
      addCriterion("conforme_certif_orig in", values, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigNotIn(List<Boolean> values) {
      addCriterion("conforme_certif_orig not in", values, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigBetween(Boolean value1, Boolean value2) {
      addCriterion("conforme_certif_orig between", value1, value2, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andConformeCertifOrigNotBetween(Boolean value1, Boolean value2) {
      addCriterion("conforme_certif_orig not between", value1, value2, "conformeCertifOrig");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareIsNull() {
      addCriterion("ispezione_supplementare is null");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareIsNotNull() {
      addCriterion("ispezione_supplementare is not null");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareEqualTo(Boolean value) {
      addCriterion("ispezione_supplementare =", value, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareNotEqualTo(Boolean value) {
      addCriterion("ispezione_supplementare <>", value, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareGreaterThan(Boolean value) {
      addCriterion("ispezione_supplementare >", value, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareGreaterThanOrEqualTo(Boolean value) {
      addCriterion("ispezione_supplementare >=", value, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareLessThan(Boolean value) {
      addCriterion("ispezione_supplementare <", value, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareLessThanOrEqualTo(Boolean value) {
      addCriterion("ispezione_supplementare <=", value, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareIn(List<Boolean> values) {
      addCriterion("ispezione_supplementare in", values, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareNotIn(List<Boolean> values) {
      addCriterion("ispezione_supplementare not in", values, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareBetween(Boolean value1, Boolean value2) {
      addCriterion("ispezione_supplementare between", value1, value2, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andIspezioneSupplementareNotBetween(Boolean value1, Boolean value2) {
      addCriterion("ispezione_supplementare not between", value1, value2, "ispezioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoLikeInsensitive(String value) {
      addCriterion("upper(numero_certificato) like", value.toUpperCase(), "numeroCertificato");
      return (Criteria) this;
    }

    public Criteria andNumeroCertificatoManualeLikeInsensitive(String value) {
      addCriterion("upper(numero_certificato_manuale) like", value.toUpperCase(), "numeroCertificatoManuale");
      return (Criteria) this;
    }

    public Criteria andDichiarazioneSupplementareLikeInsensitive(String value) {
      addCriterion("upper(dichiarazione_supplementare) like", value.toUpperCase(), "dichiarazioneSupplementare");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoLikeInsensitive(String value) {
      addCriterion("upper(nome_file_allegato) like", value.toUpperCase(), "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNoteLikeInsensitive(String value) {
      addCriterion("upper(note) like", value.toUpperCase(), "note");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_t_certificato
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_t_certificato
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 14 19:16:19 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}