package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarTEsitoExample extends GenericExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public CarTEsitoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdEsitoIsNull() {
			addCriterion("id_esito is null");
			return (Criteria) this;
		}

		public Criteria andIdEsitoIsNotNull() {
			addCriterion("id_esito is not null");
			return (Criteria) this;
		}

		public Criteria andIdEsitoEqualTo(Long value) {
			addCriterion("id_esito =", value, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoNotEqualTo(Long value) {
			addCriterion("id_esito <>", value, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoGreaterThan(Long value) {
			addCriterion("id_esito >", value, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoGreaterThanOrEqualTo(Long value) {
			addCriterion("id_esito >=", value, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoLessThan(Long value) {
			addCriterion("id_esito <", value, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoLessThanOrEqualTo(Long value) {
			addCriterion("id_esito <=", value, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoIn(List<Long> values) {
			addCriterion("id_esito in", values, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoNotIn(List<Long> values) {
			addCriterion("id_esito not in", values, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoBetween(Long value1, Long value2) {
			addCriterion("id_esito between", value1, value2, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdEsitoNotBetween(Long value1, Long value2) {
			addCriterion("id_esito not between", value1, value2, "idEsito");
			return (Criteria) this;
		}

		public Criteria andIdControlloIsNull() {
			addCriterion("id_controllo is null");
			return (Criteria) this;
		}

		public Criteria andIdControlloIsNotNull() {
			addCriterion("id_controllo is not null");
			return (Criteria) this;
		}

		public Criteria andIdControlloEqualTo(Long value) {
			addCriterion("id_controllo =", value, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloNotEqualTo(Long value) {
			addCriterion("id_controllo <>", value, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloGreaterThan(Long value) {
			addCriterion("id_controllo >", value, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloGreaterThanOrEqualTo(Long value) {
			addCriterion("id_controllo >=", value, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloLessThan(Long value) {
			addCriterion("id_controllo <", value, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloLessThanOrEqualTo(Long value) {
			addCriterion("id_controllo <=", value, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloIn(List<Long> values) {
			addCriterion("id_controllo in", values, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloNotIn(List<Long> values) {
			addCriterion("id_controllo not in", values, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloBetween(Long value1, Long value2) {
			addCriterion("id_controllo between", value1, value2, "idControllo");
			return (Criteria) this;
		}

		public Criteria andIdControlloNotBetween(Long value1, Long value2) {
			addCriterion("id_controllo not between", value1, value2, "idControllo");
			return (Criteria) this;
		}

		public Criteria andCognomeRespIsNull() {
			addCriterion("cognome_resp is null");
			return (Criteria) this;
		}

		public Criteria andCognomeRespIsNotNull() {
			addCriterion("cognome_resp is not null");
			return (Criteria) this;
		}

		public Criteria andCognomeRespEqualTo(String value) {
			addCriterion("cognome_resp =", value, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespNotEqualTo(String value) {
			addCriterion("cognome_resp <>", value, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespGreaterThan(String value) {
			addCriterion("cognome_resp >", value, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespGreaterThanOrEqualTo(String value) {
			addCriterion("cognome_resp >=", value, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespLessThan(String value) {
			addCriterion("cognome_resp <", value, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespLessThanOrEqualTo(String value) {
			addCriterion("cognome_resp <=", value, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespLike(String value) {
			addCriterion("cognome_resp like", value, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespNotLike(String value) {
			addCriterion("cognome_resp not like", value, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespIn(List<String> values) {
			addCriterion("cognome_resp in", values, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespNotIn(List<String> values) {
			addCriterion("cognome_resp not in", values, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespBetween(String value1, String value2) {
			addCriterion("cognome_resp between", value1, value2, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andCognomeRespNotBetween(String value1, String value2) {
			addCriterion("cognome_resp not between", value1, value2, "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespIsNull() {
			addCriterion("nome_resp is null");
			return (Criteria) this;
		}

		public Criteria andNomeRespIsNotNull() {
			addCriterion("nome_resp is not null");
			return (Criteria) this;
		}

		public Criteria andNomeRespEqualTo(String value) {
			addCriterion("nome_resp =", value, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespNotEqualTo(String value) {
			addCriterion("nome_resp <>", value, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespGreaterThan(String value) {
			addCriterion("nome_resp >", value, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespGreaterThanOrEqualTo(String value) {
			addCriterion("nome_resp >=", value, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespLessThan(String value) {
			addCriterion("nome_resp <", value, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespLessThanOrEqualTo(String value) {
			addCriterion("nome_resp <=", value, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespLike(String value) {
			addCriterion("nome_resp like", value, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespNotLike(String value) {
			addCriterion("nome_resp not like", value, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespIn(List<String> values) {
			addCriterion("nome_resp in", values, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespNotIn(List<String> values) {
			addCriterion("nome_resp not in", values, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespBetween(String value1, String value2) {
			addCriterion("nome_resp between", value1, value2, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespNotBetween(String value1, String value2) {
			addCriterion("nome_resp not between", value1, value2, "nomeResp");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleIsNull() {
			addCriterion("data_chiusura_verbale is null");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleIsNotNull() {
			addCriterion("data_chiusura_verbale is not null");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleEqualTo(Date value) {
			addCriterion("data_chiusura_verbale =", value, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleNotEqualTo(Date value) {
			addCriterion("data_chiusura_verbale <>", value, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleGreaterThan(Date value) {
			addCriterion("data_chiusura_verbale >", value, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleGreaterThanOrEqualTo(Date value) {
			addCriterion("data_chiusura_verbale >=", value, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleLessThan(Date value) {
			addCriterion("data_chiusura_verbale <", value, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleLessThanOrEqualTo(Date value) {
			addCriterion("data_chiusura_verbale <=", value, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleIn(List<Date> values) {
			addCriterion("data_chiusura_verbale in", values, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleNotIn(List<Date> values) {
			addCriterion("data_chiusura_verbale not in", values, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleBetween(Date value1, Date value2) {
			addCriterion("data_chiusura_verbale between", value1, value2, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andDataChiusuraVerbaleNotBetween(Date value1, Date value2) {
			addCriterion("data_chiusura_verbale not between", value1, value2, "dataChiusuraVerbale");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneIsNull() {
			addCriterion("note_dichiarazione is null");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneIsNotNull() {
			addCriterion("note_dichiarazione is not null");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneEqualTo(String value) {
			addCriterion("note_dichiarazione =", value, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneNotEqualTo(String value) {
			addCriterion("note_dichiarazione <>", value, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneGreaterThan(String value) {
			addCriterion("note_dichiarazione >", value, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneGreaterThanOrEqualTo(String value) {
			addCriterion("note_dichiarazione >=", value, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneLessThan(String value) {
			addCriterion("note_dichiarazione <", value, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneLessThanOrEqualTo(String value) {
			addCriterion("note_dichiarazione <=", value, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneLike(String value) {
			addCriterion("note_dichiarazione like", value, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneNotLike(String value) {
			addCriterion("note_dichiarazione not like", value, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneIn(List<String> values) {
			addCriterion("note_dichiarazione in", values, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneNotIn(List<String> values) {
			addCriterion("note_dichiarazione not in", values, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneBetween(String value1, String value2) {
			addCriterion("note_dichiarazione between", value1, value2, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneNotBetween(String value1, String value2) {
			addCriterion("note_dichiarazione not between", value1, value2, "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleIsNull() {
			addCriterion("email_invio_verbale is null");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleIsNotNull() {
			addCriterion("email_invio_verbale is not null");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleEqualTo(String value) {
			addCriterion("email_invio_verbale =", value, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleNotEqualTo(String value) {
			addCriterion("email_invio_verbale <>", value, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleGreaterThan(String value) {
			addCriterion("email_invio_verbale >", value, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleGreaterThanOrEqualTo(String value) {
			addCriterion("email_invio_verbale >=", value, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleLessThan(String value) {
			addCriterion("email_invio_verbale <", value, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleLessThanOrEqualTo(String value) {
			addCriterion("email_invio_verbale <=", value, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleLike(String value) {
			addCriterion("email_invio_verbale like", value, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleNotLike(String value) {
			addCriterion("email_invio_verbale not like", value, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleIn(List<String> values) {
			addCriterion("email_invio_verbale in", values, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleNotIn(List<String> values) {
			addCriterion("email_invio_verbale not in", values, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleBetween(String value1, String value2) {
			addCriterion("email_invio_verbale between", value1, value2, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleNotBetween(String value1, String value2) {
			addCriterion("email_invio_verbale not between", value1, value2, "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaIsNull() {
			addCriterion("fl_irregolarita is null");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaIsNotNull() {
			addCriterion("fl_irregolarita is not null");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaEqualTo(String value) {
			addCriterion("fl_irregolarita =", value, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaNotEqualTo(String value) {
			addCriterion("fl_irregolarita <>", value, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaGreaterThan(String value) {
			addCriterion("fl_irregolarita >", value, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaGreaterThanOrEqualTo(String value) {
			addCriterion("fl_irregolarita >=", value, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaLessThan(String value) {
			addCriterion("fl_irregolarita <", value, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaLessThanOrEqualTo(String value) {
			addCriterion("fl_irregolarita <=", value, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaLike(String value) {
			addCriterion("fl_irregolarita like", value, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaNotLike(String value) {
			addCriterion("fl_irregolarita not like", value, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaIn(List<String> values) {
			addCriterion("fl_irregolarita in", values, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaNotIn(List<String> values) {
			addCriterion("fl_irregolarita not in", values, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaBetween(String value1, String value2) {
			addCriterion("fl_irregolarita between", value1, value2, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaNotBetween(String value1, String value2) {
			addCriterion("fl_irregolarita not between", value1, value2, "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaIsNull() {
			addCriterion("note_irregolarita is null");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaIsNotNull() {
			addCriterion("note_irregolarita is not null");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaEqualTo(String value) {
			addCriterion("note_irregolarita =", value, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaNotEqualTo(String value) {
			addCriterion("note_irregolarita <>", value, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaGreaterThan(String value) {
			addCriterion("note_irregolarita >", value, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaGreaterThanOrEqualTo(String value) {
			addCriterion("note_irregolarita >=", value, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaLessThan(String value) {
			addCriterion("note_irregolarita <", value, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaLessThanOrEqualTo(String value) {
			addCriterion("note_irregolarita <=", value, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaLike(String value) {
			addCriterion("note_irregolarita like", value, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaNotLike(String value) {
			addCriterion("note_irregolarita not like", value, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaIn(List<String> values) {
			addCriterion("note_irregolarita in", values, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaNotIn(List<String> values) {
			addCriterion("note_irregolarita not in", values, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaBetween(String value1, String value2) {
			addCriterion("note_irregolarita between", value1, value2, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaNotBetween(String value1, String value2) {
			addCriterion("note_irregolarita not between", value1, value2, "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlEsitoIsNull() {
			addCriterion("fl_esito is null");
			return (Criteria) this;
		}

		public Criteria andFlEsitoIsNotNull() {
			addCriterion("fl_esito is not null");
			return (Criteria) this;
		}

		public Criteria andFlEsitoEqualTo(String value) {
			addCriterion("fl_esito =", value, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoNotEqualTo(String value) {
			addCriterion("fl_esito <>", value, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoGreaterThan(String value) {
			addCriterion("fl_esito >", value, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoGreaterThanOrEqualTo(String value) {
			addCriterion("fl_esito >=", value, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoLessThan(String value) {
			addCriterion("fl_esito <", value, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoLessThanOrEqualTo(String value) {
			addCriterion("fl_esito <=", value, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoLike(String value) {
			addCriterion("fl_esito like", value, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoNotLike(String value) {
			addCriterion("fl_esito not like", value, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoIn(List<String> values) {
			addCriterion("fl_esito in", values, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoNotIn(List<String> values) {
			addCriterion("fl_esito not in", values, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoBetween(String value1, String value2) {
			addCriterion("fl_esito between", value1, value2, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoNotBetween(String value1, String value2) {
			addCriterion("fl_esito not between", value1, value2, "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoIsNull() {
			addCriterion("fl_esito_passaporto is null");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoIsNotNull() {
			addCriterion("fl_esito_passaporto is not null");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoEqualTo(String value) {
			addCriterion("fl_esito_passaporto =", value, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoNotEqualTo(String value) {
			addCriterion("fl_esito_passaporto <>", value, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoGreaterThan(String value) {
			addCriterion("fl_esito_passaporto >", value, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoGreaterThanOrEqualTo(String value) {
			addCriterion("fl_esito_passaporto >=", value, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoLessThan(String value) {
			addCriterion("fl_esito_passaporto <", value, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoLessThanOrEqualTo(String value) {
			addCriterion("fl_esito_passaporto <=", value, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoLike(String value) {
			addCriterion("fl_esito_passaporto like", value, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoNotLike(String value) {
			addCriterion("fl_esito_passaporto not like", value, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoIn(List<String> values) {
			addCriterion("fl_esito_passaporto in", values, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoNotIn(List<String> values) {
			addCriterion("fl_esito_passaporto not in", values, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoBetween(String value1, String value2) {
			addCriterion("fl_esito_passaporto between", value1, value2, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoNotBetween(String value1, String value2) {
			addCriterion("fl_esito_passaporto not between", value1, value2, "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoIsNull() {
			addCriterion("id_utente_inserimento is null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoIsNotNull() {
			addCriterion("id_utente_inserimento is not null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoEqualTo(Long value) {
			addCriterion("id_utente_inserimento =", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoNotEqualTo(Long value) {
			addCriterion("id_utente_inserimento <>", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoGreaterThan(Long value) {
			addCriterion("id_utente_inserimento >", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoGreaterThanOrEqualTo(Long value) {
			addCriterion("id_utente_inserimento >=", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoLessThan(Long value) {
			addCriterion("id_utente_inserimento <", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoLessThanOrEqualTo(Long value) {
			addCriterion("id_utente_inserimento <=", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoIn(List<Long> values) {
			addCriterion("id_utente_inserimento in", values, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoNotIn(List<Long> values) {
			addCriterion("id_utente_inserimento not in", values, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoBetween(Long value1, Long value2) {
			addCriterion("id_utente_inserimento between", value1, value2, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoNotBetween(Long value1, Long value2) {
			addCriterion("id_utente_inserimento not between", value1, value2, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoIsNull() {
			addCriterion("data_inserimento is null");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoIsNotNull() {
			addCriterion("data_inserimento is not null");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoEqualTo(Date value) {
			addCriterion("data_inserimento =", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoNotEqualTo(Date value) {
			addCriterion("data_inserimento <>", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoGreaterThan(Date value) {
			addCriterion("data_inserimento >", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoGreaterThanOrEqualTo(Date value) {
			addCriterion("data_inserimento >=", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoLessThan(Date value) {
			addCriterion("data_inserimento <", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoLessThanOrEqualTo(Date value) {
			addCriterion("data_inserimento <=", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoIn(List<Date> values) {
			addCriterion("data_inserimento in", values, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoNotIn(List<Date> values) {
			addCriterion("data_inserimento not in", values, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoBetween(Date value1, Date value2) {
			addCriterion("data_inserimento between", value1, value2, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoNotBetween(Date value1, Date value2) {
			addCriterion("data_inserimento not between", value1, value2, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIsNull() {
			addCriterion("id_utente_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIsNotNull() {
			addCriterion("id_utente_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento =", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento <>", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoGreaterThan(Long value) {
			addCriterion("id_utente_aggiornamento >", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoGreaterThanOrEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento >=", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoLessThan(Long value) {
			addCriterion("id_utente_aggiornamento <", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoLessThanOrEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento <=", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIn(List<Long> values) {
			addCriterion("id_utente_aggiornamento in", values, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotIn(List<Long> values) {
			addCriterion("id_utente_aggiornamento not in", values, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoBetween(Long value1, Long value2) {
			addCriterion("id_utente_aggiornamento between", value1, value2, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotBetween(Long value1, Long value2) {
			addCriterion("id_utente_aggiornamento not between", value1, value2, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNull() {
			addCriterion("data_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNotNull() {
			addCriterion("data_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoEqualTo(Date value) {
			addCriterion("data_aggiornamento =", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotEqualTo(Date value) {
			addCriterion("data_aggiornamento <>", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThan(Date value) {
			addCriterion("data_aggiornamento >", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThanOrEqualTo(Date value) {
			addCriterion("data_aggiornamento >=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThan(Date value) {
			addCriterion("data_aggiornamento <", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThanOrEqualTo(Date value) {
			addCriterion("data_aggiornamento <=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIn(List<Date> values) {
			addCriterion("data_aggiornamento in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotIn(List<Date> values) {
			addCriterion("data_aggiornamento not in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoBetween(Date value1, Date value2) {
			addCriterion("data_aggiornamento between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotBetween(Date value1, Date value2) {
			addCriterion("data_aggiornamento not between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaIsNull() {
			addCriterion("nome_file_stampa is null");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaIsNotNull() {
			addCriterion("nome_file_stampa is not null");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaEqualTo(String value) {
			addCriterion("nome_file_stampa =", value, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaNotEqualTo(String value) {
			addCriterion("nome_file_stampa <>", value, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaGreaterThan(String value) {
			addCriterion("nome_file_stampa >", value, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaGreaterThanOrEqualTo(String value) {
			addCriterion("nome_file_stampa >=", value, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaLessThan(String value) {
			addCriterion("nome_file_stampa <", value, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaLessThanOrEqualTo(String value) {
			addCriterion("nome_file_stampa <=", value, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaLike(String value) {
			addCriterion("nome_file_stampa like", value, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaNotLike(String value) {
			addCriterion("nome_file_stampa not like", value, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaIn(List<String> values) {
			addCriterion("nome_file_stampa in", values, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaNotIn(List<String> values) {
			addCriterion("nome_file_stampa not in", values, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaBetween(String value1, String value2) {
			addCriterion("nome_file_stampa between", value1, value2, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaNotBetween(String value1, String value2) {
			addCriterion("nome_file_stampa not between", value1, value2, "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloIsNull() {
			addCriterion("note_esito_controllo is null");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloIsNotNull() {
			addCriterion("note_esito_controllo is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloEqualTo(String value) {
			addCriterion("note_esito_controllo =", value, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloNotEqualTo(String value) {
			addCriterion("note_esito_controllo <>", value, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloGreaterThan(String value) {
			addCriterion("note_esito_controllo >", value, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloGreaterThanOrEqualTo(String value) {
			addCriterion("note_esito_controllo >=", value, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloLessThan(String value) {
			addCriterion("note_esito_controllo <", value, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloLessThanOrEqualTo(String value) {
			addCriterion("note_esito_controllo <=", value, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloLike(String value) {
			addCriterion("note_esito_controllo like", value, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloNotLike(String value) {
			addCriterion("note_esito_controllo not like", value, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloIn(List<String> values) {
			addCriterion("note_esito_controllo in", values, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloNotIn(List<String> values) {
			addCriterion("note_esito_controllo not in", values, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloBetween(String value1, String value2) {
			addCriterion("note_esito_controllo between", value1, value2, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloNotBetween(String value1, String value2) {
			addCriterion("note_esito_controllo not between", value1, value2, "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeIsNull() {
			addCriterion("fl_misura_ufficiale is null");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeIsNotNull() {
			addCriterion("fl_misura_ufficiale is not null");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeEqualTo(String value) {
			addCriterion("fl_misura_ufficiale =", value, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeNotEqualTo(String value) {
			addCriterion("fl_misura_ufficiale <>", value, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeGreaterThan(String value) {
			addCriterion("fl_misura_ufficiale >", value, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeGreaterThanOrEqualTo(String value) {
			addCriterion("fl_misura_ufficiale >=", value, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeLessThan(String value) {
			addCriterion("fl_misura_ufficiale <", value, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeLessThanOrEqualTo(String value) {
			addCriterion("fl_misura_ufficiale <=", value, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeLike(String value) {
			addCriterion("fl_misura_ufficiale like", value, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeNotLike(String value) {
			addCriterion("fl_misura_ufficiale not like", value, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeIn(List<String> values) {
			addCriterion("fl_misura_ufficiale in", values, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeNotIn(List<String> values) {
			addCriterion("fl_misura_ufficiale not in", values, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeBetween(String value1, String value2) {
			addCriterion("fl_misura_ufficiale between", value1, value2, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeNotBetween(String value1, String value2) {
			addCriterion("fl_misura_ufficiale not between", value1, value2, "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeIsNull() {
			addCriterion("num_misura_ufficiale is null");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeIsNotNull() {
			addCriterion("num_misura_ufficiale is not null");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeEqualTo(String value) {
			addCriterion("num_misura_ufficiale =", value, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeNotEqualTo(String value) {
			addCriterion("num_misura_ufficiale <>", value, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeGreaterThan(String value) {
			addCriterion("num_misura_ufficiale >", value, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeGreaterThanOrEqualTo(String value) {
			addCriterion("num_misura_ufficiale >=", value, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeLessThan(String value) {
			addCriterion("num_misura_ufficiale <", value, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeLessThanOrEqualTo(String value) {
			addCriterion("num_misura_ufficiale <=", value, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeLike(String value) {
			addCriterion("num_misura_ufficiale like", value, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeNotLike(String value) {
			addCriterion("num_misura_ufficiale not like", value, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeIn(List<String> values) {
			addCriterion("num_misura_ufficiale in", values, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeNotIn(List<String> values) {
			addCriterion("num_misura_ufficiale not in", values, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeBetween(String value1, String value2) {
			addCriterion("num_misura_ufficiale between", value1, value2, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeNotBetween(String value1, String value2) {
			addCriterion("num_misura_ufficiale not between", value1, value2, "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeIsNull() {
			addCriterion("fl_motivo_misura_ufficiale is null");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeIsNotNull() {
			addCriterion("fl_motivo_misura_ufficiale is not null");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeEqualTo(String value) {
			addCriterion("fl_motivo_misura_ufficiale =", value, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeNotEqualTo(String value) {
			addCriterion("fl_motivo_misura_ufficiale <>", value, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeGreaterThan(String value) {
			addCriterion("fl_motivo_misura_ufficiale >", value, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeGreaterThanOrEqualTo(String value) {
			addCriterion("fl_motivo_misura_ufficiale >=", value, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeLessThan(String value) {
			addCriterion("fl_motivo_misura_ufficiale <", value, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeLessThanOrEqualTo(String value) {
			addCriterion("fl_motivo_misura_ufficiale <=", value, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeLike(String value) {
			addCriterion("fl_motivo_misura_ufficiale like", value, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeNotLike(String value) {
			addCriterion("fl_motivo_misura_ufficiale not like", value, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeIn(List<String> values) {
			addCriterion("fl_motivo_misura_ufficiale in", values, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeNotIn(List<String> values) {
			addCriterion("fl_motivo_misura_ufficiale not in", values, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeBetween(String value1, String value2) {
			addCriterion("fl_motivo_misura_ufficiale between", value1, value2, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeNotBetween(String value1, String value2) {
			addCriterion("fl_motivo_misura_ufficiale not between", value1, value2, "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeIsNull() {
			addCriterion("note_motivo_misura_ufficiale is null");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeIsNotNull() {
			addCriterion("note_motivo_misura_ufficiale is not null");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeEqualTo(String value) {
			addCriterion("note_motivo_misura_ufficiale =", value, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeNotEqualTo(String value) {
			addCriterion("note_motivo_misura_ufficiale <>", value, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeGreaterThan(String value) {
			addCriterion("note_motivo_misura_ufficiale >", value, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeGreaterThanOrEqualTo(String value) {
			addCriterion("note_motivo_misura_ufficiale >=", value, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeLessThan(String value) {
			addCriterion("note_motivo_misura_ufficiale <", value, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeLessThanOrEqualTo(String value) {
			addCriterion("note_motivo_misura_ufficiale <=", value, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeLike(String value) {
			addCriterion("note_motivo_misura_ufficiale like", value, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeNotLike(String value) {
			addCriterion("note_motivo_misura_ufficiale not like", value, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeIn(List<String> values) {
			addCriterion("note_motivo_misura_ufficiale in", values, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeNotIn(List<String> values) {
			addCriterion("note_motivo_misura_ufficiale not in", values, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeBetween(String value1, String value2) {
			addCriterion("note_motivo_misura_ufficiale between", value1, value2, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeNotBetween(String value1, String value2) {
			addCriterion("note_motivo_misura_ufficiale not between", value1, value2, "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaIsNull() {
			addCriterion("fl_sanzione_amministrativa_emessa is null");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaIsNotNull() {
			addCriterion("fl_sanzione_amministrativa_emessa is not null");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaEqualTo(String value) {
			addCriterion("fl_sanzione_amministrativa_emessa =", value, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaNotEqualTo(String value) {
			addCriterion("fl_sanzione_amministrativa_emessa <>", value, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaGreaterThan(String value) {
			addCriterion("fl_sanzione_amministrativa_emessa >", value, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaGreaterThanOrEqualTo(String value) {
			addCriterion("fl_sanzione_amministrativa_emessa >=", value, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaLessThan(String value) {
			addCriterion("fl_sanzione_amministrativa_emessa <", value, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaLessThanOrEqualTo(String value) {
			addCriterion("fl_sanzione_amministrativa_emessa <=", value, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaLike(String value) {
			addCriterion("fl_sanzione_amministrativa_emessa like", value, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaNotLike(String value) {
			addCriterion("fl_sanzione_amministrativa_emessa not like", value, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaIn(List<String> values) {
			addCriterion("fl_sanzione_amministrativa_emessa in", values, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaNotIn(List<String> values) {
			addCriterion("fl_sanzione_amministrativa_emessa not in", values, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaBetween(String value1, String value2) {
			addCriterion("fl_sanzione_amministrativa_emessa between", value1, value2, "flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaNotBetween(String value1, String value2) {
			addCriterion("fl_sanzione_amministrativa_emessa not between", value1, value2,
					"flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaIsNull() {
			addCriterion("note_sanzione_amministrativa_emessa is null");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaIsNotNull() {
			addCriterion("note_sanzione_amministrativa_emessa is not null");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaEqualTo(String value) {
			addCriterion("note_sanzione_amministrativa_emessa =", value, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaNotEqualTo(String value) {
			addCriterion("note_sanzione_amministrativa_emessa <>", value, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaGreaterThan(String value) {
			addCriterion("note_sanzione_amministrativa_emessa >", value, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaGreaterThanOrEqualTo(String value) {
			addCriterion("note_sanzione_amministrativa_emessa >=", value, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaLessThan(String value) {
			addCriterion("note_sanzione_amministrativa_emessa <", value, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaLessThanOrEqualTo(String value) {
			addCriterion("note_sanzione_amministrativa_emessa <=", value, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaLike(String value) {
			addCriterion("note_sanzione_amministrativa_emessa like", value, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaNotLike(String value) {
			addCriterion("note_sanzione_amministrativa_emessa not like", value, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaIn(List<String> values) {
			addCriterion("note_sanzione_amministrativa_emessa in", values, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaNotIn(List<String> values) {
			addCriterion("note_sanzione_amministrativa_emessa not in", values, "noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaBetween(String value1, String value2) {
			addCriterion("note_sanzione_amministrativa_emessa between", value1, value2,
					"noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaNotBetween(String value1, String value2) {
			addCriterion("note_sanzione_amministrativa_emessa not between", value1, value2,
					"noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniIsNull() {
			addCriterion("fl_prescrizioni is null");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniIsNotNull() {
			addCriterion("fl_prescrizioni is not null");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniEqualTo(String value) {
			addCriterion("fl_prescrizioni =", value, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniNotEqualTo(String value) {
			addCriterion("fl_prescrizioni <>", value, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniGreaterThan(String value) {
			addCriterion("fl_prescrizioni >", value, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniGreaterThanOrEqualTo(String value) {
			addCriterion("fl_prescrizioni >=", value, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniLessThan(String value) {
			addCriterion("fl_prescrizioni <", value, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniLessThanOrEqualTo(String value) {
			addCriterion("fl_prescrizioni <=", value, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniLike(String value) {
			addCriterion("fl_prescrizioni like", value, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniNotLike(String value) {
			addCriterion("fl_prescrizioni not like", value, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniIn(List<String> values) {
			addCriterion("fl_prescrizioni in", values, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniNotIn(List<String> values) {
			addCriterion("fl_prescrizioni not in", values, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniBetween(String value1, String value2) {
			addCriterion("fl_prescrizioni between", value1, value2, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniNotBetween(String value1, String value2) {
			addCriterion("fl_prescrizioni not between", value1, value2, "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniIsNull() {
			addCriterion("note_prescrizioni is null");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniIsNotNull() {
			addCriterion("note_prescrizioni is not null");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniEqualTo(String value) {
			addCriterion("note_prescrizioni =", value, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniNotEqualTo(String value) {
			addCriterion("note_prescrizioni <>", value, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniGreaterThan(String value) {
			addCriterion("note_prescrizioni >", value, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniGreaterThanOrEqualTo(String value) {
			addCriterion("note_prescrizioni >=", value, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniLessThan(String value) {
			addCriterion("note_prescrizioni <", value, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniLessThanOrEqualTo(String value) {
			addCriterion("note_prescrizioni <=", value, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniLike(String value) {
			addCriterion("note_prescrizioni like", value, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniNotLike(String value) {
			addCriterion("note_prescrizioni not like", value, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniIn(List<String> values) {
			addCriterion("note_prescrizioni in", values, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniNotIn(List<String> values) {
			addCriterion("note_prescrizioni not in", values, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniBetween(String value1, String value2) {
			addCriterion("note_prescrizioni between", value1, value2, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniNotBetween(String value1, String value2) {
			addCriterion("note_prescrizioni not between", value1, value2, "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaIsNull() {
			addCriterion("fl_sanzione_amministrativa_proposta is null");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaIsNotNull() {
			addCriterion("fl_sanzione_amministrativa_proposta is not null");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaEqualTo(String value) {
			addCriterion("fl_sanzione_amministrativa_proposta =", value, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaNotEqualTo(String value) {
			addCriterion("fl_sanzione_amministrativa_proposta <>", value, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaGreaterThan(String value) {
			addCriterion("fl_sanzione_amministrativa_proposta >", value, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaGreaterThanOrEqualTo(String value) {
			addCriterion("fl_sanzione_amministrativa_proposta >=", value, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaLessThan(String value) {
			addCriterion("fl_sanzione_amministrativa_proposta <", value, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaLessThanOrEqualTo(String value) {
			addCriterion("fl_sanzione_amministrativa_proposta <=", value, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaLike(String value) {
			addCriterion("fl_sanzione_amministrativa_proposta like", value, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaNotLike(String value) {
			addCriterion("fl_sanzione_amministrativa_proposta not like", value, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaIn(List<String> values) {
			addCriterion("fl_sanzione_amministrativa_proposta in", values, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaNotIn(List<String> values) {
			addCriterion("fl_sanzione_amministrativa_proposta not in", values, "flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaBetween(String value1, String value2) {
			addCriterion("fl_sanzione_amministrativa_proposta between", value1, value2,
					"flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaNotBetween(String value1, String value2) {
			addCriterion("fl_sanzione_amministrativa_proposta not between", value1, value2,
					"flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaIsNull() {
			addCriterion("note_sanzione_amministrativa_proposta is null");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaIsNotNull() {
			addCriterion("note_sanzione_amministrativa_proposta is not null");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaEqualTo(String value) {
			addCriterion("note_sanzione_amministrativa_proposta =", value, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaNotEqualTo(String value) {
			addCriterion("note_sanzione_amministrativa_proposta <>", value, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaGreaterThan(String value) {
			addCriterion("note_sanzione_amministrativa_proposta >", value, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaGreaterThanOrEqualTo(String value) {
			addCriterion("note_sanzione_amministrativa_proposta >=", value, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaLessThan(String value) {
			addCriterion("note_sanzione_amministrativa_proposta <", value, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaLessThanOrEqualTo(String value) {
			addCriterion("note_sanzione_amministrativa_proposta <=", value, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaLike(String value) {
			addCriterion("note_sanzione_amministrativa_proposta like", value, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaNotLike(String value) {
			addCriterion("note_sanzione_amministrativa_proposta not like", value, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaIn(List<String> values) {
			addCriterion("note_sanzione_amministrativa_proposta in", values, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaNotIn(List<String> values) {
			addCriterion("note_sanzione_amministrativa_proposta not in", values, "noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaBetween(String value1, String value2) {
			addCriterion("note_sanzione_amministrativa_proposta between", value1, value2,
					"noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaNotBetween(String value1, String value2) {
			addCriterion("note_sanzione_amministrativa_proposta not between", value1, value2,
					"noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andCognomeRespLikeInsensitive(String value) {
			addCriterion("upper(cognome_resp) like", value.toUpperCase(), "cognomeResp");
			return (Criteria) this;
		}

		public Criteria andNomeRespLikeInsensitive(String value) {
			addCriterion("upper(nome_resp) like", value.toUpperCase(), "nomeResp");
			return (Criteria) this;
		}

		public Criteria andNoteDichiarazioneLikeInsensitive(String value) {
			addCriterion("upper(note_dichiarazione) like", value.toUpperCase(), "noteDichiarazione");
			return (Criteria) this;
		}

		public Criteria andNoteLikeInsensitive(String value) {
			addCriterion("upper(note) like", value.toUpperCase(), "note");
			return (Criteria) this;
		}

		public Criteria andEmailInvioVerbaleLikeInsensitive(String value) {
			addCriterion("upper(email_invio_verbale) like", value.toUpperCase(), "emailInvioVerbale");
			return (Criteria) this;
		}

		public Criteria andFlIrregolaritaLikeInsensitive(String value) {
			addCriterion("upper(fl_irregolarita) like", value.toUpperCase(), "flIrregolarita");
			return (Criteria) this;
		}

		public Criteria andNoteIrregolaritaLikeInsensitive(String value) {
			addCriterion("upper(note_irregolarita) like", value.toUpperCase(), "noteIrregolarita");
			return (Criteria) this;
		}

		public Criteria andFlEsitoLikeInsensitive(String value) {
			addCriterion("upper(fl_esito) like", value.toUpperCase(), "flEsito");
			return (Criteria) this;
		}

		public Criteria andFlEsitoPassaportoLikeInsensitive(String value) {
			addCriterion("upper(fl_esito_passaporto) like", value.toUpperCase(), "flEsitoPassaporto");
			return (Criteria) this;
		}

		public Criteria andNomeFileStampaLikeInsensitive(String value) {
			addCriterion("upper(nome_file_stampa) like", value.toUpperCase(), "nomeFileStampa");
			return (Criteria) this;
		}

		public Criteria andNoteEsitoControlloLikeInsensitive(String value) {
			addCriterion("upper(note_esito_controllo) like", value.toUpperCase(), "noteEsitoControllo");
			return (Criteria) this;
		}

		public Criteria andFlMisuraUfficialeLikeInsensitive(String value) {
			addCriterion("upper(fl_misura_ufficiale) like", value.toUpperCase(), "flMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNumMisuraUfficialeLikeInsensitive(String value) {
			addCriterion("upper(num_misura_ufficiale) like", value.toUpperCase(), "numMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlMotivoMisuraUfficialeLikeInsensitive(String value) {
			addCriterion("upper(fl_motivo_misura_ufficiale) like", value.toUpperCase(), "flMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andNoteMotivoMisuraUfficialeLikeInsensitive(String value) {
			addCriterion("upper(note_motivo_misura_ufficiale) like", value.toUpperCase(), "noteMotivoMisuraUfficiale");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaEmessaLikeInsensitive(String value) {
			addCriterion("upper(fl_sanzione_amministrativa_emessa) like", value.toUpperCase(),
					"flSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaEmessaLikeInsensitive(String value) {
			addCriterion("upper(note_sanzione_amministrativa_emessa) like", value.toUpperCase(),
					"noteSanzioneAmministrativaEmessa");
			return (Criteria) this;
		}

		public Criteria andFlPrescrizioniLikeInsensitive(String value) {
			addCriterion("upper(fl_prescrizioni) like", value.toUpperCase(), "flPrescrizioni");
			return (Criteria) this;
		}

		public Criteria andNotePrescrizioniLikeInsensitive(String value) {
			addCriterion("upper(note_prescrizioni) like", value.toUpperCase(), "notePrescrizioni");
			return (Criteria) this;
		}

		public Criteria andFlSanzioneAmministrativaPropostaLikeInsensitive(String value) {
			addCriterion("upper(fl_sanzione_amministrativa_proposta) like", value.toUpperCase(),
					"flSanzioneAmministrativaProposta");
			return (Criteria) this;
		}

		public Criteria andNoteSanzioneAmministrativaPropostaLikeInsensitive(String value) {
			addCriterion("upper(note_sanzione_amministrativa_proposta) like", value.toUpperCase(),
					"noteSanzioneAmministrativaProposta");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_t_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_t_esito
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 24 08:56:53 CET 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}