package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;
import java.util.Date;

public class CarTEsito extends BaseDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.id_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private Long idEsito;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.id_controllo
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private Long idControllo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.cognome_resp
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String cognomeResp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.nome_resp
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String nomeResp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.data_chiusura_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private Date dataChiusuraVerbale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.note_dichiarazione
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String noteDichiarazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.note
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.email_invio_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String emailInvioVerbale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.fl_irregolarita
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String flIrregolarita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.note_irregolarita
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String noteIrregolarita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.fl_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String flEsito;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.fl_esito_passaporto
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String flEsitoPassaporto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.id_utente_inserimento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private Long idUtenteInserimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.data_inserimento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private Date dataInserimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.id_utente_aggiornamento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.data_aggiornamento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.nome_file_stampa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String nomeFileStampa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.note_esito_controllo
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String noteEsitoControllo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.fl_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String flMisuraUfficiale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.num_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String numMisuraUfficiale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.fl_motivo_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String flMotivoMisuraUfficiale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.note_motivo_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String noteMotivoMisuraUfficiale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.fl_sanzione_amministrativa_emessa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String flSanzioneAmministrativaEmessa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.note_sanzione_amministrativa_emessa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String noteSanzioneAmministrativaEmessa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.fl_prescrizioni
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String flPrescrizioni;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.note_prescrizioni
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String notePrescrizioni;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.fl_sanzione_amministrativa_proposta
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String flSanzioneAmministrativaProposta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.note_sanzione_amministrativa_proposta
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private String noteSanzioneAmministrativaProposta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_esito.stampa_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	private byte[] stampaVerbale;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.id_esito
	 * @return  the value of caronte.car_t_esito.id_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Long getIdEsito() {
		return idEsito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.id_esito
	 * @param idEsito  the value for caronte.car_t_esito.id_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setIdEsito(Long idEsito) {
		this.idEsito = idEsito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.id_controllo
	 * @return  the value of caronte.car_t_esito.id_controllo
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Long getIdControllo() {
		return idControllo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.id_controllo
	 * @param idControllo  the value for caronte.car_t_esito.id_controllo
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setIdControllo(Long idControllo) {
		this.idControllo = idControllo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.cognome_resp
	 * @return  the value of caronte.car_t_esito.cognome_resp
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getCognomeResp() {
		return cognomeResp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.cognome_resp
	 * @param cognomeResp  the value for caronte.car_t_esito.cognome_resp
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setCognomeResp(String cognomeResp) {
		this.cognomeResp = cognomeResp == null ? null : cognomeResp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.nome_resp
	 * @return  the value of caronte.car_t_esito.nome_resp
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNomeResp() {
		return nomeResp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.nome_resp
	 * @param nomeResp  the value for caronte.car_t_esito.nome_resp
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNomeResp(String nomeResp) {
		this.nomeResp = nomeResp == null ? null : nomeResp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.data_chiusura_verbale
	 * @return  the value of caronte.car_t_esito.data_chiusura_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Date getDataChiusuraVerbale() {
		return dataChiusuraVerbale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.data_chiusura_verbale
	 * @param dataChiusuraVerbale  the value for caronte.car_t_esito.data_chiusura_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setDataChiusuraVerbale(Date dataChiusuraVerbale) {
		this.dataChiusuraVerbale = dataChiusuraVerbale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.note_dichiarazione
	 * @return  the value of caronte.car_t_esito.note_dichiarazione
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNoteDichiarazione() {
		return noteDichiarazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.note_dichiarazione
	 * @param noteDichiarazione  the value for caronte.car_t_esito.note_dichiarazione
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNoteDichiarazione(String noteDichiarazione) {
		this.noteDichiarazione = noteDichiarazione == null ? null : noteDichiarazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.note
	 * @return  the value of caronte.car_t_esito.note
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.note
	 * @param note  the value for caronte.car_t_esito.note
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.email_invio_verbale
	 * @return  the value of caronte.car_t_esito.email_invio_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getEmailInvioVerbale() {
		return emailInvioVerbale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.email_invio_verbale
	 * @param emailInvioVerbale  the value for caronte.car_t_esito.email_invio_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setEmailInvioVerbale(String emailInvioVerbale) {
		this.emailInvioVerbale = emailInvioVerbale == null ? null : emailInvioVerbale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.fl_irregolarita
	 * @return  the value of caronte.car_t_esito.fl_irregolarita
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getFlIrregolarita() {
		return flIrregolarita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.fl_irregolarita
	 * @param flIrregolarita  the value for caronte.car_t_esito.fl_irregolarita
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setFlIrregolarita(String flIrregolarita) {
		this.flIrregolarita = flIrregolarita == null ? null : flIrregolarita.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.note_irregolarita
	 * @return  the value of caronte.car_t_esito.note_irregolarita
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNoteIrregolarita() {
		return noteIrregolarita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.note_irregolarita
	 * @param noteIrregolarita  the value for caronte.car_t_esito.note_irregolarita
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNoteIrregolarita(String noteIrregolarita) {
		this.noteIrregolarita = noteIrregolarita == null ? null : noteIrregolarita.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.fl_esito
	 * @return  the value of caronte.car_t_esito.fl_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getFlEsito() {
		return flEsito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.fl_esito
	 * @param flEsito  the value for caronte.car_t_esito.fl_esito
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setFlEsito(String flEsito) {
		this.flEsito = flEsito == null ? null : flEsito.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.fl_esito_passaporto
	 * @return  the value of caronte.car_t_esito.fl_esito_passaporto
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getFlEsitoPassaporto() {
		return flEsitoPassaporto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.fl_esito_passaporto
	 * @param flEsitoPassaporto  the value for caronte.car_t_esito.fl_esito_passaporto
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setFlEsitoPassaporto(String flEsitoPassaporto) {
		this.flEsitoPassaporto = flEsitoPassaporto == null ? null : flEsitoPassaporto.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.id_utente_inserimento
	 * @return  the value of caronte.car_t_esito.id_utente_inserimento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Long getIdUtenteInserimento() {
		return idUtenteInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.id_utente_inserimento
	 * @param idUtenteInserimento  the value for caronte.car_t_esito.id_utente_inserimento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setIdUtenteInserimento(Long idUtenteInserimento) {
		this.idUtenteInserimento = idUtenteInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.data_inserimento
	 * @return  the value of caronte.car_t_esito.data_inserimento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Date getDataInserimento() {
		return dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.data_inserimento
	 * @param dataInserimento  the value for caronte.car_t_esito.data_inserimento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.id_utente_aggiornamento
	 * @return  the value of caronte.car_t_esito.id_utente_aggiornamento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.id_utente_aggiornamento
	 * @param idUtenteAggiornamento  the value for caronte.car_t_esito.id_utente_aggiornamento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.data_aggiornamento
	 * @return  the value of caronte.car_t_esito.data_aggiornamento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.data_aggiornamento
	 * @param dataAggiornamento  the value for caronte.car_t_esito.data_aggiornamento
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.nome_file_stampa
	 * @return  the value of caronte.car_t_esito.nome_file_stampa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNomeFileStampa() {
		return nomeFileStampa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.nome_file_stampa
	 * @param nomeFileStampa  the value for caronte.car_t_esito.nome_file_stampa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNomeFileStampa(String nomeFileStampa) {
		this.nomeFileStampa = nomeFileStampa == null ? null : nomeFileStampa.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.note_esito_controllo
	 * @return  the value of caronte.car_t_esito.note_esito_controllo
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNoteEsitoControllo() {
		return noteEsitoControllo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.note_esito_controllo
	 * @param noteEsitoControllo  the value for caronte.car_t_esito.note_esito_controllo
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNoteEsitoControllo(String noteEsitoControllo) {
		this.noteEsitoControllo = noteEsitoControllo == null ? null : noteEsitoControllo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.fl_misura_ufficiale
	 * @return  the value of caronte.car_t_esito.fl_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getFlMisuraUfficiale() {
		return flMisuraUfficiale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.fl_misura_ufficiale
	 * @param flMisuraUfficiale  the value for caronte.car_t_esito.fl_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setFlMisuraUfficiale(String flMisuraUfficiale) {
		this.flMisuraUfficiale = flMisuraUfficiale == null ? null : flMisuraUfficiale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.num_misura_ufficiale
	 * @return  the value of caronte.car_t_esito.num_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNumMisuraUfficiale() {
		return numMisuraUfficiale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.num_misura_ufficiale
	 * @param numMisuraUfficiale  the value for caronte.car_t_esito.num_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNumMisuraUfficiale(String numMisuraUfficiale) {
		this.numMisuraUfficiale = numMisuraUfficiale == null ? null : numMisuraUfficiale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.fl_motivo_misura_ufficiale
	 * @return  the value of caronte.car_t_esito.fl_motivo_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getFlMotivoMisuraUfficiale() {
		return flMotivoMisuraUfficiale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.fl_motivo_misura_ufficiale
	 * @param flMotivoMisuraUfficiale  the value for caronte.car_t_esito.fl_motivo_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setFlMotivoMisuraUfficiale(String flMotivoMisuraUfficiale) {
		this.flMotivoMisuraUfficiale = flMotivoMisuraUfficiale == null ? null : flMotivoMisuraUfficiale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.note_motivo_misura_ufficiale
	 * @return  the value of caronte.car_t_esito.note_motivo_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNoteMotivoMisuraUfficiale() {
		return noteMotivoMisuraUfficiale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.note_motivo_misura_ufficiale
	 * @param noteMotivoMisuraUfficiale  the value for caronte.car_t_esito.note_motivo_misura_ufficiale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNoteMotivoMisuraUfficiale(String noteMotivoMisuraUfficiale) {
		this.noteMotivoMisuraUfficiale = noteMotivoMisuraUfficiale == null ? null : noteMotivoMisuraUfficiale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.fl_sanzione_amministrativa_emessa
	 * @return  the value of caronte.car_t_esito.fl_sanzione_amministrativa_emessa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getFlSanzioneAmministrativaEmessa() {
		return flSanzioneAmministrativaEmessa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.fl_sanzione_amministrativa_emessa
	 * @param flSanzioneAmministrativaEmessa  the value for caronte.car_t_esito.fl_sanzione_amministrativa_emessa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setFlSanzioneAmministrativaEmessa(String flSanzioneAmministrativaEmessa) {
		this.flSanzioneAmministrativaEmessa = flSanzioneAmministrativaEmessa == null ? null
				: flSanzioneAmministrativaEmessa.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.note_sanzione_amministrativa_emessa
	 * @return  the value of caronte.car_t_esito.note_sanzione_amministrativa_emessa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNoteSanzioneAmministrativaEmessa() {
		return noteSanzioneAmministrativaEmessa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.note_sanzione_amministrativa_emessa
	 * @param noteSanzioneAmministrativaEmessa  the value for caronte.car_t_esito.note_sanzione_amministrativa_emessa
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNoteSanzioneAmministrativaEmessa(String noteSanzioneAmministrativaEmessa) {
		this.noteSanzioneAmministrativaEmessa = noteSanzioneAmministrativaEmessa == null ? null
				: noteSanzioneAmministrativaEmessa.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.fl_prescrizioni
	 * @return  the value of caronte.car_t_esito.fl_prescrizioni
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getFlPrescrizioni() {
		return flPrescrizioni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.fl_prescrizioni
	 * @param flPrescrizioni  the value for caronte.car_t_esito.fl_prescrizioni
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setFlPrescrizioni(String flPrescrizioni) {
		this.flPrescrizioni = flPrescrizioni == null ? null : flPrescrizioni.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.note_prescrizioni
	 * @return  the value of caronte.car_t_esito.note_prescrizioni
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNotePrescrizioni() {
		return notePrescrizioni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.note_prescrizioni
	 * @param notePrescrizioni  the value for caronte.car_t_esito.note_prescrizioni
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNotePrescrizioni(String notePrescrizioni) {
		this.notePrescrizioni = notePrescrizioni == null ? null : notePrescrizioni.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.fl_sanzione_amministrativa_proposta
	 * @return  the value of caronte.car_t_esito.fl_sanzione_amministrativa_proposta
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getFlSanzioneAmministrativaProposta() {
		return flSanzioneAmministrativaProposta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.fl_sanzione_amministrativa_proposta
	 * @param flSanzioneAmministrativaProposta  the value for caronte.car_t_esito.fl_sanzione_amministrativa_proposta
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setFlSanzioneAmministrativaProposta(String flSanzioneAmministrativaProposta) {
		this.flSanzioneAmministrativaProposta = flSanzioneAmministrativaProposta == null ? null
				: flSanzioneAmministrativaProposta.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.note_sanzione_amministrativa_proposta
	 * @return  the value of caronte.car_t_esito.note_sanzione_amministrativa_proposta
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public String getNoteSanzioneAmministrativaProposta() {
		return noteSanzioneAmministrativaProposta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.note_sanzione_amministrativa_proposta
	 * @param noteSanzioneAmministrativaProposta  the value for caronte.car_t_esito.note_sanzione_amministrativa_proposta
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setNoteSanzioneAmministrativaProposta(String noteSanzioneAmministrativaProposta) {
		this.noteSanzioneAmministrativaProposta = noteSanzioneAmministrativaProposta == null ? null
				: noteSanzioneAmministrativaProposta.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_esito.stampa_verbale
	 * @return  the value of caronte.car_t_esito.stampa_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public byte[] getStampaVerbale() {
		return stampaVerbale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_esito.stampa_verbale
	 * @param stampaVerbale  the value for caronte.car_t_esito.stampa_verbale
	 * @mbg.generated  Wed Apr 14 12:10:52 CEST 2021
	 */
	public void setStampaVerbale(byte[] stampaVerbale) {
		this.stampaVerbale = stampaVerbale;
	}
}