package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;
import java.util.Date;

public class CarTAllegatoControllo extends BaseDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.id_allegato_controllo
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private Long idAllegatoControllo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.nome_file
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private String nomeFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.desc_allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private String descAllegato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.id_tipo_allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private Long idTipoAllegato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.id_controllo
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private Long idControllo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.id_utente_inserimento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private Long idUtenteInserimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.data_inserimento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private Date dataInserimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.id_utente_aggiornamento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.data_aggiornamento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caronte.car_t_allegato_controllo.allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	private byte[] allegato;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.id_allegato_controllo
	 * @return  the value of caronte.car_t_allegato_controllo.id_allegato_controllo
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public Long getIdAllegatoControllo() {
		return idAllegatoControllo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.id_allegato_controllo
	 * @param idAllegatoControllo  the value for caronte.car_t_allegato_controllo.id_allegato_controllo
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setIdAllegatoControllo(Long idAllegatoControllo) {
		this.idAllegatoControllo = idAllegatoControllo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.nome_file
	 * @return  the value of caronte.car_t_allegato_controllo.nome_file
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public String getNomeFile() {
		return nomeFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.nome_file
	 * @param nomeFile  the value for caronte.car_t_allegato_controllo.nome_file
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setNomeFile(String nomeFile) {
		this.nomeFile = nomeFile == null ? null : nomeFile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.desc_allegato
	 * @return  the value of caronte.car_t_allegato_controllo.desc_allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public String getDescAllegato() {
		return descAllegato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.desc_allegato
	 * @param descAllegato  the value for caronte.car_t_allegato_controllo.desc_allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setDescAllegato(String descAllegato) {
		this.descAllegato = descAllegato == null ? null : descAllegato.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.id_tipo_allegato
	 * @return  the value of caronte.car_t_allegato_controllo.id_tipo_allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public Long getIdTipoAllegato() {
		return idTipoAllegato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.id_tipo_allegato
	 * @param idTipoAllegato  the value for caronte.car_t_allegato_controllo.id_tipo_allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setIdTipoAllegato(Long idTipoAllegato) {
		this.idTipoAllegato = idTipoAllegato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.id_controllo
	 * @return  the value of caronte.car_t_allegato_controllo.id_controllo
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public Long getIdControllo() {
		return idControllo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.id_controllo
	 * @param idControllo  the value for caronte.car_t_allegato_controllo.id_controllo
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setIdControllo(Long idControllo) {
		this.idControllo = idControllo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.id_utente_inserimento
	 * @return  the value of caronte.car_t_allegato_controllo.id_utente_inserimento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public Long getIdUtenteInserimento() {
		return idUtenteInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.id_utente_inserimento
	 * @param idUtenteInserimento  the value for caronte.car_t_allegato_controllo.id_utente_inserimento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setIdUtenteInserimento(Long idUtenteInserimento) {
		this.idUtenteInserimento = idUtenteInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.data_inserimento
	 * @return  the value of caronte.car_t_allegato_controllo.data_inserimento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public Date getDataInserimento() {
		return dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.data_inserimento
	 * @param dataInserimento  the value for caronte.car_t_allegato_controllo.data_inserimento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.id_utente_aggiornamento
	 * @return  the value of caronte.car_t_allegato_controllo.id_utente_aggiornamento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.id_utente_aggiornamento
	 * @param idUtenteAggiornamento  the value for caronte.car_t_allegato_controllo.id_utente_aggiornamento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.data_aggiornamento
	 * @return  the value of caronte.car_t_allegato_controllo.data_aggiornamento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.data_aggiornamento
	 * @param dataAggiornamento  the value for caronte.car_t_allegato_controllo.data_aggiornamento
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caronte.car_t_allegato_controllo.allegato
	 * @return  the value of caronte.car_t_allegato_controllo.allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public byte[] getAllegato() {
		return allegato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column caronte.car_t_allegato_controllo.allegato
	 * @param allegato  the value for caronte.car_t_allegato_controllo.allegato
	 * @mbg.generated  Mon Dec 28 16:07:44 CET 2020
	 */
	public void setAllegato(byte[] allegato) {
		this.allegato = allegato;
	}
}