package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarTDatiDomandaExample extends GenericExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public CarTDatiDomandaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdDatiDomandaIsNull() {
			addCriterion("id_dati_domanda is null");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaIsNotNull() {
			addCriterion("id_dati_domanda is not null");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaEqualTo(Long value) {
			addCriterion("id_dati_domanda =", value, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaNotEqualTo(Long value) {
			addCriterion("id_dati_domanda <>", value, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaGreaterThan(Long value) {
			addCriterion("id_dati_domanda >", value, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaGreaterThanOrEqualTo(Long value) {
			addCriterion("id_dati_domanda >=", value, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaLessThan(Long value) {
			addCriterion("id_dati_domanda <", value, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaLessThanOrEqualTo(Long value) {
			addCriterion("id_dati_domanda <=", value, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaIn(List<Long> values) {
			addCriterion("id_dati_domanda in", values, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaNotIn(List<Long> values) {
			addCriterion("id_dati_domanda not in", values, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaBetween(Long value1, Long value2) {
			addCriterion("id_dati_domanda between", value1, value2, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDatiDomandaNotBetween(Long value1, Long value2) {
			addCriterion("id_dati_domanda not between", value1, value2, "idDatiDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaIsNull() {
			addCriterion("id_domanda is null");
			return (Criteria) this;
		}

		public Criteria andIdDomandaIsNotNull() {
			addCriterion("id_domanda is not null");
			return (Criteria) this;
		}

		public Criteria andIdDomandaEqualTo(Long value) {
			addCriterion("id_domanda =", value, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaNotEqualTo(Long value) {
			addCriterion("id_domanda <>", value, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaGreaterThan(Long value) {
			addCriterion("id_domanda >", value, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaGreaterThanOrEqualTo(Long value) {
			addCriterion("id_domanda >=", value, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaLessThan(Long value) {
			addCriterion("id_domanda <", value, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaLessThanOrEqualTo(Long value) {
			addCriterion("id_domanda <=", value, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaIn(List<Long> values) {
			addCriterion("id_domanda in", values, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaNotIn(List<Long> values) {
			addCriterion("id_domanda not in", values, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaBetween(Long value1, Long value2) {
			addCriterion("id_domanda between", value1, value2, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andIdDomandaNotBetween(Long value1, Long value2) {
			addCriterion("id_domanda not between", value1, value2, "idDomanda");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoIsNull() {
			addCriterion("imp_dato_aggiuntivo is null");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoIsNotNull() {
			addCriterion("imp_dato_aggiuntivo is not null");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoEqualTo(String value) {
			addCriterion("imp_dato_aggiuntivo =", value, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoNotEqualTo(String value) {
			addCriterion("imp_dato_aggiuntivo <>", value, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoGreaterThan(String value) {
			addCriterion("imp_dato_aggiuntivo >", value, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoGreaterThanOrEqualTo(String value) {
			addCriterion("imp_dato_aggiuntivo >=", value, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoLessThan(String value) {
			addCriterion("imp_dato_aggiuntivo <", value, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoLessThanOrEqualTo(String value) {
			addCriterion("imp_dato_aggiuntivo <=", value, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoLike(String value) {
			addCriterion("imp_dato_aggiuntivo like", value, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoNotLike(String value) {
			addCriterion("imp_dato_aggiuntivo not like", value, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoIn(List<String> values) {
			addCriterion("imp_dato_aggiuntivo in", values, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoNotIn(List<String> values) {
			addCriterion("imp_dato_aggiuntivo not in", values, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoBetween(String value1, String value2) {
			addCriterion("imp_dato_aggiuntivo between", value1, value2, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoNotBetween(String value1, String value2) {
			addCriterion("imp_dato_aggiuntivo not between", value1, value2, "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpNoteIsNull() {
			addCriterion("imp_note is null");
			return (Criteria) this;
		}

		public Criteria andImpNoteIsNotNull() {
			addCriterion("imp_note is not null");
			return (Criteria) this;
		}

		public Criteria andImpNoteEqualTo(String value) {
			addCriterion("imp_note =", value, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteNotEqualTo(String value) {
			addCriterion("imp_note <>", value, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteGreaterThan(String value) {
			addCriterion("imp_note >", value, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteGreaterThanOrEqualTo(String value) {
			addCriterion("imp_note >=", value, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteLessThan(String value) {
			addCriterion("imp_note <", value, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteLessThanOrEqualTo(String value) {
			addCriterion("imp_note <=", value, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteLike(String value) {
			addCriterion("imp_note like", value, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteNotLike(String value) {
			addCriterion("imp_note not like", value, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteIn(List<String> values) {
			addCriterion("imp_note in", values, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteNotIn(List<String> values) {
			addCriterion("imp_note not in", values, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteBetween(String value1, String value2) {
			addCriterion("imp_note between", value1, value2, "impNote");
			return (Criteria) this;
		}

		public Criteria andImpNoteNotBetween(String value1, String value2) {
			addCriterion("imp_note not between", value1, value2, "impNote");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoIsNull() {
			addCriterion("exp_dato_aggiuntivo is null");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoIsNotNull() {
			addCriterion("exp_dato_aggiuntivo is not null");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoEqualTo(String value) {
			addCriterion("exp_dato_aggiuntivo =", value, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoNotEqualTo(String value) {
			addCriterion("exp_dato_aggiuntivo <>", value, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoGreaterThan(String value) {
			addCriterion("exp_dato_aggiuntivo >", value, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoGreaterThanOrEqualTo(String value) {
			addCriterion("exp_dato_aggiuntivo >=", value, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoLessThan(String value) {
			addCriterion("exp_dato_aggiuntivo <", value, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoLessThanOrEqualTo(String value) {
			addCriterion("exp_dato_aggiuntivo <=", value, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoLike(String value) {
			addCriterion("exp_dato_aggiuntivo like", value, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoNotLike(String value) {
			addCriterion("exp_dato_aggiuntivo not like", value, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoIn(List<String> values) {
			addCriterion("exp_dato_aggiuntivo in", values, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoNotIn(List<String> values) {
			addCriterion("exp_dato_aggiuntivo not in", values, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoBetween(String value1, String value2) {
			addCriterion("exp_dato_aggiuntivo between", value1, value2, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoNotBetween(String value1, String value2) {
			addCriterion("exp_dato_aggiuntivo not between", value1, value2, "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpNoteIsNull() {
			addCriterion("exp_note is null");
			return (Criteria) this;
		}

		public Criteria andExpNoteIsNotNull() {
			addCriterion("exp_note is not null");
			return (Criteria) this;
		}

		public Criteria andExpNoteEqualTo(String value) {
			addCriterion("exp_note =", value, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteNotEqualTo(String value) {
			addCriterion("exp_note <>", value, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteGreaterThan(String value) {
			addCriterion("exp_note >", value, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteGreaterThanOrEqualTo(String value) {
			addCriterion("exp_note >=", value, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteLessThan(String value) {
			addCriterion("exp_note <", value, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteLessThanOrEqualTo(String value) {
			addCriterion("exp_note <=", value, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteLike(String value) {
			addCriterion("exp_note like", value, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteNotLike(String value) {
			addCriterion("exp_note not like", value, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteIn(List<String> values) {
			addCriterion("exp_note in", values, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteNotIn(List<String> values) {
			addCriterion("exp_note not in", values, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteBetween(String value1, String value2) {
			addCriterion("exp_note between", value1, value2, "expNote");
			return (Criteria) this;
		}

		public Criteria andExpNoteNotBetween(String value1, String value2) {
			addCriterion("exp_note not between", value1, value2, "expNote");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoIsNull() {
			addCriterion("viv_dato_aggiuntivo is null");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoIsNotNull() {
			addCriterion("viv_dato_aggiuntivo is not null");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoEqualTo(String value) {
			addCriterion("viv_dato_aggiuntivo =", value, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoNotEqualTo(String value) {
			addCriterion("viv_dato_aggiuntivo <>", value, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoGreaterThan(String value) {
			addCriterion("viv_dato_aggiuntivo >", value, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoGreaterThanOrEqualTo(String value) {
			addCriterion("viv_dato_aggiuntivo >=", value, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoLessThan(String value) {
			addCriterion("viv_dato_aggiuntivo <", value, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoLessThanOrEqualTo(String value) {
			addCriterion("viv_dato_aggiuntivo <=", value, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoLike(String value) {
			addCriterion("viv_dato_aggiuntivo like", value, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoNotLike(String value) {
			addCriterion("viv_dato_aggiuntivo not like", value, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoIn(List<String> values) {
			addCriterion("viv_dato_aggiuntivo in", values, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoNotIn(List<String> values) {
			addCriterion("viv_dato_aggiuntivo not in", values, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoBetween(String value1, String value2) {
			addCriterion("viv_dato_aggiuntivo between", value1, value2, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoNotBetween(String value1, String value2) {
			addCriterion("viv_dato_aggiuntivo not between", value1, value2, "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivNoteIsNull() {
			addCriterion("viv_note is null");
			return (Criteria) this;
		}

		public Criteria andVivNoteIsNotNull() {
			addCriterion("viv_note is not null");
			return (Criteria) this;
		}

		public Criteria andVivNoteEqualTo(String value) {
			addCriterion("viv_note =", value, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteNotEqualTo(String value) {
			addCriterion("viv_note <>", value, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteGreaterThan(String value) {
			addCriterion("viv_note >", value, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteGreaterThanOrEqualTo(String value) {
			addCriterion("viv_note >=", value, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteLessThan(String value) {
			addCriterion("viv_note <", value, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteLessThanOrEqualTo(String value) {
			addCriterion("viv_note <=", value, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteLike(String value) {
			addCriterion("viv_note like", value, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteNotLike(String value) {
			addCriterion("viv_note not like", value, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteIn(List<String> values) {
			addCriterion("viv_note in", values, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteNotIn(List<String> values) {
			addCriterion("viv_note not in", values, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteBetween(String value1, String value2) {
			addCriterion("viv_note between", value1, value2, "vivNote");
			return (Criteria) this;
		}

		public Criteria andVivNoteNotBetween(String value1, String value2) {
			addCriterion("viv_note not between", value1, value2, "vivNote");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoIsNull() {
			addCriterion("pass_dato_aggiuntivo is null");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoIsNotNull() {
			addCriterion("pass_dato_aggiuntivo is not null");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoEqualTo(String value) {
			addCriterion("pass_dato_aggiuntivo =", value, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoNotEqualTo(String value) {
			addCriterion("pass_dato_aggiuntivo <>", value, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoGreaterThan(String value) {
			addCriterion("pass_dato_aggiuntivo >", value, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoGreaterThanOrEqualTo(String value) {
			addCriterion("pass_dato_aggiuntivo >=", value, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoLessThan(String value) {
			addCriterion("pass_dato_aggiuntivo <", value, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoLessThanOrEqualTo(String value) {
			addCriterion("pass_dato_aggiuntivo <=", value, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoLike(String value) {
			addCriterion("pass_dato_aggiuntivo like", value, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoNotLike(String value) {
			addCriterion("pass_dato_aggiuntivo not like", value, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoIn(List<String> values) {
			addCriterion("pass_dato_aggiuntivo in", values, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoNotIn(List<String> values) {
			addCriterion("pass_dato_aggiuntivo not in", values, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoBetween(String value1, String value2) {
			addCriterion("pass_dato_aggiuntivo between", value1, value2, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoNotBetween(String value1, String value2) {
			addCriterion("pass_dato_aggiuntivo not between", value1, value2, "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassNoteIsNull() {
			addCriterion("pass_note is null");
			return (Criteria) this;
		}

		public Criteria andPassNoteIsNotNull() {
			addCriterion("pass_note is not null");
			return (Criteria) this;
		}

		public Criteria andPassNoteEqualTo(String value) {
			addCriterion("pass_note =", value, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteNotEqualTo(String value) {
			addCriterion("pass_note <>", value, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteGreaterThan(String value) {
			addCriterion("pass_note >", value, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteGreaterThanOrEqualTo(String value) {
			addCriterion("pass_note >=", value, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteLessThan(String value) {
			addCriterion("pass_note <", value, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteLessThanOrEqualTo(String value) {
			addCriterion("pass_note <=", value, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteLike(String value) {
			addCriterion("pass_note like", value, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteNotLike(String value) {
			addCriterion("pass_note not like", value, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteIn(List<String> values) {
			addCriterion("pass_note in", values, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteNotIn(List<String> values) {
			addCriterion("pass_note not in", values, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteBetween(String value1, String value2) {
			addCriterion("pass_note between", value1, value2, "passNote");
			return (Criteria) this;
		}

		public Criteria andPassNoteNotBetween(String value1, String value2) {
			addCriterion("pass_note not between", value1, value2, "passNote");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoIsNull() {
			addCriterion("id_utente_inserimento is null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoIsNotNull() {
			addCriterion("id_utente_inserimento is not null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoEqualTo(Long value) {
			addCriterion("id_utente_inserimento =", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoNotEqualTo(Long value) {
			addCriterion("id_utente_inserimento <>", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoGreaterThan(Long value) {
			addCriterion("id_utente_inserimento >", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoGreaterThanOrEqualTo(Long value) {
			addCriterion("id_utente_inserimento >=", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoLessThan(Long value) {
			addCriterion("id_utente_inserimento <", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoLessThanOrEqualTo(Long value) {
			addCriterion("id_utente_inserimento <=", value, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoIn(List<Long> values) {
			addCriterion("id_utente_inserimento in", values, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoNotIn(List<Long> values) {
			addCriterion("id_utente_inserimento not in", values, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoBetween(Long value1, Long value2) {
			addCriterion("id_utente_inserimento between", value1, value2, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteInserimentoNotBetween(Long value1, Long value2) {
			addCriterion("id_utente_inserimento not between", value1, value2, "idUtenteInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoIsNull() {
			addCriterion("data_inserimento is null");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoIsNotNull() {
			addCriterion("data_inserimento is not null");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoEqualTo(Date value) {
			addCriterion("data_inserimento =", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoNotEqualTo(Date value) {
			addCriterion("data_inserimento <>", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoGreaterThan(Date value) {
			addCriterion("data_inserimento >", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoGreaterThanOrEqualTo(Date value) {
			addCriterion("data_inserimento >=", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoLessThan(Date value) {
			addCriterion("data_inserimento <", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoLessThanOrEqualTo(Date value) {
			addCriterion("data_inserimento <=", value, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoIn(List<Date> values) {
			addCriterion("data_inserimento in", values, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoNotIn(List<Date> values) {
			addCriterion("data_inserimento not in", values, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoBetween(Date value1, Date value2) {
			addCriterion("data_inserimento between", value1, value2, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andDataInserimentoNotBetween(Date value1, Date value2) {
			addCriterion("data_inserimento not between", value1, value2, "dataInserimento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIsNull() {
			addCriterion("id_utente_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIsNotNull() {
			addCriterion("id_utente_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento =", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento <>", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoGreaterThan(Long value) {
			addCriterion("id_utente_aggiornamento >", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoGreaterThanOrEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento >=", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoLessThan(Long value) {
			addCriterion("id_utente_aggiornamento <", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoLessThanOrEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento <=", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIn(List<Long> values) {
			addCriterion("id_utente_aggiornamento in", values, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotIn(List<Long> values) {
			addCriterion("id_utente_aggiornamento not in", values, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoBetween(Long value1, Long value2) {
			addCriterion("id_utente_aggiornamento between", value1, value2, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotBetween(Long value1, Long value2) {
			addCriterion("id_utente_aggiornamento not between", value1, value2, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNull() {
			addCriterion("data_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNotNull() {
			addCriterion("data_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoEqualTo(Date value) {
			addCriterion("data_aggiornamento =", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotEqualTo(Date value) {
			addCriterion("data_aggiornamento <>", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThan(Date value) {
			addCriterion("data_aggiornamento >", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThanOrEqualTo(Date value) {
			addCriterion("data_aggiornamento >=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThan(Date value) {
			addCriterion("data_aggiornamento <", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThanOrEqualTo(Date value) {
			addCriterion("data_aggiornamento <=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIn(List<Date> values) {
			addCriterion("data_aggiornamento in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotIn(List<Date> values) {
			addCriterion("data_aggiornamento not in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoBetween(Date value1, Date value2) {
			addCriterion("data_aggiornamento between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotBetween(Date value1, Date value2) {
			addCriterion("data_aggiornamento not between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andNomeFileIsNull() {
			addCriterion("nome_file is null");
			return (Criteria) this;
		}

		public Criteria andNomeFileIsNotNull() {
			addCriterion("nome_file is not null");
			return (Criteria) this;
		}

		public Criteria andNomeFileEqualTo(String value) {
			addCriterion("nome_file =", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileNotEqualTo(String value) {
			addCriterion("nome_file <>", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileGreaterThan(String value) {
			addCriterion("nome_file >", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileGreaterThanOrEqualTo(String value) {
			addCriterion("nome_file >=", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileLessThan(String value) {
			addCriterion("nome_file <", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileLessThanOrEqualTo(String value) {
			addCriterion("nome_file <=", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileLike(String value) {
			addCriterion("nome_file like", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileNotLike(String value) {
			addCriterion("nome_file not like", value, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileIn(List<String> values) {
			addCriterion("nome_file in", values, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileNotIn(List<String> values) {
			addCriterion("nome_file not in", values, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileBetween(String value1, String value2) {
			addCriterion("nome_file between", value1, value2, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andNomeFileNotBetween(String value1, String value2) {
			addCriterion("nome_file not between", value1, value2, "nomeFile");
			return (Criteria) this;
		}

		public Criteria andImpDatoAggiuntivoLikeInsensitive(String value) {
			addCriterion("upper(imp_dato_aggiuntivo) like", value.toUpperCase(), "impDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andImpNoteLikeInsensitive(String value) {
			addCriterion("upper(imp_note) like", value.toUpperCase(), "impNote");
			return (Criteria) this;
		}

		public Criteria andExpDatoAggiuntivoLikeInsensitive(String value) {
			addCriterion("upper(exp_dato_aggiuntivo) like", value.toUpperCase(), "expDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andExpNoteLikeInsensitive(String value) {
			addCriterion("upper(exp_note) like", value.toUpperCase(), "expNote");
			return (Criteria) this;
		}

		public Criteria andVivDatoAggiuntivoLikeInsensitive(String value) {
			addCriterion("upper(viv_dato_aggiuntivo) like", value.toUpperCase(), "vivDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andVivNoteLikeInsensitive(String value) {
			addCriterion("upper(viv_note) like", value.toUpperCase(), "vivNote");
			return (Criteria) this;
		}

		public Criteria andPassDatoAggiuntivoLikeInsensitive(String value) {
			addCriterion("upper(pass_dato_aggiuntivo) like", value.toUpperCase(), "passDatoAggiuntivo");
			return (Criteria) this;
		}

		public Criteria andPassNoteLikeInsensitive(String value) {
			addCriterion("upper(pass_note) like", value.toUpperCase(), "passNote");
			return (Criteria) this;
		}

		public Criteria andNomeFileLikeInsensitive(String value) {
			addCriterion("upper(nome_file) like", value.toUpperCase(), "nomeFile");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_t_dati_domanda
	 * @mbg.generated  Mon Sep 28 14:55:54 CEST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_t_dati_domanda
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 01 10:27:28 CEST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}