package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.GenericExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CarTPagamentoExample extends GenericExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public CarTPagamentoExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    protected void addCriterionForJDBCDate(String condition, Date value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value.getTime()), property);
    }

    protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
      Iterator<Date> iter = values.iterator();
      while (iter.hasNext()) {
        dateList.add(new java.sql.Date(iter.next().getTime()));
      }
      addCriterion(condition, dateList, property);
    }

    protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
    }

    public Criteria andIdPagamentoIsNull() {
      addCriterion("id_pagamento is null");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoIsNotNull() {
      addCriterion("id_pagamento is not null");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoEqualTo(Long value) {
      addCriterion("id_pagamento =", value, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoNotEqualTo(Long value) {
      addCriterion("id_pagamento <>", value, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoGreaterThan(Long value) {
      addCriterion("id_pagamento >", value, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoGreaterThanOrEqualTo(Long value) {
      addCriterion("id_pagamento >=", value, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoLessThan(Long value) {
      addCriterion("id_pagamento <", value, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoLessThanOrEqualTo(Long value) {
      addCriterion("id_pagamento <=", value, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoIn(List<Long> values) {
      addCriterion("id_pagamento in", values, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoNotIn(List<Long> values) {
      addCriterion("id_pagamento not in", values, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoBetween(Long value1, Long value2) {
      addCriterion("id_pagamento between", value1, value2, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andIdPagamentoNotBetween(Long value1, Long value2) {
      addCriterion("id_pagamento not between", value1, value2, "idPagamento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoIsNull() {
      addCriterion("numero_documento is null");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoIsNotNull() {
      addCriterion("numero_documento is not null");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoEqualTo(String value) {
      addCriterion("numero_documento =", value, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoNotEqualTo(String value) {
      addCriterion("numero_documento <>", value, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoGreaterThan(String value) {
      addCriterion("numero_documento >", value, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoGreaterThanOrEqualTo(String value) {
      addCriterion("numero_documento >=", value, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoLessThan(String value) {
      addCriterion("numero_documento <", value, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoLessThanOrEqualTo(String value) {
      addCriterion("numero_documento <=", value, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoLike(String value) {
      addCriterion("numero_documento like", value, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoNotLike(String value) {
      addCriterion("numero_documento not like", value, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoIn(List<String> values) {
      addCriterion("numero_documento in", values, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoNotIn(List<String> values) {
      addCriterion("numero_documento not in", values, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoBetween(String value1, String value2) {
      addCriterion("numero_documento between", value1, value2, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoNotBetween(String value1, String value2) {
      addCriterion("numero_documento not between", value1, value2, "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoIsNull() {
      addCriterion("data_pagamento is null");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoIsNotNull() {
      addCriterion("data_pagamento is not null");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoEqualTo(Date value) {
      addCriterionForJDBCDate("data_pagamento =", value, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoNotEqualTo(Date value) {
      addCriterionForJDBCDate("data_pagamento <>", value, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoGreaterThan(Date value) {
      addCriterionForJDBCDate("data_pagamento >", value, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("data_pagamento >=", value, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoLessThan(Date value) {
      addCriterionForJDBCDate("data_pagamento <", value, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("data_pagamento <=", value, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoIn(List<Date> values) {
      addCriterionForJDBCDate("data_pagamento in", values, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoNotIn(List<Date> values) {
      addCriterionForJDBCDate("data_pagamento not in", values, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("data_pagamento between", value1, value2, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andDataPagamentoNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("data_pagamento not between", value1, value2, "dataPagamento");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaIsNull() {
      addCriterion("id_richiesta is null");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaIsNotNull() {
      addCriterion("id_richiesta is not null");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaEqualTo(Long value) {
      addCriterion("id_richiesta =", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaNotEqualTo(Long value) {
      addCriterion("id_richiesta <>", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaGreaterThan(Long value) {
      addCriterion("id_richiesta >", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaGreaterThanOrEqualTo(Long value) {
      addCriterion("id_richiesta >=", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaLessThan(Long value) {
      addCriterion("id_richiesta <", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaLessThanOrEqualTo(Long value) {
      addCriterion("id_richiesta <=", value, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaIn(List<Long> values) {
      addCriterion("id_richiesta in", values, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaNotIn(List<Long> values) {
      addCriterion("id_richiesta not in", values, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaBetween(Long value1, Long value2) {
      addCriterion("id_richiesta between", value1, value2, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdRichiestaNotBetween(Long value1, Long value2) {
      addCriterion("id_richiesta not between", value1, value2, "idRichiesta");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoIsNull() {
      addCriterion("id_mezzo_pagamento is null");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoIsNotNull() {
      addCriterion("id_mezzo_pagamento is not null");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoEqualTo(Long value) {
      addCriterion("id_mezzo_pagamento =", value, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoNotEqualTo(Long value) {
      addCriterion("id_mezzo_pagamento <>", value, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoGreaterThan(Long value) {
      addCriterion("id_mezzo_pagamento >", value, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoGreaterThanOrEqualTo(Long value) {
      addCriterion("id_mezzo_pagamento >=", value, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoLessThan(Long value) {
      addCriterion("id_mezzo_pagamento <", value, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoLessThanOrEqualTo(Long value) {
      addCriterion("id_mezzo_pagamento <=", value, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoIn(List<Long> values) {
      addCriterion("id_mezzo_pagamento in", values, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoNotIn(List<Long> values) {
      addCriterion("id_mezzo_pagamento not in", values, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoBetween(Long value1, Long value2) {
      addCriterion("id_mezzo_pagamento between", value1, value2, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andIdMezzoPagamentoNotBetween(Long value1, Long value2) {
      addCriterion("id_mezzo_pagamento not between", value1, value2, "idMezzoPagamento");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoIsNull() {
      addCriterion("nome_file_allegato is null");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoIsNotNull() {
      addCriterion("nome_file_allegato is not null");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoEqualTo(String value) {
      addCriterion("nome_file_allegato =", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoNotEqualTo(String value) {
      addCriterion("nome_file_allegato <>", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoGreaterThan(String value) {
      addCriterion("nome_file_allegato >", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoGreaterThanOrEqualTo(String value) {
      addCriterion("nome_file_allegato >=", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoLessThan(String value) {
      addCriterion("nome_file_allegato <", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoLessThanOrEqualTo(String value) {
      addCriterion("nome_file_allegato <=", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoLike(String value) {
      addCriterion("nome_file_allegato like", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoNotLike(String value) {
      addCriterion("nome_file_allegato not like", value, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoIn(List<String> values) {
      addCriterion("nome_file_allegato in", values, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoNotIn(List<String> values) {
      addCriterion("nome_file_allegato not in", values, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoBetween(String value1, String value2) {
      addCriterion("nome_file_allegato between", value1, value2, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoNotBetween(String value1, String value2) {
      addCriterion("nome_file_allegato not between", value1, value2, "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andMittenteIsNull() {
      addCriterion("mittente is null");
      return (Criteria) this;
    }

    public Criteria andMittenteIsNotNull() {
      addCriterion("mittente is not null");
      return (Criteria) this;
    }

    public Criteria andMittenteEqualTo(String value) {
      addCriterion("mittente =", value, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteNotEqualTo(String value) {
      addCriterion("mittente <>", value, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteGreaterThan(String value) {
      addCriterion("mittente >", value, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteGreaterThanOrEqualTo(String value) {
      addCriterion("mittente >=", value, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteLessThan(String value) {
      addCriterion("mittente <", value, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteLessThanOrEqualTo(String value) {
      addCriterion("mittente <=", value, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteLike(String value) {
      addCriterion("mittente like", value, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteNotLike(String value) {
      addCriterion("mittente not like", value, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteIn(List<String> values) {
      addCriterion("mittente in", values, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteNotIn(List<String> values) {
      addCriterion("mittente not in", values, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteBetween(String value1, String value2) {
      addCriterion("mittente between", value1, value2, "mittente");
      return (Criteria) this;
    }

    public Criteria andMittenteNotBetween(String value1, String value2) {
      addCriterion("mittente not between", value1, value2, "mittente");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertIsNull() {
      addCriterion("id_utente_insert is null");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertIsNotNull() {
      addCriterion("id_utente_insert is not null");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertEqualTo(Long value) {
      addCriterion("id_utente_insert =", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertNotEqualTo(Long value) {
      addCriterion("id_utente_insert <>", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertGreaterThan(Long value) {
      addCriterion("id_utente_insert >", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertGreaterThanOrEqualTo(Long value) {
      addCriterion("id_utente_insert >=", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertLessThan(Long value) {
      addCriterion("id_utente_insert <", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertLessThanOrEqualTo(Long value) {
      addCriterion("id_utente_insert <=", value, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertIn(List<Long> values) {
      addCriterion("id_utente_insert in", values, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertNotIn(List<Long> values) {
      addCriterion("id_utente_insert not in", values, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertBetween(Long value1, Long value2) {
      addCriterion("id_utente_insert between", value1, value2, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteInsertNotBetween(Long value1, Long value2) {
      addCriterion("id_utente_insert not between", value1, value2, "idUtenteInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertIsNull() {
      addCriterion("data_insert is null");
      return (Criteria) this;
    }

    public Criteria andDataInsertIsNotNull() {
      addCriterion("data_insert is not null");
      return (Criteria) this;
    }

    public Criteria andDataInsertEqualTo(Date value) {
      addCriterion("data_insert =", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertNotEqualTo(Date value) {
      addCriterion("data_insert <>", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertGreaterThan(Date value) {
      addCriterion("data_insert >", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertGreaterThanOrEqualTo(Date value) {
      addCriterion("data_insert >=", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertLessThan(Date value) {
      addCriterion("data_insert <", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertLessThanOrEqualTo(Date value) {
      addCriterion("data_insert <=", value, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertIn(List<Date> values) {
      addCriterion("data_insert in", values, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertNotIn(List<Date> values) {
      addCriterion("data_insert not in", values, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertBetween(Date value1, Date value2) {
      addCriterion("data_insert between", value1, value2, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andDataInsertNotBetween(Date value1, Date value2) {
      addCriterion("data_insert not between", value1, value2, "dataInsert");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateIsNull() {
      addCriterion("id_utente_update is null");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateIsNotNull() {
      addCriterion("id_utente_update is not null");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateEqualTo(Long value) {
      addCriterion("id_utente_update =", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateNotEqualTo(Long value) {
      addCriterion("id_utente_update <>", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateGreaterThan(Long value) {
      addCriterion("id_utente_update >", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateGreaterThanOrEqualTo(Long value) {
      addCriterion("id_utente_update >=", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateLessThan(Long value) {
      addCriterion("id_utente_update <", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateLessThanOrEqualTo(Long value) {
      addCriterion("id_utente_update <=", value, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateIn(List<Long> values) {
      addCriterion("id_utente_update in", values, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateNotIn(List<Long> values) {
      addCriterion("id_utente_update not in", values, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateBetween(Long value1, Long value2) {
      addCriterion("id_utente_update between", value1, value2, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andIdUtenteUpdateNotBetween(Long value1, Long value2) {
      addCriterion("id_utente_update not between", value1, value2, "idUtenteUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateIsNull() {
      addCriterion("data_update is null");
      return (Criteria) this;
    }

    public Criteria andDataUpdateIsNotNull() {
      addCriterion("data_update is not null");
      return (Criteria) this;
    }

    public Criteria andDataUpdateEqualTo(Date value) {
      addCriterion("data_update =", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateNotEqualTo(Date value) {
      addCriterion("data_update <>", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateGreaterThan(Date value) {
      addCriterion("data_update >", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateGreaterThanOrEqualTo(Date value) {
      addCriterion("data_update >=", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateLessThan(Date value) {
      addCriterion("data_update <", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateLessThanOrEqualTo(Date value) {
      addCriterion("data_update <=", value, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateIn(List<Date> values) {
      addCriterion("data_update in", values, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateNotIn(List<Date> values) {
      addCriterion("data_update not in", values, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateBetween(Date value1, Date value2) {
      addCriterion("data_update between", value1, value2, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andDataUpdateNotBetween(Date value1, Date value2) {
      addCriterion("data_update not between", value1, value2, "dataUpdate");
      return (Criteria) this;
    }

    public Criteria andNumeroDocumentoLikeInsensitive(String value) {
      addCriterion("upper(numero_documento) like", value.toUpperCase(), "numeroDocumento");
      return (Criteria) this;
    }

    public Criteria andNomeFileAllegatoLikeInsensitive(String value) {
      addCriterion("upper(nome_file_allegato) like", value.toUpperCase(), "nomeFileAllegato");
      return (Criteria) this;
    }

    public Criteria andMittenteLikeInsensitive(String value) {
      addCriterion("upper(mittente) like", value.toUpperCase(), "mittente");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table caronte.car_t_pagamento
   * @mbg.generated  Wed Oct 31 16:30:00 CET 2018
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table caronte.car_t_pagamento
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 14 19:16:19 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}