package it.aizoon.ersaf.dto.generati;

import it.aizoon.ersaf.dto.BaseDto;
import java.util.Date;

public class CarTControlloFisico extends BaseDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.id_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private Long idControlloFisico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.id_controllo
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private Long idControllo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x1
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x2
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x4
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x5
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x6
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x7
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x8
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x9
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x10
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x11
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.note_controllo_5x11
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String noteControllo5x11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x12
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x13
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x14
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x15
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x16
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x17
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x18
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x19
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x20
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x21
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x22
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.note_controllo_5x22
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String noteControllo5x22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.fl_controllo_5x23
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private String flControllo5x23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.id_utente_inserimento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private Long idUtenteInserimento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.data_inserimento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private Date dataInserimento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.id_utente_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private Long idUtenteAggiornamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caronte.car_t_controllo_fisico.data_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    private Date dataAggiornamento;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.id_controllo_fisico
     *
     * @return the value of caronte.car_t_controllo_fisico.id_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public Long getIdControlloFisico() {
        return idControlloFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.id_controllo_fisico
     *
     * @param idControlloFisico the value for caronte.car_t_controllo_fisico.id_controllo_fisico
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setIdControlloFisico(Long idControlloFisico) {
        this.idControlloFisico = idControlloFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.id_controllo
     *
     * @return the value of caronte.car_t_controllo_fisico.id_controllo
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public Long getIdControllo() {
        return idControllo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.id_controllo
     *
     * @param idControllo the value for caronte.car_t_controllo_fisico.id_controllo
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setIdControllo(Long idControllo) {
        this.idControllo = idControllo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x1
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x1
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x1() {
        return flControllo5x1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x1
     *
     * @param flControllo5x1 the value for caronte.car_t_controllo_fisico.fl_controllo_5x1
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x1(String flControllo5x1) {
        this.flControllo5x1 = flControllo5x1 == null ? null : flControllo5x1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x2
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x2
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x2() {
        return flControllo5x2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x2
     *
     * @param flControllo5x2 the value for caronte.car_t_controllo_fisico.fl_controllo_5x2
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x2(String flControllo5x2) {
        this.flControllo5x2 = flControllo5x2 == null ? null : flControllo5x2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x4
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x4
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x4() {
        return flControllo5x4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x4
     *
     * @param flControllo5x4 the value for caronte.car_t_controllo_fisico.fl_controllo_5x4
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x4(String flControllo5x4) {
        this.flControllo5x4 = flControllo5x4 == null ? null : flControllo5x4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x5
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x5
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x5() {
        return flControllo5x5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x5
     *
     * @param flControllo5x5 the value for caronte.car_t_controllo_fisico.fl_controllo_5x5
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x5(String flControllo5x5) {
        this.flControllo5x5 = flControllo5x5 == null ? null : flControllo5x5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x6
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x6
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x6() {
        return flControllo5x6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x6
     *
     * @param flControllo5x6 the value for caronte.car_t_controllo_fisico.fl_controllo_5x6
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x6(String flControllo5x6) {
        this.flControllo5x6 = flControllo5x6 == null ? null : flControllo5x6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x7
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x7
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x7() {
        return flControllo5x7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x7
     *
     * @param flControllo5x7 the value for caronte.car_t_controllo_fisico.fl_controllo_5x7
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x7(String flControllo5x7) {
        this.flControllo5x7 = flControllo5x7 == null ? null : flControllo5x7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x8
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x8
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x8() {
        return flControllo5x8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x8
     *
     * @param flControllo5x8 the value for caronte.car_t_controllo_fisico.fl_controllo_5x8
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x8(String flControllo5x8) {
        this.flControllo5x8 = flControllo5x8 == null ? null : flControllo5x8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x9
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x9
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x9() {
        return flControllo5x9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x9
     *
     * @param flControllo5x9 the value for caronte.car_t_controllo_fisico.fl_controllo_5x9
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x9(String flControllo5x9) {
        this.flControllo5x9 = flControllo5x9 == null ? null : flControllo5x9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x10
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x10
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x10() {
        return flControllo5x10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x10
     *
     * @param flControllo5x10 the value for caronte.car_t_controllo_fisico.fl_controllo_5x10
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x10(String flControllo5x10) {
        this.flControllo5x10 = flControllo5x10 == null ? null : flControllo5x10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x11
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x11
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x11() {
        return flControllo5x11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x11
     *
     * @param flControllo5x11 the value for caronte.car_t_controllo_fisico.fl_controllo_5x11
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x11(String flControllo5x11) {
        this.flControllo5x11 = flControllo5x11 == null ? null : flControllo5x11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.note_controllo_5x11
     *
     * @return the value of caronte.car_t_controllo_fisico.note_controllo_5x11
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getNoteControllo5x11() {
        return noteControllo5x11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.note_controllo_5x11
     *
     * @param noteControllo5x11 the value for caronte.car_t_controllo_fisico.note_controllo_5x11
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setNoteControllo5x11(String noteControllo5x11) {
        this.noteControllo5x11 = noteControllo5x11 == null ? null : noteControllo5x11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x12
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x12
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x12() {
        return flControllo5x12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x12
     *
     * @param flControllo5x12 the value for caronte.car_t_controllo_fisico.fl_controllo_5x12
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x12(String flControllo5x12) {
        this.flControllo5x12 = flControllo5x12 == null ? null : flControllo5x12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x13
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x13
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x13() {
        return flControllo5x13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x13
     *
     * @param flControllo5x13 the value for caronte.car_t_controllo_fisico.fl_controllo_5x13
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x13(String flControllo5x13) {
        this.flControllo5x13 = flControllo5x13 == null ? null : flControllo5x13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x14
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x14
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x14() {
        return flControllo5x14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x14
     *
     * @param flControllo5x14 the value for caronte.car_t_controllo_fisico.fl_controllo_5x14
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x14(String flControllo5x14) {
        this.flControllo5x14 = flControllo5x14 == null ? null : flControllo5x14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x15
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x15
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x15() {
        return flControllo5x15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x15
     *
     * @param flControllo5x15 the value for caronte.car_t_controllo_fisico.fl_controllo_5x15
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x15(String flControllo5x15) {
        this.flControllo5x15 = flControllo5x15 == null ? null : flControllo5x15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x16
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x16
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x16() {
        return flControllo5x16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x16
     *
     * @param flControllo5x16 the value for caronte.car_t_controllo_fisico.fl_controllo_5x16
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x16(String flControllo5x16) {
        this.flControllo5x16 = flControllo5x16 == null ? null : flControllo5x16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x17
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x17
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x17() {
        return flControllo5x17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x17
     *
     * @param flControllo5x17 the value for caronte.car_t_controllo_fisico.fl_controllo_5x17
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x17(String flControllo5x17) {
        this.flControllo5x17 = flControllo5x17 == null ? null : flControllo5x17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x18
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x18
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x18() {
        return flControllo5x18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x18
     *
     * @param flControllo5x18 the value for caronte.car_t_controllo_fisico.fl_controllo_5x18
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x18(String flControllo5x18) {
        this.flControllo5x18 = flControllo5x18 == null ? null : flControllo5x18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x19
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x19
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x19() {
        return flControllo5x19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x19
     *
     * @param flControllo5x19 the value for caronte.car_t_controllo_fisico.fl_controllo_5x19
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x19(String flControllo5x19) {
        this.flControllo5x19 = flControllo5x19 == null ? null : flControllo5x19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x20
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x20
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x20() {
        return flControllo5x20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x20
     *
     * @param flControllo5x20 the value for caronte.car_t_controllo_fisico.fl_controllo_5x20
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x20(String flControllo5x20) {
        this.flControllo5x20 = flControllo5x20 == null ? null : flControllo5x20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x21
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x21
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x21() {
        return flControllo5x21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x21
     *
     * @param flControllo5x21 the value for caronte.car_t_controllo_fisico.fl_controllo_5x21
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x21(String flControllo5x21) {
        this.flControllo5x21 = flControllo5x21 == null ? null : flControllo5x21.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x22
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x22
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x22() {
        return flControllo5x22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x22
     *
     * @param flControllo5x22 the value for caronte.car_t_controllo_fisico.fl_controllo_5x22
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x22(String flControllo5x22) {
        this.flControllo5x22 = flControllo5x22 == null ? null : flControllo5x22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.note_controllo_5x22
     *
     * @return the value of caronte.car_t_controllo_fisico.note_controllo_5x22
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getNoteControllo5x22() {
        return noteControllo5x22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.note_controllo_5x22
     *
     * @param noteControllo5x22 the value for caronte.car_t_controllo_fisico.note_controllo_5x22
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setNoteControllo5x22(String noteControllo5x22) {
        this.noteControllo5x22 = noteControllo5x22 == null ? null : noteControllo5x22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x23
     *
     * @return the value of caronte.car_t_controllo_fisico.fl_controllo_5x23
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public String getFlControllo5x23() {
        return flControllo5x23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.fl_controllo_5x23
     *
     * @param flControllo5x23 the value for caronte.car_t_controllo_fisico.fl_controllo_5x23
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setFlControllo5x23(String flControllo5x23) {
        this.flControllo5x23 = flControllo5x23 == null ? null : flControllo5x23.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.id_utente_inserimento
     *
     * @return the value of caronte.car_t_controllo_fisico.id_utente_inserimento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public Long getIdUtenteInserimento() {
        return idUtenteInserimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.id_utente_inserimento
     *
     * @param idUtenteInserimento the value for caronte.car_t_controllo_fisico.id_utente_inserimento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setIdUtenteInserimento(Long idUtenteInserimento) {
        this.idUtenteInserimento = idUtenteInserimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.data_inserimento
     *
     * @return the value of caronte.car_t_controllo_fisico.data_inserimento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public Date getDataInserimento() {
        return dataInserimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.data_inserimento
     *
     * @param dataInserimento the value for caronte.car_t_controllo_fisico.data_inserimento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setDataInserimento(Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.id_utente_aggiornamento
     *
     * @return the value of caronte.car_t_controllo_fisico.id_utente_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public Long getIdUtenteAggiornamento() {
        return idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.id_utente_aggiornamento
     *
     * @param idUtenteAggiornamento the value for caronte.car_t_controllo_fisico.id_utente_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
        this.idUtenteAggiornamento = idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caronte.car_t_controllo_fisico.data_aggiornamento
     *
     * @return the value of caronte.car_t_controllo_fisico.data_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public Date getDataAggiornamento() {
        return dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caronte.car_t_controllo_fisico.data_aggiornamento
     *
     * @param dataAggiornamento the value for caronte.car_t_controllo_fisico.data_aggiornamento
     *
     * @mbg.generated Wed Dec 23 16:26:49 CET 2020
     */
    public void setDataAggiornamento(Date dataAggiornamento) {
        this.dataAggiornamento = dataAggiornamento;
    }
}